      SUBROUTINE EIRENE_BROAD_PEDIST_USR( XTIM )
      USE EIRMOD_PRECISION, ONLY: DP
      USE EIRMOD_PARMMOD, ONLY: NSTRA

      IMPLICIT NONE

      !> time allocated for stratum
      REAL(DP), INTENT(IN) :: XTIM(0:NSTRA)

      END SUBROUTINE EIRENE_BROAD_PEDIST_USR
