C  CALLED FROM MAIN ROUTINE EIRENE TO PRODUCE FURTHER, 3RD PARTY
C  PRODUCED (POST PROCESSED) VOLUME TALLIES FOR PRINTOUT AND GRAPHICAL OUTPUT

C  in case of an underlying coarser grid, these additional tallies
C  are set on this coarse grid.
C
      SUBROUTINE EIRENE_OUTUSR
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD

      IMPLICIT NONE
      RETURN
      END
