      SUBROUTINE EIRENE_PEDIST_USR( XTIM, XX1 )
      USE EIRMOD_PRECISION, ONLY: DP
      USE EIRMOD_PARMMOD, ONLY: NSTRA

      IMPLICIT NONE

      !> time allocated for stratum
      REAL(DP), INTENT(INOUT) :: XTIM(0:NSTRA)
      REAL(DP), INTENT(IN) :: XX1 !< remaining CPU time

      END SUBROUTINE EIRENE_PEDIST_USR
