c
      SUBROUTINE EIRENE_TALUSR(ICOUNT,VECTOR,TALTOT,TALAV,
     .                  TXTTL,TXTSP,TXTUN,ILAST,*)

C  USER-SUPPLIED POST-PROCESSED TALLY NO. ICOUNT, FOR STRATUM ISTRA,
C  STORED ON VECTOR. (ISTRA IS KNOWN FROM COMMON COMPRT)
C
C  RETURN 1:       DO NOT PRINTOUT VOLUME-AVERAGED TALLY "VECTOR"
C                  VECTOR NEEDS NOT BE RETURNED. INSTEAD, THE POST-
C                  PROCESSED TALLY CAN ALSO BE PUT ONTO THE ADDITIONAL TALLY
C                  STORAGES (ADDV,COLV,...) IF STORAGE IS PROVIDED 
C                  AND IF THE PARAMETERS NADVI, NCLVI, ETC. IN BLOCK 10A, OR 10B,
C                  ARE PROPERLY SET.
C  RETURN  :       PRINTOUT VOLUME-AVERAGED TALLY VECTOR(I), I=1,NRAD,
C                  AS SPECIFIED IN INPUT BLOCK 11 FOR PRINTOUT OF TALLY NO. 0
C  INPUT:  ICOUNT: COUNTS THE NUMBER OF CALL TO TALUSR FOR EACH STRATUM
C                  FIRST CALL FOR STRATUM ISTRA: ICOUNT=1
C  OUTPUT: ILAST:  IF ILAST.GT.ICOUNT, THEN TALSUR IS CALLED
C                  ONCE MORE WITH ICOUNT INCREASED BY ONE
C                  OTHERWISE: TALUSR IS NOT CALLED AGAIN FOR THE CURRENT TALLY
C          TXTTL,TXTSP,TXTUN: TEXT IN PRINTOUT FOR THIS TALLY: NAME, SPECIES, UNITS
C          TALTOT,TALAV: TOTAL AND AVERAGE VALUE, FOR PRINTOUT
C

      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD

      implicit NONE
      integer, intent(in) :: icount
      integer, intent(out) :: ilast
      real(dp), intent(inout) :: VECTOR(*), TALTOT, TALAV

      character(len=*) :: txttl,txtsp,txtun
      TXTTL=' '
      TXTSP=' '
      TXTUN=' '
      
C
C  WRITE DIRECTLY ONTO OUTPUT STREAM IUNOUT, I.E.: NOT: RETURN 1, BUT: RETURN
 
      ILAST=0
      RETURN 
      END
