C
C
      SUBROUTINE EIRENE_PLTKI (FCN,XANF,XEND,INN,TRCPLT,LBOX)

      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CRECH
      USE EIRMOD_CCONA
      USE EIRMOD_CLMSUR
      USE EIRMOD_CPLOT
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      USE EIRMOD_STCOOR, ONLY: EIRENE_STCOOR

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: XANF, XEND
      REAL(DP) :: FCN
      INTEGER, INTENT(OUT) :: INN
      LOGICAL, INTENT(IN) :: TRCPLT,LBOX

      REAL(DP) :: XTRAN, YTRAN, XI, ETA, GERAX, GERAY, XG, YG, X, Y, DX,
     .          XP, YP, XX, YY, XXO, YYO, XINC
      INTEGER :: I, ISIDE, IFLAG, IJUMP, INC

      XTRAN(XI,ETA)=XI*COSA-ETA*SINA
      YTRAN(XI,ETA)=XI*SINA+ETA*COSA
      GERAY(XG)=(YY-YYO)/(XX-XXO)*XG+YY-XX*(YY-YYO)/(XX-XXO)
      GERAX(YG)=(YG-YY)*(XX-XXO)/(YY-YYO)+XX
      IF (TRCPLT) WRITE (iunout,*) 'PLTKI'
      IF (LBOX) THEN
        CALL GRJMP(REAL(XL1,SP),REAL(YL1,SP))
        CALL GRDRW(REAL(XL2,SP),REAL(YL1,SP))
        CALL GRDRW(REAL(XL2,SP),REAL(YL2,SP))
        CALL GRDRW(REAL(XL1,SP),REAL(YL2,SP))
        CALL GRDRW(REAL(XL1,SP),REAL(YL1,SP))
      ENDIF
      INC=100
      XINC=DBLE(INC)
      DX=(XEND-XANF)/XINC
      IFLAG=0
      ISIDE=0
      INN=0
      XX=0.
      YY=0.
      DO 431 I=1,INC+1
         X=XANF+(I-1)*DX
         Y=FCN(X)
         XXO=XX
         YYO=YY
         XX=XTRAN(X+XM,Y+YM)
         YY=YTRAN(X+XM,Y+YM)
         IJUMP=ISIDE
         ISIDE=0
         IF (XX.LE.XL1+EPS10) ISIDE=3
         IF (XX.GE.XL2-EPS10) ISIDE=2
         IF (YY.LE.YL1+EPS10) ISIDE=4
         IF (YY.GE.YL2-EPS10) ISIDE=1
         IF (ISIDE.NE.0) THEN
             IF (IFLAG.EQ.0) CYCLE
             IJUMP=ISIDE
             IF (IFLAG.NE.0) GOTO 432
         ENDIF
C        ISIDE=0
         IF (IFLAG.EQ.0.AND.I.NE.1) GOTO 432
  439    IF (I.NE.1) IFLAG=24
         IF (IFLAG.EQ.0) THEN
            IF (LZR) CALL GRJMP (REAL(XX,SP), REAL(YY,SP))
            IF (.NOT.LZR.OR.PLSTOR.OR.PLNUMS)
     .        CALL EIRENE_STCOOR(XX,YY,0)
         ENDIF
         IF (IFLAG.NE.0) THEN
         IF (LZR) CALL GRDRW (REAL(XX,SP), REAL(YY,SP))
         IF (.NOT.LZR.OR.PLSTOR.OR.PLNUMS)
     .     CALL EIRENE_STCOOR(XX,YY,1)
         ENDIF
         INN=MAX0(INN,IFLAG)
         CYCLE
  432    CONTINUE
         SELECT CASE(IJUMP)
         CASE (1)
           XP=GERAX(YL2)
           YP=YL2
         CASE (2)
           XP=XL2
CPB        YP=YTRAN(XP,FCN(XP-XM)+YM)
           YP=GERAY(XL2)
         CASE (3)
           XP=XL1
CPB        YP=YTRAN(XP,FCN(XP-XM)+YM)
           YP=GERAY(XL1)
         CASE (4)
           XP=GERAX(YL1)
           YP=YL1
         CASE DEFAULT
           GOTO 439
         END SELECT
C
         IF (IFLAG.EQ.0) THEN
            IF (LZR) CALL GRJMP (REAL(XP,SP), REAL(YP,SP))
            IF (.NOT.LZR.OR.PLSTOR.OR.PLNUMS) 
     .        CALL EIRENE_STCOOR(XP,YP,0)
         ENDIF
         IF (IFLAG.NE.0) THEN
            IF (LZR) CALL GRDRW (REAL(XP,SP), REAL(YP,SP))
            IF (.NOT.LZR.OR.PLSTOR.OR.PLNUMS) 
     .        CALL EIRENE_STCOOR(XP,YP,1)
         ENDIF
         INN=MAX0(INN,IFLAG)
         IF (IFLAG.EQ.0) GOTO 439
         IFLAG=0
C
  431 CONTINUE
      RETURN
      END SUBROUTINE EIRENE_PLTKI
