C
C
      SUBROUTINE
     .  EIRENE_PLTLNE(NRET,XX,YY,XMI2D,XMA2D,YMI2D,YMA2D,LSTORE)

      USE EIRMOD_PRECISION
      USE EIRMOD_STCOOR, ONLY: EIRENE_STCOOR

      IMPLICIT NONE

      REAL(DP), INTENT(INOUT) :: XX(*), YY(*)
      REAL(DP), INTENT(IN) :: XMI2D, XMA2D, YMI2D, YMA2D
      INTEGER, INTENT(IN) :: NRET
      LOGICAL, INTENT(IN) :: LSTORE
      REAL(DP) :: XT, YT, XTN, YTN, XT2, YT2, TESTN
      INTEGER :: IN, IFL, I
c
      DO 148 I=1,NRET
        IFL=I-1
        XTN=XX(I)
        YTN=YY(I)
        CALL EIRENE_TSTCHM(IFL,XTN,YTN,XT,YT,IN,TESTN,
     .              XMI2D,XMA2D,YMI2D,YMA2D,XT2,YT2)
C
        IF (IN.EQ.0) IN=4
        SELECT CASE (IN)
          CASE (1)
            CALL GRDRW(REAL(XTN,KIND(1.E0)),REAL(YTN,KIND(1.E0)))
            IF (LSTORE) CALL EIRENE_STCOOR(XTN,YTN,1)
          CASE (2)
            CALL GRDRW(REAL(XT,KIND(1.E0)),REAL(YT,KIND(1.E0)))
            CALL GRJMP(REAL(XTN,KIND(1.E0)),REAL(YTN,KIND(1.E0)))
            IF (LSTORE) THEN
              CALL EIRENE_STCOOR(XT,YT,0)
              CALL EIRENE_STCOOR(XTN,YTN,1)
            END IF
          CASE (3)
            CALL GRJMP(REAL(XT,KIND(1.E0)),REAL(YT,KIND(1.E0)))
            CALL GRDRW(REAL(XTN,KIND(1.E0)),REAL(YTN,KIND(1.E0)))
            IF (LSTORE) THEN
              CALL EIRENE_STCOOR(XT,YT,0)
              CALL EIRENE_STCOOR(XTN,YTN,1)
            END IF
          CASE (4)
            CALL GRJMP(REAL(XTN,KIND(1.E0)),REAL(YTN,KIND(1.E0)))
            IF (LSTORE) CALL EIRENE_STCOOR(XTN,YTN,0)
          CASE (5)
            CALL GRJMP(REAL(XT,KIND(1.E0)),REAL(YT,KIND(1.E0)))
            CALL GRDRW(REAL(XT2,KIND(1.E0)),REAL(YT2,KIND(1.E0)))
            IF (LSTORE) THEN
              CALL EIRENE_STCOOR(XT,YT,0)
              CALL EIRENE_STCOOR(XT2,YT2,1)
            END IF
        END SELECT
C
  148 CONTINUE
      return
      end
