      MODULE EIRMOD_CPES
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
 
      IMPLICIT NONE
 
      PRIVATE
 
      PUBLIC :: EIRENE_ALLOC_CPES, EIRENE_DEALLOC_CPES, EIRENE_INIT_CPES
 
      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I         NPESTR(:), NPESTA(:),
     I         NSTRPE(:)
 
      INTEGER, PUBLIC, SAVE ::
     I         NSTEFF, nprs, my_pe
 
      LOGICAL, PUBLIC, SAVE :: NLIDENT

CVKMPI CORRESPONDENCE TABLE "STRATA VERSUS PROCESSOR"
      LOGICAL,ALLOCATABLE,SAVE,PUBLIC :: PROCFORSTRA(:,:)
 
 
      CONTAINS
 
 
      SUBROUTINE EIRENE_ALLOC_CPES
 
      IF (ALLOCATED(NPESTR)) RETURN
 
      ALLOCATE (NPESTR(0:NSTRA))
      ALLOCATE (NPESTA(0:NSTRA))
      ALLOCATE (NSTRPE(0:NRPES-1))

      ALLOCATE(PROCFORSTRA(NSTRA,0:NRPES-1))
 
      WRITE (55+IFOFF,'(A,T25,I15)')
     .      ' CPES ',(2*(NSTRA+1)+NRPES)*4 + NSTRA*NRPES*4
 
      CALL EIRENE_INIT_CPES
 
      RETURN
      END SUBROUTINE EIRENE_ALLOC_CPES
 
 
      SUBROUTINE EIRENE_DEALLOC_CPES
 
      IF (.NOT.ALLOCATED(NPESTR)) RETURN
 
      DEALLOCATE (NPESTR)
      DEALLOCATE (NPESTA)
      DEALLOCATE (NSTRPE)

      DEALLOCATE(PROCFORSTRA)
 
      RETURN
      END SUBROUTINE EIRENE_DEALLOC_CPES
 
 
      SUBROUTINE EIRENE_INIT_CPES
 
      NPESTR = 0
      NPESTA = 0
      NSTRPE = 0

      PROCFORSTRA=.TRUE. !VK
 
      RETURN
      END SUBROUTINE EIRENE_INIT_CPES
 
      END MODULE EIRMOD_CPES
