include:
    - '.update_fork_branches.yml'
    - '.tag_and_deploy.yml'

variables:
    SERVER_DOMAIN: 'jugit.fz-juelich.de'
    SAMPLE_CASE_VERSION: '6750748c15c0f76a079c9d39bf0474f78b5470c4'

stages:
    - build:library
    - build:executable
    - run
    - test
    - coverage
    - tag
    - deploy
    - on-schedule

.build_executable: &build_executable
    stage: build:executable
    except: 
        - schedules
    script:
        - git config --global core.packedGitLimit 128m
        - git config --global core.packedGitWindowSize 128m
        - git config --global pack.deltaCacheSize 128m
        - git config --global pack.packSizeLimit 128m
        - git config --global pack.windowMemory 128m
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${SERVER_DOMAIN}/eirene/EIRENE-sample-cases.git
        - cd EIRENE-sample-cases
        - git checkout ${SAMPLE_CASE_VERSION}
        - cd ${PATH_CASE}
        - make
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - EIRENE-sample-cases/${PATH_CASE}

.run: &run
    stage: run
    except: 
        - schedules
    script:
        - cd EIRENE-sample-cases/${PATH_CASE}
        - make output
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - EIRENE-sample-cases/${PATH_CASE}
        when: always

.test: &test
    stage: test
    except: 
        - schedules
    script:
        - cd EIRENE-sample-cases/${PATH_CASE}
        - make test
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - EIRENE-sample-cases/${PATH_CASE}/output/
        when: on_failure

build_library:
    stage: build:library
    except: 
        - schedules
    script:
        - mkdir buildRelease
        - cd buildRelease
        - FC=gfortran cmake ../src
        - make EIRENE
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - buildRelease/
            - libRelease/

build_standalone_1D_slab:
    <<: *build_executable
    variables:
        PATH_CASE: "1D-H_slab"

run_standalone_1D-H_slab:
    <<: *run
    variables:
        PATH_CASE: "1D-H_slab"
    dependencies:
        - build_standalone_1D_slab

test_standalone_1D-H_slab:
    <<: *test
    variables:
        PATH_CASE: "1D-H_slab"
    dependencies:
        - run_standalone_1D-H_slab

build_standalone_1D_slab_with_farming:
    <<: *build_executable
    variables:
        PATH_CASE: "1D-H_slab_with_farming"
    only:
        - PB/feature/farming

run_standalone_1D-H_slab_with_farming:
    <<: *run
    variables:
        PATH_CASE: "1D-H_slab_with_farming"
    only:
        - PB/feature/farming
    dependencies:
        - build_standalone_1D_slab_with_farming

test_standalone_1D-H_slab_with_farming:
    <<: *test
    variables:
        PATH_CASE: "1D-H_slab_with_farming"
    only:
        - PB/feature/farming
    dependencies:
        - run_standalone_1D-H_slab_with_farming

build_standalone_2D_slab:
    <<: *build_executable
    variables:
        PATH_CASE: "2D-D_slab"

run_standalone_2D-D_slab:
    <<: *run
    variables:
        PATH_CASE: "2D-D_slab"
    dependencies:
        - build_standalone_2D_slab

test_standalone_2D-D_slab:
    <<: *test
    variables:
        PATH_CASE: "2D-D_slab"
    dependencies:
        - run_standalone_2D-D_slab

build_standalone_ITER_1573:
    <<: *build_executable
    variables:
        PATH_CASE: "ITER_1573"
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - binRelease/
            - EIRENE-sample-cases/${PATH_CASE}

run_standalone_ITER_1573:
    <<: *run
    variables:
        PATH_CASE: "ITER_1573"
    dependencies:
        - build_standalone_ITER_1573

test_standalone_ITER_1573:
    <<: *test
    variables:
        PATH_CASE: "ITER_1573"
    dependencies:
        - run_standalone_ITER_1573

build_EMC3-EIRENE:
    <<: *build_executable
    variables:
        PATH_CASE: "EMC3"
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - EIRENE-sample-cases/EMC3/emc3/binRelease/
            - EIRENE-sample-cases/EMC3/W7X_Limiter/

run_EMC3-EIRENE_H:
    <<: *run
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H"
    dependencies:
        - build_EMC3-EIRENE

test_EMC3-EIRENE_H:
    <<: *test
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H"
    dependencies:
        - build_EMC3-EIRENE
        - run_EMC3-EIRENE_H

run_EMC3-EIRENE_He:
    <<: *run
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/He"
    dependencies:
        - build_EMC3-EIRENE

test_EMC3-EIRENE_He:
    <<: *test
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/He"
    dependencies:
        - build_EMC3-EIRENE
        - run_EMC3-EIRENE_He
    
run_EMC3-EIRENE_H_multiStrata:
    <<: *run
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_multiStrata"
    dependencies:
        - build_EMC3-EIRENE

test_EMC3-EIRENE_H_multiStrata:
    <<: *test
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_multiStrata"
    dependencies:
        - build_EMC3-EIRENE
        - run_EMC3-EIRENE_H_multiStrata
    
run_EMC3-EIRENE_H_multiStrataMpi:
    <<: *run
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_multiStrataMpi"
    dependencies:
        - build_EMC3-EIRENE

test_EMC3-EIRENE_H_multiStrataMpi:
    <<: *test
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_multiStrataMpi"
    dependencies:
        - build_EMC3-EIRENE
        - run_EMC3-EIRENE_H_multiStrataMpi
    
run_EMC3-EIRENE_H_multiStrataMpi2:
    <<: *run
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_multiStrataMpi2"
    dependencies:
        - build_EMC3-EIRENE

test_EMC3-EIRENE_H_multiStrataMpi2:
    <<: *test
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_multiStrataMpi2"
    dependencies:
        - build_EMC3-EIRENE
        - run_EMC3-EIRENE_H_multiStrataMpi2
    
run_EMC3-EIRENE_H_multiStrataMpi3:
    <<: *run
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_multiStrataMpi3"
    dependencies:
        - build_EMC3-EIRENE

test_EMC3-EIRENE_H_multiStrataMpi3:
    <<: *test
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_multiStrataMpi3"
    dependencies:
        - build_EMC3-EIRENE
        - run_EMC3-EIRENE_H_multiStrataMpi3

run_EMC3-EIRENE_H_profile:
    <<: *run
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_profile"
    dependencies:
        - build_EMC3-EIRENE

test_EMC3-EIRENE_H_profile:
    <<: *test
    variables:
        PATH_CASE: "EMC3/W7X_Limiter/H_profile"
    dependencies:
        - build_EMC3-EIRENE
        - run_EMC3-EIRENE_H_profile

coverage_report:
    stage: coverage
    only:
        - develop
        - master
    except:
        - schedules
    script:
        - mkdir buildCoverage
        - cd buildCoverage
        - FC=gfortran cmake ../src -DCMAKE_BUILD_TYPE=Coverage
        - make EIRENE
        - cd ..
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${SERVER_DOMAIN}/eirene/EIRENE-sample-cases.git
        - cd EIRENE-sample-cases
        - git checkout ${SAMPLE_CASE_VERSION}
        - make coverageReport FFLAGS="-g -fprofile-arcs -ftest-coverage" CONFIG=Coverage
    dependencies: []
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - EIRENE-sample-cases/coverage.info
            - EIRENE-sample-cases/coverageReport
