before_script:
    # Install build dependencies
    - apt-get update && apt-get -y install cmake gfortran mpich libmpich-dev

build_gfortran:
   stage: build
   script:
      - mkdir build
      - cd build
      - FC=gfortran cmake ../src
      - make

test_standalone:
    stage: test
    script:
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@src.ipp.kfa-juelich.de/eirene/EIRENE-sample-cases.git
        - cd EIRENE-sample-cases
        - git checkout buildSystem
        - cd 1D-H_slab
        - ls -l /usr/bin/mpi*
        - make test