.tag_database: &tag_database
    stage: tag
    only: 
        - master
    except: 
        - schedules
    before_script:
        # Configure git user information
        - git config --global user.email "noreply@${SERVER_DOMAIN}"
        - git config --global user.name "GitLab CI"
        # Run ssh-agent (inside the build environment)
        - eval $(ssh-agent -s)
        # Add the required SSH keys to the agent store
        # We're using tr to fix line endings which makes ed25519 keys work
        # without extra base64 encoding.
        - echo "${SSH_KEY_EIRENE_DEPLOY}" | tr -d '\r' | ssh-add - > /dev/null
        # Create the SSH directory and give it the right permissions
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        # Use ssh-keyscan to scan the keys of your private servers.
        - ssh-keyscan ${SERVER_DOMAIN} >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        # Change origin push URL to get write access to EIRENE repository
        - git remote set-url --push origin git@${SERVER_DOMAIN}:eirene/eirene.git
    script:
        - cd Database/AMdata
        # Identify latest database change via tag and check for new commits
        # only since then
        - TAG=$(git tag --sort=v:refname -l $DATABASE-* | tail -n 1)
        - if [ -n "$TAG" ];
          then
            REV_RANGE="$TAG..";
          fi
        - COMMITS=$(git log --reverse --pretty=format:%H $REV_RANGE $DATABASE.tex)
        # For each database commit add tag "database-date" with date of commit
        #   if same tag name exist already, add enumerated suffix
        - for COMMIT in $COMMITS; 
          do
            DATE=$(git show -s --format=%ad --date=short $COMMIT);
            SUFFIX=$(git tag -l $DATABASE-$DATE* | wc -l);
            if [[ "$SUFFIX" > 0 ]];
            then
              DATE="${DATE}_$SUFFIX";
            fi;
            git tag -a -m "$DATABASE update" $DATABASE-$DATE $COMMIT;
            git push origin $DATABASE-$DATE;
          done

tag_database_amjuel:
    <<: *tag_database
    variables:
        DATABASE: "amjuel"

tag_database_hydhel:
    <<: *tag_database
    variables:
        DATABASE: "hydhel"

tag_database_h2vibr:
    <<: *tag_database
    variables:
        DATABASE: "h2vibr"

tag_database_methane:
    <<: *tag_database
    variables:
        DATABASE: "methane"

.deploy_database_website: &deploy_database_website
    stage: deploy
    # nice if following would work in future
    #only: 
    #    refs:
    #        - tags
    #    variables:
    #        - $CI_COMMIT_TAG =~ /^$DATABASE-.*$/
        # would be ideal to trigger job only if tag is latest
        # not (yet) supported by GitLab
        #    - $CI_COMMIT_TAG == $(git tag --sort=v:refname -l $DATABASE-* | tail -n 1)
    before_script:
        # Run ssh-agent (inside the build environment)
        - eval $(ssh-agent -s)
        # Add the required SSH keys to the agent store
        # We're using tr to fix line endings which makes ed25519 keys work
        # without extra base64 encoding.
        - echo "${SSH_KEY_WEBSITE}" | tr -d '\r' | ssh-add - > /dev/null
        # Create the SSH directory and give it the right permissions
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        # Use ssh-keyscan to scan the keys of your private servers.
        - ssh-keyscan apps.fz-juelich.de >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        # Download figures of database pdf
        - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@${SERVER_DOMAIN}/eirene/eirene-database-figures.git
        # Build pdf
        - mkdir -p eirene-database-figures/$DATABASE
        - cd eirene-database-figures/$DATABASE
        - TEX_FILE=../../Database/AMdata/$DATABASE.tex
        - latexmk -silent -pdfdvi -e '$dvipdf = "dvipdfmx %O -o %D %S"' $TEX_FILE
        # Upload tex, pdf
        - rsync -t -e ssh $TEX_FILE $DATABASE.pdf eirene@apps.fz-juelich.de:/var/www/eirene
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_TAG"
        paths:
            - eirene-database-figures/$DATABASE/$DATABASE.pdf
            - Database/AMdata/$DATABASE.tex
    environment:
        name: Website/$DATABASE
        url: http://www.eirene.de/html/$DATABASE.html

deploy_database_website_amjuel:
    <<: *deploy_database_website
    variables:
        DATABASE: "amjuel"
    only: 
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^amjuel-.*/

deploy_database_website_hydhel:
    <<: *deploy_database_website
    variables:
        DATABASE: "hydhel"
    only: 
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^hydhel-.*/

deploy_database_website_h2vibr:
    <<: *deploy_database_website
    variables:
        DATABASE: "h2vibr"
    only: 
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^h2vibr-.*/

deploy_database_website_methane:
    <<: *deploy_database_website
    variables:
        DATABASE: "methane"
    only: 
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^methane-.*/

.deploy_database_hydkin: &deploy_database_hydkin
    stage: deploy
    # nice if following would work in future
    #only: 
    #    refs:
    #        - tags
    #    variables:
    #        - $CI_COMMIT_TAG =~ /^$DATABASE-.*$/
        # would be ideal to trigger job only if tag is latest
        # not (yet) supported by GitLab
        #    - $CI_COMMIT_TAG == $(git tag --sort=v:refname -l $DATABASE-* | tail -n 1)
    before_script:
        # Configure git user information
        - git config --global user.email "noreply@${SERVER_DOMAIN}"
        - git config --global user.name "GitLab CI"
        # Run ssh-agent (inside the build environment)
        - eval $(ssh-agent -s)
        # Add the required SSH keys to the agent store
        # We're using tr to fix line endings which makes ed25519 keys work
        # without extra base64 encoding.
        - echo "${SSH_KEY_HYDKIN_DEPLOY}" | tr -d '\r' | ssh-add - > /dev/null
        - echo "${SSH_KEY_WEBSITE}" | tr -d '\r' | ssh-add - > /dev/null
        # Create the SSH directory and give it the right permissions
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        # Use ssh-keyscan to scan the keys of your private servers.
        - ssh-keyscan ${SERVER_DOMAIN} >> ~/.ssh/known_hosts
        - ssh-keyscan apps.fz-juelich.de >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        # Clone HYDKIN
        - git clone git@${SERVER_DOMAIN}:hydkin/hydkin.git
        # Compute HYDKIN input und html from EIRENE databases
        - cd hydkin/tex2hyd
        - TEX_FILE=../../Database/AMdata/$DATABASE.tex
        - ./ex_prog.sh -d h0 -p "$DATABASE" $TEX_FILE ./output/
        - ./ex_prog.sh -spec -p "$DATABASE" $TEX_FILE ./output/ specific
        # Commit and push changes on HYDKIN input and html
        # Upload HYDKIN input and html files on HYDKIN website
        - if [[ "$(git diff --exit-code --quiet; echo $?)" != 0 ]];
          then
            git add ../plotform/index_*.html ../inputdir*/*.txt;
            git commit -m 'Automated database update following on EIRENE repository database update.';
            git push origin;
            rsync -t -e ssh ../inputdir/* eirene@apps.fz-juelich.de:/var/www/hydkin/inputdir;
            rsync -t -e ssh ../inputdir_amjuel/* eirene@apps.fz-juelich.de:/var/www/hydkin/inputdir_amjuel;
            rsync -t -e ssh ../inputdir_hydhel/* eirene@apps.fz-juelich.de:/var/www/hydkin/inputdir_hydhel;
            rsync -t -e ssh ../plotform/index_*.html eirene@apps.fz-juelich.de:/var/www/hydkin/plotform;
          fi
        # Tag and push database update reference tag
        - git tag -a -m "$DATABASE update" $CI_COMMIT_TAG
        - git push origin $CI_COMMIT_TAG
    environment:
        name: HYDKIN/$DATABASE
        url: http://www.hydkin.de/plotform/index_$DATABASE.html

deploy_database_hydkin_amjuel:
    <<: *deploy_database_hydkin
    variables:
        DATABASE: "amjuel"
    only: 
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^amjuel-.*/

deploy_database_hydkin_hydhel:
    <<: *deploy_database_hydkin
    variables:
        DATABASE: "hydhel"
    only: 
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^hydhel-.*/

deploy_database_hydkin_h2vibr:
    <<: *deploy_database_hydkin
    variables:
        DATABASE: "h2vibr"
    only: 
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^h2vibr-.*/

deploy_database_hydkin_methane:
    <<: *deploy_database_hydkin
    variables:
        DATABASE: "methane"
    only: 
        refs:
            - tags
        variables:
            - $CI_COMMIT_TAG =~ /^methane-.*/
