.update_fork_branches: &update_fork_branches
    stage: on-schedule
    only: 
        - schedules
    before_script:
        # Install ssh-agent and git
        - apt-get update -y && apt-get -y install openssh-client git git-svn
        # Run ssh-agent (inside the build environment)
        - eval $(ssh-agent -s)
        # Add the required SSH keys to the agent store
        # We're using tr to fix line endings which makes ed25519 keys work
        # without extra base64 encoding.
        - echo "${SSH_KEY}" | tr -d '\r' | ssh-add - > /dev/null
        - echo "${SSH_KEY_EIRENE_DEPLOY}" | tr -d '\r' | ssh-add - > /dev/null
        # Create the SSH directory and give it the right permissions
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        # Use ssh-keyscan to scan the keys of your private servers.
        - ssh-keyscan ${REPO_DOMAIN} >> ~/.ssh/known_hosts
        - ssh-keyscan src.ipp.kfa-juelich.de >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        # Change origin push URL to get write access to EIRENE repository
        - git remote set-url --push origin git@src.ipp.kfa-juelich.de:eirene/eirene.git

update_fork_branches_ITER:
    <<: *update_fork_branches
    variables:
        SSH_KEY: ${SSH_KEY_ITER}
        REPO_DOMAIN: "git.iter.org"
        REPO_URL: 'ssh://git@git.iter.org/bnd/eirene.git'
    script:
        # Add ITER repository as additional remote
        - git remote add -t master -t develop iter $REPO_URL || git remote set-url iter $REPO_URL
        - git remote set-url --push iter no_push
        # Fetch available branches from ITER
        - git fetch iter
        # Checkout and push branches to EIRENE repository
        - git checkout forks/iter/master && git merge iter/master || git checkout -b forks/iter/master iter/master 
        - git push -u origin forks/iter/master:forks/iter/master
        - git checkout forks/iter/develop && git merge iter/develop || git checkout -b forks/iter/develop iter/develop
        - git push -u origin forks/iter/develop:forks/iter/develop

update_fork_branches_CEA:
    <<: *update_fork_branches
    variables:
        SSH_KEY: ${SSH_KEY_CEA}
        REPO_DOMAIN: "subversion.assembla.com"
    script:
        # Adjust ssh_config to pass required environment variables
        - printf "Host cea-svn\n  HostName subversion.assembla.com\n  SendEnv REPO_NAME\n" >> ~/.ssh/config
        # Get local copy of CEA SVN repository
        - REPO_NAME=e-styx git svn clone svn+ssh://svn@cea-svn --stdlayout eirene_cea && cd eirene_cea && git checkout -b eirene_up2date origin/eirene_up2date || cd eirene_cea && REPO_NAME=e-styx git svn fetch
        # Add CEA repository as additional remote
        - cd ..
        - git remote add -t master -t eirene_up2date cea eirene_cea || git remote set-url cea eirene_cea
        # Fetch available branches from CEA
        - git fetch cea
        # Checkout and push branches to EIRENE repository
        - git checkout forks/cea/master && git merge cea/master || git checkout -b forks/cea/master cea/master 
        - git push -u origin forks/cea/master:forks/cea/master
        - git checkout forks/cea/eirene_up2date && git merge cea/eirene_up2date || git checkout -b forks/cea/eirene_up2date cea/eirene_up2date
        - git push -u origin forks/cea/eirene_up2date:forks/cea/eirene_up2date

update_fork_branches_JET:
    <<: *update_fork_branches
    variables:
        SSH_KEY: ${SSH_KEY_JET}
        REPO_DOMAIN: "git.ccfe.ac.uk"
        REPO_URL: 'git@git.ccfe.ac.uk:jintrac/EIRENE.git'
        REPO_NEW_URL: 'git@git.ccfe.ac.uk:jintrac/EIRENE_JUEL.git'
    script:
        # Add JET repositories as additional remotes
        - git remote add -t master -t develop jet $REPO_URL || git remote set-url jet $REPO_URL
        - git remote add -t JET_master -t v170517_NewJuel jet_new $REPO_NEW_URL || git remote set-url jet_new $REPO_NEW_URL
        - git remote set-url --push jet no_push
        - git remote set-url --push jet_new no_push
        # Fetch available branches from JET
        - git fetch jet
        - git fetch jet_new
        # Checkout and push branches to EIRENE repository
        - git checkout forks/jet/master && git merge jet/master || git checkout -b forks/jet/master jet/master 
        - git push -u origin forks/jet/master:forks/jet/master
        - git checkout forks/jet/develop && git merge jet/develop || git checkout -b forks/jet/develop jet/develop
        - git push -u origin forks/jet/develop:forks/jet/develop
        - git checkout forks/jet_new/JET_master && git merge jet_new/JET_master || git checkout -b forks/jet_new/JET_master jet_new/JET_master
        - git push -u origin forks/jet_new/JET_master:forks/jet_new/JET_master
        - git checkout forks/jet_new/v170517_NewJuel && git merge jet_new/v170517_NewJuel || git checkout -b forks/jet_new/v170517_NewJuel jet_new/v170517_NewJuel
        - git push -u origin forks/jet_new/v170517_NewJuel:forks/jet_new/v170517_NewJuel

