cdr  sept.2015:  NLSCL scaling option for rpartc (weights of census scores),
cdr              but not for census flux FLUX(NSTRAI) ???  to be done ??
cdr              added census fluxes resolved wrt. species and stratum
cdr              currently only for diagnostic printout, but should be used
cdr              also for stratifying re-sampling to preserve species specific
cdr              fluxes exactly
cdr  aug. 2016:  NLSCL corrections are also not on partw, i.e. not
cdr              accounted for during bootstrapping (re-sampling) from census
cdr  jul. 2020:  statement 300 continue moved up a bit.
cdr              This ensures that fort.15 (census array) is written
cdr              even in case of zero flux to census (empty censius then). To
cdr              facilitate continuation in time-dep runs even
cdr              if "zeroth time step" (census initialization) was too large.

CDR  APRIL 2006: IPHOT ADDED TO LOOP: DO 140

C
      SUBROUTINE EIRENE_MOD_TMSTEP
C
C  THIS SUBROUTINE IS CALLED AFTER EACH TIME CYCLE. IT ALLOWS TO
C  MODIFY SOME PLASMA BACKGROUND AND PRIMARY SOURCE DATA (I.E., STRATA
C  ISTRA=1,NSTRAI-1) ACCORDING TO INPUT SPECIFICATIONS IN BLOCK 13.
C
C  IT THEN DEFINES THE ADDITIONAL "CENSUS-STRATUM" ISTRA=NSTRAI, I.E., THE SOURCE DUE TO
C  THE INITIAL CONDITION AT THE BEGINNING OF THE NEXT TIMESTEP.
C  FLUX(NSTRAI)    : ATOMIC FLUX
C  RPARTW(1:IPNRL) : CUMULATIVE DISTRIBUTION FOR SAMPLING INDEX I ON CENSUS
C                    NOT NORMALIZED, AND WITHOUT NPRT FLUX FACTORS
C
      USE EIRMOD_PRECISION, ONLY: DP
      USE EIRMOD_PARMMOD, ONLY: MPARTT, NATM, NION, NMOL, NPHOT, NPARTT,
     >                          NSTRA
      USE EIRMOD_COMUSR, ONLY: ISPEZI, ITIMV, NATMI, NIONI, NMOLI,
     >                         NPHOTI, NFILEJ, NPRT, NSPA, NSPAM, NSPH,
     >                         NTIME, TEXTS
      USE EIRMOD_CCONA, ONLY: EPS10, EPS60
      USE EIRMOD_CLOGAU, ONLY: NLMOVIE, NLPLAS
      USE EIRMOD_CPLOT, ONLY: PLTSRC
      USE EIRMOD_CTRCEI, ONLY: TRCPLT, TRCGRD, TRCCEN
      USE EIRMOD_COMPRT, ONLY: IATM, IION, IMOL, IPHOT, ISPZ, ISTRA,
     >                         IPSTT, ITYP, IUNOUT, NPANU, RPSTT, WEIGHT
      USE EIRMOD_COMNNL, ONLY: DTIMV, IPART, IPARTC, IPRNL, IPRNLI,
     >                         NPTST, RPART, RPARTC, RPARTW, TIME0
      USE EIRMOD_COMSOU, ONLY: FLUX, NLSRON, NMINPTS, NPTS, NSTRAI,
     >                         NSRFSI, SORWGT
      USE EIRMOD_COUTAU, ONLY: FASCL, FISCL, FMSCL, FLXFAC, FPHSCL, XMCP

      IMPLICIT NONE

      REAL(DP) :: SGMTOT(NSTRA),FLX(NSTRA),
     .            ADDA(0:NATM,0:NSTRA),ADDM(0:NMOL,0:NSTRA),
     .            ADDI(0:NION,0:NSTRA),ADDPH(0:NPHOT,0:NSTRA)
      REAL(DP) :: FLXQ, FCT, SGMREL, SGMTQN, ADDS, ADD, ADDP, SGMTQ1,
     .            SUMM, WEIGHT0
      INTEGER :: ISTRAO, NPANUO, ISTRAI, JATM, JMOL, JION, JPHOT, I
C
C  STEP 1
C
C  REDUCE REDUNDANT PRINTOUT IN NEXT TIME STEP
      TRCPLT=.FALSE.
      TRCGRD=.FALSE.
      PLTSRC(NSTRAI)=.FALSE.
      DO 120 ISTRAI=1,NSTRAI-1
        PLTSRC(NSTRAI)=PLTSRC(NSTRAI).OR.PLTSRC(ISTRAI)
  120 CONTINUE
C
C  SPEED UP GEOMETRY. USE INFO FROM PREVIOUS TIME-STEP
C  tbd.    
C
C  STEP 2
C
C  MODIFY BACKGROUND DATA AS COMPARED TO PREVIOUS ITERATION
C  FOR TIME DEP. MODE
C
C  STARTING TIME FOR NEXT TIMESTEP
C
      TIME0=TIME0+DTIMV
      NLSRON(NSTRAI) =.TRUE.
C
C  CALL USER-SUPPLIED ROUTINE TMSUSR
C  E.G.: FILL COMMON BRAEIR WITH NEW PLASMA, IF NMODE.NE.0
C  BE CAREFUL: NO INDEX MAPPING IS DONE, UNLESS
C  NCUTL.NE.NCUTB
      CALL EIRENE_TMSUSR(TIME0)
      NLPLAS=.TRUE.
C
C  STEP 3
C
C  SET SOURCE DUE TO INITIAL CONDITION FOR NEXT TIME CYCLE
C  THERE HAVE BEEN IPRNL SCORES ON THE CENSUS IN THIS PRESENT RUN.
C
C  SOURCE STRENGTH OF INITIAL DISTRIBUTION IN NEW TIME CYCLE

C  A: set NPTS for time stratum NSTRAI IN NEXT TIME STEP
      IPRNL=IPRNLI
      IPRNLI=0
      IF (NPTST.EQ.0) THEN
        NPTS(NSTRAI)=IPRNL
        IF (NLMOVIE) THEN
          WRITE (IUNOUT,*) 'NLMOVIE TURNED OFF, BECAUSE NPTST.EQ.0'
          NLMOVIE=.FALSE.
        ENDIF
      ELSEIF (NPTST.GT.0) THEN
        NPTS(NSTRAI)=NPTST
        IF (NLMOVIE) THEN
          WRITE (IUNOUT,*) 'NLMOVIE TURNED OFF, BECAUSE NPTST.GT.0'
          NLMOVIE=.FALSE.
        ENDIF
      ELSEIF (NPTST.LT.0.OR.NLMOVIE) THEN
C  ONE BY ONE RELAUNCH FROM OLD CENSUS
C  OLD CENSUS CONTAINS IPRNL ENTRIES.
        NPTS(NSTRAI)=IPRNL
        NMINPTS(NSTRAI)=IPRNL  !ENFORCE: FULL RE-LOCATION OF ALL PARTICLES FROM OLD CENSUS
      ENDIF

      FLUX(NSTRAI)=0.
      RPARTW(0)=0.0
      DO 130 ISTRAI=1,NSTRAI
        SGMTOT(ISTRAI)=0.0
        FLX(ISTRAI)=0.0
  130 CONTINUE
      SGMREL=0.0
C
cdr  empty census?
      IF (IPRNL.EQ.0) GOTO 300

      RPSTT(1:NPARTT)=RPART(1:NPARTT,1)
      IPSTT(1:MPARTT)=IPART(1:MPARTT,1)

      NPANUO=NPANU
      ISTRAO=ISTRA

      ADDS=0.

      ADDPH=0.
      ADDA =0.
      ADDM =0.
      ADDI =0.
C
C  SET "ATOMIC" FLUXES ONTO CENSUS ARRAY
C  IF NLSCL, APPLY PART. BALANCE CORRECTION SCALING, FOR THE TOTAL CENSUS FLUX

C  THIS IS ALREADY DONE ON "TIME SURFACE" TALLY ELSEWHERE, AS IT IS ON ANY OTHER SURFACE
C  BUT IS DONE HERE ADDITIONALLY ON THE PARTICULAR "CENSUS ARRAYS" RPARTW (RESAMPLING), RPART(9,..),
C  AND THE SPECIES TYPE-RESOLVED FLUXES ADDPH, ADDA, ADDM, ADDI

      DO 140  I=1,IPRNL
        RPSTT(1:NPARTT)=RPART(1:NPARTT,I)
        IPSTT(1:MPARTT)=IPART(1:MPARTT,I)

cdr     IPAN=IPART(1,I)  ! particle number of score I on census = NPANU
cdr     ISTR=IPART(8,I)  ! stratum  number of score I on census = ISTRA
cdr     ISPZ=IPART(9,I)  ! species index of score I on census   = ISPZ

        ITYP=ISPEZI(ISPZ,-1) !  ispz is now known (pointer to ipstt(9))
        WEIGHT0=WEIGHT
        IF (ITYP.EQ.0) THEN
          IPHOT=ISPEZI(ISPZ,0)
          WEIGHT=WEIGHT0*FPHSCL(ISTRA)
          ADDP=WEIGHT0*FLXFAC(ISTRA)
          ADD=ADDP*NPRT(IPHOT)
          ADDPH(IPHOT,ISTRA)=ADDPH(IPHOT,ISTRA)+ADDP
        ELSEIF (ITYP.EQ.1) THEN
          IATM=ISPEZI(ISPZ,1)
          WEIGHT=WEIGHT0*FASCL(ISTRA)
          ADDP=WEIGHT0*FLXFAC(ISTRA)
          ADD=ADDP*NPRT(NSPH+IATM)
          ADDA(IATM,ISTRA)=ADDA(IATM,ISTRA)+ADDP
        ELSEIF (ITYP.EQ.2) THEN
          IMOL=ISPEZI(ISPZ,2)
          WEIGHT=WEIGHT0*FMSCL(ISTRA)
          ADDP=WEIGHT0*FLXFAC(ISTRA)
          ADD=ADDP*NPRT(NSPA+IMOL)
          ADDM(IMOL,ISTRA)=ADDM(IMOL,ISTRA)+ADDP
        ELSEIF (ITYP.EQ.3) THEN
          IION=ISPEZI(ISPZ,3)
          WEIGHT=WEIGHT0*FISCL(ISTRA)
          ADDP=WEIGHT0*FLXFAC(ISTRA)
          ADD=ADDP*NPRT(NSPAM+IION)
          ADDI(IION,ISTRA)=ADDI(IION,ISTRA)+ADDP
        ENDIF

C  SET DISCRETE CUMULATIVE CENSUS FLUX DISTRIBUTION FOR RESAMPLING OF SCORE-INDEX "I"
C  DO NOT INCLUDE NPRT FACTORS, BECAUSE THIS WEIGHT-FACTOŔ WILL ALREADY BE CARRIED BY RELAUNCHED PARTICLE
C  ALSO THE BALANCE CORRECTION FACTORS FATM,... ARE NOT INCLUDED HERE
C       RPARTW(I)=RPARTW(I-1)+ADDP  ! same as next line

        RPARTW(I)=RPARTW(I-1)+WEIGHT0*FLXFAC(ISTRA)
C
C  ACCUMULATE CONTRIBUTION FROM TEST FLIGHT NO. NPANUO
C  FOR ESTIMATION OF STATISTICAL VARIANCE OF CENSUS FLUX
C  NPANUO MAY HAVE SCORED AT CENSUS SEVERAL TIMES
        IF (NPANU.EQ.NPANUO) THEN
          ADDS=ADDS+ADD
        ENDIF

C  NPANU IS A NEW PARTICLE ?
        IF (NPANU.NE.NPANUO) THEN
C  ADD PREVIOUS CENSUS SCORE NPANUO TO FLUX, SGMTOT,...
C  FLUX IS TOTAL "ATOMIC FLUX" ON CENSUS
          FLUX(NSTRAI)=FLUX(NSTRAI)+ADDS
          FLX(ISTRAO)=FLX(ISTRAO)+ADDS
          SGMTOT(ISTRAO)=SGMTOT(ISTRAO)+ADDS*ADDS
          NPANUO=NPANU
          ISTRAO=ISTRA
C   PUT WEIGHT OF CURRENT CENSUS SCORE NPANU ONTO ADDS
          ADDS=ADD
        ENDIF

C   WEIGHT may have been altered. So: redefine entire this component of state vector.
        RPART(1:NPARTT,I)=RPSTT(1:NPARTT)
  140 CONTINUE

C  CONTRIBUTION FROM LAST CENSUS SCORE NO. IPRNL

      FLUX(NSTRAI)=FLUX(NSTRAI)+ADDS
      FLX(ISTRAO)=FLX(ISTRAO)+ADDS
      SGMTOT(ISTRAO)=SGMTOT(ISTRAO)+ADDS*ADDS
C
C  SUM OVER SPECIES, CENSUS FLUXES
      DO ISTRAI=1,NSTRAI
        ADDA(0,ISTRAI) = SUM(ADDA(1:NATMI,ISTRAI))
        ADDM(0,ISTRAI) = SUM(ADDM(1:NMOLI,ISTRAI))
        ADDI(0,ISTRAI) = SUM(ADDI(1:NIONI,ISTRAI))
        ADDPH(0,ISTRAI)= SUM(ADDPH(1:NPHOTI,ISTRAI))
      ENDDO
C  SUM OVER STRATA
      DO JATM=1,NATMI
        ADDA(JATM,0) =SUM(ADDA(JATM,1:NSTRAI))
      ENDDO
      DO JMOL=1,NMOLI
        ADDM(JMOL,0) =SUM(ADDM(JMOL,1:NSTRAI))
      ENDDO
      DO JION=1,NIONI
        ADDI(JION,0) =SUM(ADDI(JION,1:NSTRAI))
      ENDDO
      DO JPHOT=1,NPHOTI
        ADDPH(JPHOT,0)=SUM(ADDPH(JPHOT,1:NSTRAI))
      ENDDO
C  SUM OVER SPECIES AND STRATA
      ADDA(0,0) =SUM(ADDA(0,1:NSTRAI))
      ADDM(0,0) =SUM(ADDM(0,1:NSTRAI))
      ADDI(0,0) =SUM(ADDI(0,1:NSTRAI))
      ADDPH(0,0)=SUM(ADDPH(0,1:NSTRAI))
C
C  VARIANCE OF CENSUS FLUX: ACCOUNT FOR SOURCE STRATIFICATION
C
      SGMTQ1=0.
      SGMREL=0.
      DO 150 ISTRAI=1,NSTRAI
        IF (XMCP(ISTRAI).GT.1.) THEN
          FCT=XMCP(ISTRAI)/(XMCP(ISTRAI)-1.)
          FLXQ=FLX(ISTRAI)*FLX(ISTRAI)
          SGMTQ1=SGMTQ1+(SGMTOT(ISTRAI)-FLXQ/XMCP(ISTRAI))*FCT
        ENDIF
  150 CONTINUE
      IF (SGMTQ1.GT.0.D0) THEN
        SGMTQN=SQRT(SGMTQ1)
        SGMREL=SGMTQN/(FLUX(NSTRAI)+EPS60)
        SGMREL=MAX(0._DP,SGMREL-EPS10)*100.
      ENDIF
C
      IF (FLUX(NSTRAI).GT.0) THEN
        NSRFSI(NSTRAI)=1
        SORWGT(1,NSTRAI)=1.D0
      ENDIF

C  SET ARRAYS OF CENSUS PARTICLE COORDINATES
C  FOR RE-SAMPLING (SUBR. LOCATE) IN NEXT TIMESTEP.
C  WEIGHT OF RE-SAMPLED PARTICLE = 1.0, SINCE ORIGINAL CENSUS PARTICLE
C  WEIGHT IS ALREADY ACCOUNTED FOR IN RE-SAMPLING DISTRIBUTION RPARTW
      RPARTC(1:NPARTT,1:IPRNL)=RPART(1:NPARTT,1:IPRNL)
      IPARTC(1:MPARTT,1:IPRNL)=IPART(1:MPARTT,1:IPRNL)
C
C Such loops can be optimised by changing IPSTT to a pointer on IPARTC,
C similar situation in collect_census.f
      DO I=1,IPRNL
        IPSTT(1:MPARTT)=IPARTC(1:MPARTT,I)
        ISTRA=NSTRAI
        IPARTC(1:MPARTT,I)=IPSTT(1:MPARTT)
      ENDDO
C
C  CALL WRSNAP TO WRITE SNAPSHOT POPULATION
C  FOR NEXT RUN ON FT 15
C
  300 CONTINUE
      IF ((NFILEJ.EQ.1.OR.NFILEJ.EQ.3).AND.ITIMV.GE.NTIME) THEN
cdr  Even in case iprnl=0 (no flux on census):
cdr  Open and write fort 15, at least the first line.
        CALL EIRENE_WRSNAP(NSTRAI)
        WRITE (iunout,*) 'CENSUS ARRAY, FLUX AND TOTAL TIMESTEP STORED'
      ENDIF
C
cdr   300 CONTINUE  ! moved up to ensure fort.15 is written.

      CALL EIRENE_LEER(2)
      WRITE (iunout,*) 'TIME CYCLE COMPLETED, NEXT TIME CYCLE PREPARED'
      WRITE (iunout,*) 'NEXT TIME CYCLE RUNS FROM TIM1 TO TIM2:'
      CALL EIRENE_MASR2('TIM1, TIM2      ',TIME0,TIME0+DTIMV)
      CALL EIRENE_MASJ1('IPRNL   ',IPRNL)
      WRITE (IUNOUT,*) '"ATOMIC" FLUX AT CENSUS (AMP):'
      CALL EIRENE_MASR1('FLUX    ',FLUX(NSTRAI))
      CALL EIRENE_MASR1('+-%     ',SGMREL)

      CALL EIRENE_LEER(2)
C
      IF (TRCCEN) THEN
        CALL EIRENE_MASBOX
     .          ('DETAILED CENSUS FLUXES, PER SPECIES, STRATUM')

        DO 950 ISTRAI=1,NSTRAI
          CALL EIRENE_LEER(1)
          WRITE (IUNOUT,*) 'STRATUM NO. ISTRA=', ISTRAI
          CALL EIRENE_LEER(1)
          SUMM=ADDA(0,ISTRAI)+ADDM(0,ISTRAI)+ADDI(0,ISTRAI)+
     .         ADDPH(0,ISTRAI)
          IF (SUMM.EQ.0.0) THEN
            WRITE (IUNOUT,*) 'NO FLUXES FROM THIS STRATUM ON CENSUS'
            GOTO 950
          ENDIF

C   PRINT ADDA(IATM) FOR ISTRAI
          IF  (ADDA(0,ISTRAI).GT.0.0) THEN
            WRITE (IUNOUT,*) 'ATOM FLUX AT CENSUS (AMP):'
            DO JATM = 1, NATMI
              WRITE (IUNOUT,'(A10,ES12.4)')
     .               TEXTS(NSPH+JATM), ADDA(JATM,ISTRAI)
            END DO
            WRITE (IUNOUT,'(A10,ES12.4)')
     .               'TOTAL     ',ADDA(0,ISTRAI)
            CALL EIRENE_LEER(1)
          ENDIF

C   PRINT ADDM(IMOL) FOR ISTRAI
          IF  (ADDM(0,ISTRAI).GT.0.0) THEN
            WRITE (IUNOUT,*) 'MOLECULE FLUX AT CENSUS (AMP):'
            DO JMOL = 1, NMOLI
              WRITE (IUNOUT,'(A10,ES12.4)')
     .               TEXTS(NSPA+JMOL), ADDM(JMOL,ISTRAI)
            END DO
            WRITE (IUNOUT,'(A10,ES12.4)')
     .               'TOTAL     ',ADDM(0,ISTRAI)
            CALL EIRENE_LEER(1)
          ENDIF

C   PRINT ADDI(IION) FOR ISTRAI
          IF  (ADDI(0,ISTRAI).GT.0.0) THEN
            WRITE (IUNOUT,*) 'TEST ION FLUX AT CENSUS (AMP):'
            DO JION = 1, NIONI
              WRITE (IUNOUT,'(A10,ES12.4)')
     .               TEXTS(NSPAM+JION), ADDI(JION,ISTRAI)
            END DO
            WRITE (IUNOUT,'(A10,ES12.4)')
     .               'TOTAL     ',ADDI(0,ISTRAI)
            CALL EIRENE_LEER(1)
          ENDIF

C   PRINT ADDPH(IPHOT) FOR ISTRAI
          IF  (ADDPH(0,ISTRAI).GT.0.0) THEN
            WRITE (IUNOUT,*) 'PHOTON FLUX AT CENSUS (AMP):'
            DO JPHOT = 1, NPHOTI
              WRITE (IUNOUT,'(A10,ES12.4)')
     .               TEXTS(JPHOT), ADDPH(JPHOT,ISTRAI)
            END DO
            WRITE (IUNOUT,'(A10,ES12.4)')
     .             'TOTAL     ',ADDPH(0,ISTRAI)
            CALL EIRENE_LEER(1)
          ENDIF

  950   CONTINUE
        CALL EIRENE_LEER(2)

        WRITE (IUNOUT,*) 'SUM OVER STRATA'

        SUMM=ADDA(0,0)+ADDM(0,0)+ADDI(0,0)+ADDPH(0,0)
        IF (SUMM.EQ.0.0) THEN
          WRITE (IUNOUT,*) 'NO FLUXES ON CENSUS '
          GOTO 960
        ENDIF

C   PRINT ADDA(IATM) FOR ISTRAI=0
        IF  (ADDA(0,0).GT.0.0) THEN
          WRITE (IUNOUT,*) 'ATOM FLUX AT CENSUS (AMP):'
          DO JATM = 1, NATMI
            WRITE (IUNOUT,'(A10,ES12.4)')
     .             TEXTS(NSPH+JATM), ADDA(JATM,0)
          END DO
          WRITE (IUNOUT,'(A10,ES12.4)')
     .             'TOTAL     ',ADDA(0,0)
          CALL EIRENE_LEER(1)
        ENDIF

C   PRINT ADDM(IMOL) FOR ISTRAI=0
        IF  (ADDM(0,0).GT.0.0) THEN
          WRITE (IUNOUT,*) 'MOLECULE FLUX AT CENSUS (AMP):'
          DO JMOL = 1, NMOLI
            WRITE (IUNOUT,'(A10,ES12.4)')
     .             TEXTS(NSPA+JMOL), ADDM(JMOL,0)
          END DO
          WRITE (IUNOUT,'(A10,ES12.4)')
     .             'TOTAL     ',ADDM(0,0)
          CALL EIRENE_LEER(1)
        ENDIF

C   PRINT ADDI(IION) FOR ISTRAI=0
        IF  (ADDI(0,0).GT.0.0) THEN
          WRITE (IUNOUT,*) 'TEST ION FLUX AT CENSUS (AMP):'
          DO JION = 1, NIONI
            WRITE (IUNOUT,'(A10,ES12.4)')
     .             TEXTS(NSPAM+JION), ADDI(JION,0)
          END DO
          WRITE (IUNOUT,'(A10,ES12.4)')
     .             'TOTAL     ',ADDI(0,0)
          CALL EIRENE_LEER(1)
        ENDIF

C   PRINT ADDPH(IPHOT) FOR ISTRAI=0
        IF  (ADDPH(0,0).GT.0.0) THEN
          WRITE (IUNOUT,*) 'PHOTON FLUX AT CENSUS (AMP):'
          DO JPHOT = 1, NPHOTI
            WRITE (IUNOUT,'(A10,ES12.4)')
     .             TEXTS(JPHOT), ADDPH(JPHOT,0)
          END DO
          WRITE (IUNOUT,'(A10,ES12.4)')
     .             'TOTAL     ',ADDPH(0,0)
          CALL EIRENE_LEER(1)
        ENDIF

  960   CONTINUE

      ENDIF  !TRCCEN

      WRITE (IUNOUT,*) '...............................................'
C
      RETURN
      END SUBROUTINE EIRENE_MOD_TMSTEP
