      MODULE EIRMOD_BRASCL
 
C  RESCALING ARRAYS FOR NEUTRAL SOURCE TERMS IN SHORT LOOP
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
 
      IMPLICIT NONE
 
      PRIVATE
 
      PUBLIC :: EIRENE_ALLOC_BRASCL, EIRENE_DEALLOC_BRASCL,
     P          EIRENE_INIT_BRASCL1, EIRENE_INIT_BRASCL2,
     P          EIRENE_ALLOC_RATE_ARRAY, RATE_STORE,
     P          RATES_ARRAY
 
      TYPE RATE_STORE
        REAL(DP), POINTER ::
     R      SPLODA(:,:,:), SEIODA(:,:), SEEODA(:,:), SMOODA(:,:),
     R      SPLODI(:,:,:), SEIODI(:,:), SEEODI(:,:), SMOODI(:,:),
     R      SPLODM(:,:,:), SEIODM(:,:), SEEODM(:,:), SMOODM(:,:)
      END TYPE RATE_STORE

      TYPE RATES_ARRAY
        TYPE(RATE_STORE), POINTER :: RTA
      END TYPE RATES_ARRAY

      TYPE(RATES_ARRAY), PUBLIC, ALLOCATABLE, SAVE :: RTS(:)
      INTEGER, PUBLIC, ALLOCATABLE, SAVE :: ITS(:), ITS_COUNT(:)


      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R SPLNWA(:,:,:), SEINWA(:,:), SEENWA(:,:), SMONWA(:,:),
     R SPLNWI(:,:,:), SEINWI(:,:), SEENWI(:,:), SMONWI(:,:),
     R SPLNWM(:,:,:), SEINWM(:,:), SEENWM(:,:), SMONWM(:,:)
 
 
      CONTAINS
 
 
      SUBROUTINE EIRENE_ALLOC_BRASCL

      INTEGER :: IS
 
      IF (ALLOCATED(SPLNWA)) RETURN
 
      ALLOCATE (RTS(NSTRA))
      ALLOCATE (ITS(NSTRA))
      ALLOCATE (ITS_COUNT(NSTRA))

      ALLOCATE (SPLNWA(NRAD,NATM,NPLS))
      ALLOCATE (SEINWA(NRAD,NPLS))
      ALLOCATE (SEENWA(NRAD,NATM))
      ALLOCATE (SMONWA(NRAD,NATM))
      ALLOCATE (SPLNWI(NRAD,NION,NPLS))
      ALLOCATE (SEINWI(NRAD,NION))
      ALLOCATE (SEENWI(NRAD,NION))
      ALLOCATE (SMONWI(NRAD,NION))
      ALLOCATE (SPLNWM(NRAD,NMOL,NPLS))
      ALLOCATE (SEINWM(NRAD,NMOL))
      ALLOCATE (SEENWM(NRAD,NMOL))
      ALLOCATE (SMONWM(NRAD,NMOL))
 
      WRITE (55,'(A,T25,I15)')
     .      ' BRASCL ',NRAD*(NATM*(NPLS+2)+NION*(NPLS+3)+
     .                 NMOL*(NPLS+3)+NPLS)*8
 
      DO IS=1, NSTRA
        NULLIFY(RTS(IS)%RTA) 
      END DO

      ITS = 1
      ITS_COUNT = 0

      CALL EIRENE_INIT_BRASCL2
 
      RETURN
      END SUBROUTINE EIRENE_ALLOC_BRASCL
 
 
      SUBROUTINE EIRENE_ALLOC_RATE_ARRAY(IS)
      
      INTEGER, INTENT(IN) :: IS

      IF (ASSOCIATED(RTS(IS)%RTA)) RETURN

      ALLOCATE (RTS(IS)%RTA)
 
      ALLOCATE (RTS(IS)%RTA%SPLODA(NRAD,NATM,NPLS))
      ALLOCATE (RTS(IS)%RTA%SEIODA(NRAD,NPLS))
      ALLOCATE (RTS(IS)%RTA%SEEODA(NRAD,NATM))
      ALLOCATE (RTS(IS)%RTA%SMOODA(NRAD,NATM))
      ALLOCATE (RTS(IS)%RTA%SPLODI(NRAD,NION,NPLS))
      ALLOCATE (RTS(IS)%RTA%SEIODI(NRAD,NION))
      ALLOCATE (RTS(IS)%RTA%SEEODI(NRAD,NION))
      ALLOCATE (RTS(IS)%RTA%SMOODI(NRAD,NION))
      ALLOCATE (RTS(IS)%RTA%SPLODM(NRAD,NMOL,NPLS))
      ALLOCATE (RTS(IS)%RTA%SEIODM(NRAD,NMOL))
      ALLOCATE (RTS(IS)%RTA%SEEODM(NRAD,NMOL))
      ALLOCATE (RTS(IS)%RTA%SMOODM(NRAD,NMOL))
 
      WRITE (55,'(A,T25,I15)')
     .      ' BRASCL ',NRAD*(NATM*(NPLS+2)+NION*(NPLS+3)+
     .                 NMOL*(NPLS+3)+NPLS)*8
 
      CALL EIRENE_INIT_BRASCL1(IS)
 
      RETURN
      END SUBROUTINE EIRENE_ALLOC_RATE_ARRAY
 
 
      SUBROUTINE EIRENE_DEALLOC_BRASCL

      INTEGER :: IS
 
      IF (.NOT.ALLOCATED(SPLNWA)) RETURN
 
      DO IS = 1, NSTRA
        IF (.NOT.ASSOCIATED(RTS(IS)%RTA)) CYCLE
        DEALLOCATE (RTS(IS)%RTA%SPLODA)
        DEALLOCATE (RTS(IS)%RTA%SEIODA)
        DEALLOCATE (RTS(IS)%RTA%SEEODA)
        DEALLOCATE (RTS(IS)%RTA%SMOODA)
        DEALLOCATE (RTS(IS)%RTA%SPLODI)
        DEALLOCATE (RTS(IS)%RTA%SEIODI)
        DEALLOCATE (RTS(IS)%RTA%SEEODI)
        DEALLOCATE (RTS(IS)%RTA%SMOODI)
        DEALLOCATE (RTS(IS)%RTA%SPLODM)
        DEALLOCATE (RTS(IS)%RTA%SEIODM)
        DEALLOCATE (RTS(IS)%RTA%SEEODM)
        DEALLOCATE (RTS(IS)%RTA%SMOODM)
      END DO
      
      DEALLOCATE (RTS)
      DEALLOCATE (ITS)
      DEALLOCATE (ITS_COUNT)

      DEALLOCATE (SPLNWA)
      DEALLOCATE (SEINWA)
      DEALLOCATE (SEENWA)
      DEALLOCATE (SMONWA)
      DEALLOCATE (SPLNWI)
      DEALLOCATE (SEINWI)
      DEALLOCATE (SEENWI)
      DEALLOCATE (SMONWI)
      DEALLOCATE (SPLNWM)
      DEALLOCATE (SEINWM)
      DEALLOCATE (SEENWM)
      DEALLOCATE (SMONWM)
 
      RETURN
      END SUBROUTINE EIRENE_DEALLOC_BRASCL
 
 
      SUBROUTINE EIRENE_INIT_BRASCL1(IS)
      
      INTEGER, INTENT(IN) :: IS
 
      RTS(IS)%RTA%SPLODA = 0.D0
      RTS(IS)%RTA%SEIODA = 0.D0
      RTS(IS)%RTA%SEEODA = 0.D0
      RTS(IS)%RTA%SMOODA = 0.D0
      RTS(IS)%RTA%SPLODI = 0.D0
      RTS(IS)%RTA%SEIODI = 0.D0
      RTS(IS)%RTA%SEEODI = 0.D0
      RTS(IS)%RTA%SMOODI = 0.D0
      RTS(IS)%RTA%SPLODM = 0.D0
      RTS(IS)%RTA%SEIODM = 0.D0
      RTS(IS)%RTA%SEEODM = 0.D0
      RTS(IS)%RTA%SMOODM = 0.D0
 
      RETURN
      END SUBROUTINE EIRENE_INIT_BRASCL1
 
 
      SUBROUTINE EIRENE_INIT_BRASCL2
 
      SPLNWA = 0.D0
      SEINWA = 0.D0
      SEENWA = 0.D0
      SMONWA = 0.D0
      SPLNWI = 0.D0
      SEINWI = 0.D0
      SEENWI = 0.D0
      SMONWI = 0.D0
      SPLNWM = 0.D0
      SEINWM = 0.D0
      SEENWM = 0.D0
      SMONWM = 0.D0
 
      RETURN
      END SUBROUTINE EIRENE_INIT_BRASCL2
 
      END MODULE EIRMOD_BRASCL
