!pb  31.10.06:  definition of census arrays RPART, RPARTC, IPART, IPARTC changed
!               RPART (NPRNL,NPARTT) --> RPART (NPARTT,NPRNL)
!               IPART (MPRNL,NPARTT) --> IPART (MPARTT,NPRNL)
!               RPARTC(NPRNL,NPARTT) --> RPARTC(NPARTT,NPRNL)
!               IPARTC(MPRNL,NPARTT) --> IPARTC(MPARTT,NPRNL)

      MODULE EIRMOD_COMNNL

      USE EIRMOD_PRECISION, ONLY: DP
      USE EIRMOD_PARMMOD, ONLY: IUNMEM, MPARTT, NPARTT, NPRNL, NSTRA


      IMPLICIT NONE

      PRIVATE

      PUBLIC :: EIRENE_ALLOC_COMNNL, EIRENE_DEALLOC_COMNNL,
     P          EIRENE_INIT_COMNNL

      REAL(DP), PUBLIC, SAVE ::
     R  DTIMV,  DTIMVI, DTIMVN, TIME0

      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R  RPART(:,:), RPARTC(:,:), RPARTW(:)

      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I  IPART(:,:), IPARTC(:,:),
     I  NPRNLS(:)

      INTEGER, PUBLIC, SAVE ::
     I  NPRNLI, IPRNLI, IPRNLS, IPRNL,
     I  NPTST,  NTMSTP, ITMSTP


      CONTAINS


      SUBROUTINE EIRENE_ALLOC_COMNNL

      IF (ALLOCATED(RPART)) RETURN

      ALLOCATE (RPART(NPARTT,NPRNL))
      ALLOCATE (RPARTC(NPARTT,NPRNL))
      ALLOCATE (RPARTW(0:NPRNL))

      ALLOCATE (IPART(MPARTT,NPRNL))
      ALLOCATE (IPARTC(MPARTT,NPRNL))
      ALLOCATE (NPRNLS(NSTRA))

      WRITE (IUNMEM,'(A,T25,I15)')
     .      ' COMNNL ',(2*NPRNL*NPARTT+NPRNL+1)*8 +
     .                 (2*NPRNL*MPARTT+NSTRA)*4

      CALL EIRENE_INIT_COMNNL

      RETURN
      END SUBROUTINE EIRENE_ALLOC_COMNNL


      SUBROUTINE EIRENE_DEALLOC_COMNNL

      IF (.NOT.ALLOCATED(RPART)) RETURN

      DEALLOCATE (RPART)
      DEALLOCATE (RPARTC)
      DEALLOCATE (RPARTW)

      DEALLOCATE (IPART)
      DEALLOCATE (IPARTC)
      DEALLOCATE (NPRNLS)

      RETURN
      END SUBROUTINE EIRENE_DEALLOC_COMNNL


      SUBROUTINE EIRENE_INIT_COMNNL

      RPART  = 0._DP
      RPARTC = 0._DP
      RPARTW = 0._DP

      IPART  = 0
      IPARTC = 0
      NPRNLS = 0

      NPRNLI = 0
      IPRNLI = 0
      IPRNLS = 0
      IPRNL  = 0
      NPTST  = 0
      NTMSTP = 0
      ITMSTP = 0

      RETURN
      END SUBROUTINE EIRENE_INIT_COMNNL

      END MODULE EIRMOD_COMNNL
