      SUBROUTINE EIRENE_ALLOC_COUPLE
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CCOUPL
      USE EIRMOD_COMUSR, ONLY : NMODE

      IF (NMODE .NE. 0) CALL EIRENE_ALLOC_CCOUPL(1)
      CALL EIRENE_ALLOC_CCOUPL(2)

      END SUBROUTINE EIRENE_ALLOC_COUPLE
