      MODULE EIRMOD_CCOUPL

      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD

      IMPLICIT NONE

      PRIVATE

      PUBLIC :: EIRENE_ALLOC_CCOUPL, EIRENE_DEALLOC_CCOUPL,
     P     EIRENE_INIT_CCOUPL, EIRENE_BROAD_CCOUPL

      INTEGER, PUBLIC, TARGET, ALLOCATABLE, SAVE ::
     I         ICCPL2(:)

      INTEGER, PUBLIC, POINTER, SAVE ::
     I NFLA

      INTEGER, PUBLIC, SAVE ::
     I MCOUPL2

      CONTAINS


      SUBROUTINE EIRENE_ALLOC_CCOUPL (ICAL)

      INTEGER, INTENT(IN) :: ICAL

      IF (ICAL == 1) THEN

        IF (ALLOCATED(ICCPL2)) RETURN

        MCOUPL2 = 1
        ALLOCATE (ICCPL2(MCOUPL2))

        WRITE (IUNMEM,'(A,T25,I15)')
     .        ' CCOUPL ',MCOUPL2*4

        NFLA       => ICCPL2(1)
      END IF

      CALL EIRENE_INIT_CCOUPL (ICAL)

      RETURN
      END SUBROUTINE EIRENE_ALLOC_CCOUPL


      SUBROUTINE EIRENE_DEALLOC_CCOUPL

      IF (.NOT.ALLOCATED(ICCPL2)) RETURN
      DEALLOCATE (ICCPL2)

      RETURN
      END SUBROUTINE EIRENE_DEALLOC_CCOUPL


      SUBROUTINE EIRENE_INIT_CCOUPL(ICAL)

      INTEGER, INTENT(IN) :: ICAL

      ICCPL2 = 0

      RETURN
      END SUBROUTINE EIRENE_INIT_CCOUPL


      SUBROUTINE EIRENE_BROAD_CCOUPL

      RETURN
      END SUBROUTINE EIRENE_BROAD_CCOUPL 


      END MODULE EIRMOD_CCOUPL
