C
C
      SUBROUTINE EIRENE_EXIT_OWN (ICC)
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: ICC
C  LEGAL ENDING OF GR PLOTTING SOFTWARE      
      CALL EIRENE_PLEND
      STOP 1
      END SUBROUTINE EIRENE_EXIT_OWN
