C
C
      SUBROUTINE EIRENE_EXIT_OWN (ICC)
      USE EIRMOD_CPES
      USE EIRMOD_COMPRT
      USE EIRMOD_MPI
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: ICC
#ifdef USE_MPI
      INTEGER :: IER
#endif
      LOGICAL :: LXOWN

      WRITE(IUNOUT,*) 'EIRENE EXIT_OWN ENTERED FROM PROCESSOR ', MY_PE
      LXOWN = .TRUE.
#ifdef USE_MPI
      CALL MPI_ALLGATHER (LXOWN, 1, MPI_LOGICAL,
     .                    LEXIT, 1, MPI_LOGICAL, MPI_COMM_WORLD, IER)
C  LEGAL ENDING OF GR PLOTTING SOFTWARE
      CALL EIRENE_PLEND
      CALL MPI_ABORT(MPI_COMM_WORLD, -1, IER)
      CALL MPI_FINALIZE(IER)
#else
      CALL EIRENE_PLEND
#endif
#if defined(G95) || ( defined(PGF90) && COMPILER_MAJOR_VERSION < 19 ) || ( defined(GFORTRAN) && COMPILER_MAJOR_VERSION < 5 && COMPILER_MINOR_VERSION < 6 )
      STOP 'EIRENE_EXIT'
#else
      ERROR STOP 'EIRENE_EXIT'
#endif
      END SUBROUTINE EIRENE_EXIT_OWN

      SUBROUTINE EIRENE_CHECK_EXIT
      USE EIRMOD_CPES
      USE EIRMOD_MPI
      IMPLICIT NONE
#ifdef USE_MPI
      INTEGER :: IER
      INTEGER IPRS
#endif
      LOGICAL :: LXOWN

      LXOWN = .FALSE.

C  LEGAL ENDING OF GR PLOTTING SOFTWARE
#ifdef USE_MPI
      CALL MPI_ALLGATHER (LXOWN, 1, MPI_LOGICAL,
     .                    LEXIT, 1, MPI_LOGICAL, MPI_COMM_WORLD, IER)
      DO IPRS = 0, NPRS-1
        IF (LEXIT(IPRS)) THEN
          WRITE(0,*) 'ERROR DETECTED FROM PROCESSOR ', IPRS
          WRITE(0,*) 'EXITING...'
          FLUSH(0)
          CALL EIRENE_PLEND
          CALL MPI_ABORT(MPI_COMM_WORLD, -1, IER)
          CALL MPI_FINALIZE(IER)
#if defined(G95) || ( defined(PGF90) && COMPILER_MAJOR_VERSION < 19 ) || ( defined(GFORTRAN) && COMPILER_MAJOR_VERSION < 5 && COMPILER_MINOR_VERSION < 6 )
          STOP 'EIRENE_EXIT'
#else
          ERROR STOP 'EIRENE_EXIT'
#endif
        END IF
      END DO
#endif
      RETURN
      END SUBROUTINE EIRENE_CHECK_EXIT
