      FUNCTION EIRENE_INDIRECT_ADDRESS(I1,I2,ND1) RESULT(INDEX)

      IMPLICIT NONE
      INTEGER, INTENT(IN) :: I1, I2, ND1
      INTEGER :: INDEX

      INDEX = I1 + I2*ND1

      RETURN
      END FUNCTION EIRENE_INDIRECT_ADDRESS
