

C*DK MASAJR3
      SUBROUTINE EIRENE_MASAJR3 (A,B,N,R1,R2,R3)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(24), INTENT(IN) :: A
      CHARACTER(8), INTENT(IN) :: B
      INTEGER, INTENT(IN) :: N
      REAL(DP), INTENT(IN) :: R1,R2,R3
      WRITE (iunout,60) A,B,N,R1,R2,R3
   60 FORMAT (1X,A24,1X,A8,1X,I2,1X,3(1PE12.4,1X))
      RETURN
      END SUBROUTINE EIRENE_MASAJR3
