C
C*DK MASJR3
      SUBROUTINE EIRENE_MASJR3 (A,I,B,C,D)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(32), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B, C, D
      INTEGER, INTENT(IN) :: I
      WRITE (iunout,60) A,I,B,C,D
   60 FORMAT (1X,A32,3X,I6,3X,3(1PE12.4,3X))
      RETURN
      END
