C
C*DK MASJR4
      SUBROUTINE EIRENE_MASJR4 (A,I,B,C,D,E)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(24), INTENT(IN) :: A
      REAL(DP), INTENT(IN) :: B,C,D,E
      INTEGER, INTENT(IN) :: I
      WRITE (iunout,60) A,I,B,C,D,E
   60 FORMAT (1X,A24,3X,I6,3X,4(1PE12.4,3X))
      RETURN
      END SUBROUTINE EIRENE_MASJR4
