C
C
C*DK MASJ5
      SUBROUTINE EIRENE_MASJ5(A,I,J,K,L,M)
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(40), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: I, J, K, L, M
      WRITE (iunout,60) A,I,J,K,L,M
   60 FORMAT (1X,A40/1X,5(I6,3X))
      RETURN
      END SUBROUTINE EIRENE_MASJ5
