C
C
C*DK MASRR4
      SUBROUTINE EIRENE_MASRR5 (A,B,C,D,E,F,N)
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
      CHARACTER(22), INTENT(IN) :: A
      INTEGER, INTENT(IN) :: N
      REAL(DP), INTENT(IN) :: B(N), C(N), D(N), E(N), F(N)
      INTEGER :: J
      WRITE (iunout,60) A
   60 FORMAT (1X,A22)
      DO J=1,N
        WRITE (iunout,61) J,B(J),C(J),D(J),E(J),F(J)
      END DO
   61 FORMAT (1X,I4,1X,5(1PE12.4,3X))
      RETURN
      END
