cdr Nov. 19: comments
C
      SUBROUTINE EIRENE_READTL
     . (T1,T2,T3,PROF,NR,NP,NT,NB,NTT,IFLAG,IFILE)
C
C  READ VOLUME-AVERAGED INPUT TALLIES FROM STREAM IFILE
C  IN CASE INDPRO(..)=4.
c  RETURN THIS TALLY ON 1D ARRAY PROF
c  Called from INPUT.F  (for cell volumes, tally -12)
c  and   from PLASMA.F  (for all other input tallies)
C
      USE EIRMOD_PRECISION
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE

      CHARACTER(72), INTENT(OUT) :: T1
      CHARACTER(24), INTENT(OUT) :: T2, T3
      REAL(DP), INTENT(OUT) :: PROF(*)
      INTEGER, INTENT(IN) :: IFILE, IFLAG
      INTEGER, INTENT(OUT) :: NR, NP, NT, NB, NTT
      INTEGER, PARAMETER :: NSTREAM=15
      INTEGER :: ISTREAM(NSTREAM)
      INTEGER :: IRAD, IST, IR
      CHARACTER(72) :: TL

C     DATA TL/72*'='/
      DATA ISTREAM/6,50,20,21,29,30,31,32,33,10,11,12,13,14,15/
      SAVE
      IF (IFILE.GT.0) THEN
        DO IST=1,NSTREAM
          IF (IFILE.EQ.ISTREAM(IST)) THEN
            WRITE (iunout,*) 'ERROR IN INPUT BLOCK 5, INDPRO=4 '
            WRITE (iunout,*) 'STREAM NO. ',IFILE,' IS NOT AVAILABLE'
            GOTO 11111
          ENDIF
        ENDDO
        READ (IFILE,'(A72)') TL
        READ (IFILE,'(A72)') TL
        READ (IFILE,'(A72)') T1
        READ (IFILE,'(A24)') T2
        READ (IFILE,'(A24)') T3
        READ (IFILE,'(A72)') TL
        READ (IFILE,'(A72)') TL
        READ (IFILE,*) NR,NP,NT,NB,NTT
        DO IRAD=1,NTT,5
          READ (IFILE,*) (PROF(IR),IR=IRAD,IRAD+4)
        ENDDO
      ENDIF
11111 CONTINUE
      RETURN
      END
