


C-----------------------------------------------------------------------
               SUBROUTINE EIRENE_SUBTIT(AUSDRU, AKTLEN, HILFE)
C-----------------------------------------------------------------------
C
C     FUNKTION:
C
C     ELIMINATION VON BLANKS UND SUBTITUTION VON '**' DURCH '^'
C
C-----------------------------------------------------------------------
      IMPLICIT NONE

C
C     EIN/AUSGABEPARAMETER :
C
      INTEGER, INTENT(INOUT) :: AKTLEN
C           : AKTUELLE LAENGE VON AUSDRU

      CHARACTER(*), INTENT(INOUT) :: AUSDRU
C           : AUSDRUCK, DER IM UNTERPROGRAMM ZERLEGT WIRD

      CHARACTER(*), INTENT(INOUT) :: HILFE
C           : HILFSSTRING, DER FUER ZUWEISUNGEN BENOETIGT WIRD

C
C     HILFSVARIABLEN :
C
      INTEGER :: I, POS

C
C     ELIMINATION VON BLANKS
C
      I=1
C
C     WHILE-1 : SOLANGE AUSDRU NOCH NICHT VOLLSTAENDIG DURCHLAUFEN
C
      DO WHILE (I .LT. AKTLEN)
C
C        ENTFERNEN VON BLANKS
C
         IF (AUSDRU(I:I) .EQ. ' ') THEN
            IF ( I .EQ. 1) THEN
               HILFE=AUSDRU(I+1:AKTLEN) // ' '
            ELSE
               HILFE=AUSDRU(1:I-1) // AUSDRU(I+1:AKTLEN) // ' '
            ENDIF
            AUSDRU=HILFE
            AKTLEN=AKTLEN-1
         ELSE
            I=I+1
         ENDIF
      END DO
C
C     ENDWHILE-1
C
C
C     SUBTITUTION VON '**' DURCH '^'
C
      CALL EIRENE_REPLACE(AUSDRU,'**','^',AKTLEN)

      CALL EIRENE_REPLACE(AUSDRU,'DX', 'QA',AKTLEN)
      CALL EIRENE_REPLACE(AUSDRU,'DY', 'QB',AKTLEN)
      CALL EIRENE_REPLACE(AUSDRU,'DZ', 'QC',AKTLEN)
      CALL EIRENE_REPLACE(AUSDRU,'EXP','QD',AKTLEN)
      CALL EIRENE_REPLACE(AUSDRU,'LN', 'QE',AKTLEN)
      CALL EIRENE_REPLACE(AUSDRU,'LOG','QF',AKTLEN)
      CALL EIRENE_REPLACE(AUSDRU,'ABS','QG',AKTLEN)
C
C     ENDE VON SUBTIT
C
      CONTAINS

      SUBROUTINE EIRENE_REPLACE (STR, REP, WITH, LENGTH)
      IMPLICIT NONE
      CHARACTER(*), INTENT(INOUT) :: STR
      CHARACTER(*), INTENT(IN) :: REP, WITH
      INTEGER, INTENT(INOUT) :: LENGTH
      INTEGER :: LREP, LWITH, POS
      CHARACTER(:), ALLOCATABLE :: CREP, CWITH, HILFE

      CREP = ADJUSTL(TRIM(REP))
      CWITH = ADJUSTL(TRIM(WITH))
      LREP = LEN(CREP)
      LWITH = LEN(CWITH)
      
      POS=INDEX(STR,CREP)

      DO WHILE ( POS .GE. 1 .AND. POS .LT. LENGTH-1) 

         IF (POS == 1) THEN
           HILFE = CWITH // STR(POS+LREP:LENGTH)
         ELSE
           HILFE=STR(1:POS-1) // CWITH // STR(POS+LREP:LENGTH)
         END IF
         STR=HILFE
         LENGTH=LENGTH - (LREP - LWITH)
         POS=INDEX(STR,CREP)
      END DO  
      
      END SUBROUTINE EIRENE_REPLACE

      END
