      SUBROUTINE EIRENE_CLEAR_STRATUM
C
C  CLEAR WORK AREA FOR THIS STRATUM
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CSPEI
      USE EIRMOD_CESTIM
      USE EIRMOD_CSDVI
      USE EIRMOD_CSDVI_BGK

      IMPLICIT NONE

      INTEGER :: ISPC

      IESTR=-1
C  TALLIES
      ESTIMV=0.
      ESTIMS=0.
      DO ISPC=1,NADSPC
        ESTIML(ISPC)%SPC = 0._DP
        ESTIML(ISPC)%SPCS = 0._DP
      ENDDO

C  VARIANCES, COVARIANCES,...
      SDVI1=0.
      SDVI2=0.
      SIGMAC=0.
      SGMCS=0.
C  ARRAYS SDVIA,SDVIAW,SDVIAC
      SDVIA  = 0.D0
      SDVIAW = 0.D0
      SDVIAC = 0.D0
C  BGK ARRAYS
      SGMS_BGK=0.D0
      SIGMA_BGK=0.D0
      SDVIA_BGK=0.D0
C  SPECTRA
      DO ISPC=1,NADSPC
        IF (NSIGI_SPC > 0) THEN
          ESTIML(ISPC)%SDV = 0._DP
          ESTIML(ISPC)%SGM = 0._DP
          ESTIML(ISPC)%STV = 0._DP
          ESTIML(ISPC)%GG = 0._DP
        END IF
        ESTIML(ISPC)%SGMS = 0._DP
        ESTIML(ISPC)%STVS = 0._DP
        ESTIML(ISPC)%GGS = 0._DP
      END DO

      RETURN

      END SUBROUTINE EIRENE_CLEAR_STRATUM
