!pb  181206  output is done by processor 0
!pb  181206  setting up of census source is done by processor 0
!pb  100107  call to reinitialisation routine
cdr  140416  allow for NSTRAI .le. NSTRA  (e.g. if time stratum has been turned off)
cdr          currently turning off time stratum may not be detected
cdr          when setting dynamic allocatable storage parameters in "find_param.f"
cdr  to be done:  check for further use of NSTRA, rather than NSTRAI
cdr  to be done:  add warnings whenever a storage paramater Nxxx differs from Nxxxi
!pb  MAY 16  nrds -> nrei
cdr  June 17: GR cleanup: call grnxtb...  --> call eirene_plnxtb... 
cdr           (to remove redundant dummy gr routines)
 
 
 
      RECURSIVE SUBROUTINE EIRENE_EIRENE (DT,NLMODE,NLLAST,ITNR,
     .                                    MPI_INITIALIZE)
C
C  DT >  0.      : RUN EIRENE FOR A TIMESTEP DT (S),
C  DT <= 0.      : RUN EIRENE IN QUASI STEADY STATE MODE
C  NLMODE=.FALSE.: FULL EIRENE INITIALIZATION
C                  PLASMA DATA TRANSFER INTO EIRENE CONTROLLED BY REGULAR INPUT OPTIONS
C                  INCLUDING, POSSIBLY, TRANSFER VIA INFCOP, ARRAYS.....
C  NLMODE=.TRUE. : CALLED FROM INTERFACING ROUTINE EIRSRT
C                  PLASMA DATA ON COMMON BRAEIR IN SUBROUTINE INFCOP.
C  ITNR          : ITERATION NUMBER, FOR ITERATIONS WITH EXTERNAL CODE (IF ANY)
C  MPI_INITIALIZE: INITIALIZE USAGE OF MPI-ROUTINES FOR PARALLEL COMPUTATION
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR
!pb      USE EIRMOD_CREFMOD
      USE EIRMOD_CREF
      USE EIRMOD_CESTIM
      USE EIRMOD_CRECH
      USE EIRMOD_CADGEO
      USE EIRMOD_cai
      USE EIRMOD_CCONA
      USE EIRMOD_CGRPTL
      USE EIRMOD_CLOGAU
      USE EIRMOD_CPL3D
      USE EIRMOD_CPLOT
      USE EIRMOD_CINIT
      USE EIRMOD_CUPD
      USE EIRMOD_COMSIG
      USE EIRMOD_CPOLYG
      USE EIRMOD_CGRID
      USE EIRMOD_CSPEZ
      USE EIRMOD_CZT1
      USE EIRMOD_CTRCEI
      USE EIRMOD_CCOUPL
      USE EIRMOD_CGEOM
      USE EIRMOD_CSDVI
      USE EIRMOD_CSDVI_COP
      USE EIRMOD_CSDVI_BGK
      USE EIRMOD_CTETRA
      USE EIRMOD_COMPRT
      USE EIRMOD_CPES
      USE EIRMOD_COMNNL
      USE EIRMOD_COMSOU
      USE EIRMOD_CSTEP
      USE EIRMOD_COMSPL
      USE EIRMOD_CTEXT
      USE EIRMOD_CLGIN
      USE EIRMOD_COUTAU
      USE EIRMOD_COMXS
      USE EIRMOD_CSPEI
      USE EIRMOD_CTRIG
      USE EIRMOD_CLAST
      use EIRMOD_cfplk
 
      IMPLICIT NONE
 
      INCLUDE 'mpif.h'
 
      REAL(DP), INTENT(IN) :: DT
      LOGICAL, INTENT(IN) :: NLMODE, NLLAST, MPI_INITIALIZE
      INTEGER, INTENT(IN) :: ITNR
 
      INTEGER :: IERROR, IER, ISTRAI
      REAL(DP) :: EIRENE_RESET_SECOND, EIRENE_SECOND_OWN, DUMMY, TIMI
      integer, save :: inentry=1, init_log=0
      logical :: nlplas_save
      character(20) :: outname
C
C               1.         INITIALIZE PACKAGE
C
      TIMI=EIRENE_SECOND_OWN()
      IF (MPI_INITIALIZE) CALL MPI_INIT(IER)
      CALL MPI_COMM_SIZE (MPI_COMM_WORLD,NPRS,IER)
      CALL MPI_COMM_RANK (MPI_COMM_WORLD,MY_PE,IER)

      NRPES = NPRS
      IF (NPRS == 1) NSTEFF=1

      CALL EIRENE_DEFAULTS_USR

cdr  this is currently done in COMPRT. Should be moved to PARMMOD, or somewhere else early enough
c     IUNIN = 1
      IUNIN = IUNIN + IFOFF
 
      IUNOUT = 6
      IF (NRPES > 1) IUNOUT = 7
      IUNOUT = IUNOUT + IFOFF


CDR  OUTPUT STREAM IS: IUNOUT. THIS IS ALSO THE STREAM FOR MASTER PROCESSOR MY_PE =0
cdr  MPI:  DEFINE OUTPUT STREAMS FOR OTHER PROCESSORS
      IF (NPRS > 1) THEN
        OUTNAME='output.'
        WRITE (OUTNAME(8:),'(I4.4)') MY_PE
        OPEN (UNIT=IUNOUT,FILE=OUTNAME, ACCESS='SEQUENTIAL',
     .        FORM='FORMATTED')
      END IF
 
      IF (MY_PE == 0) THEN
 
        IF (ITNR == 1) THEN
          CALL EIRENE_FIND_PARAM
          CALL EIRENE_SET_PARMMOD(1)
        ELSE
          DUMMY=EIRENE_RESET_SECOND()
        END IF
 
        write (iunout,*) ' Number of PEs ',nprs
        if (nprs .gt. nrpes) then
          write (iunout,*) ' Number of PE too large '
          write (iunout,*) ' increase parameter NRPES = ',nrpes
          call EIRENE_exit_own(1)
        endif
 
        IF (ITNR == 1) CALL EIRENE_ALLOC_CLOGAU
        CALL EIRENE_ALLOC_COMPRT

        inentry = 0
 
        NRAPS=60
        IRAPS=0
        IITER=ITNR
        ITIMV=1
        IPRNLI=0
        
        DTIMVN=DT
        NLPLAS=NLMODE

        TIME=EIRENE_SECOND_OWN()
        write (iunout,*) ' CPU TIME for startup of Eirene ',time-timi
 
      END IF  ! MY_PE == 0

C
100   CONTINUE
C
C  READ FORMATTED INPUT FILE OR RESTART FOR NEXT ITERATION
C
      ENTRY EIRENE_EIRENE_COUPLE (NLLAST,ITNR,MPI_INITIALIZE)
 
      IF (MY_PE == 0) THEN

        TIMI=EIRENE_SECOND_OWN()
C
        IF (INENTRY == 1) THEN
          nlplas_save = nlplas
          CALL EIRENE_SET_PARMMOD(1)
          if (init_log == 0) CALL EIRENE_ALLOC_CLOGAU
          CALL EIRENE_ALLOC_COMPRT
          nlplas = nlplas_save
        END IF

        init_log = 1
        CALL EIRENE_ALLOC_CESTIM(1)
        CALL EIRENE_ALLOC_COMUSR(1)
        CALL EIRENE_ALLOC_CADGEO
        CALL EIRENE_ALLOC_CAI
        CALL EIRENE_ALLOC_CPLOT
        CALL EIRENE_ALLOC_CINIT
        CALL EIRENE_ALLOC_CUPD
        CALL EIRENE_ALLOC_CPOLYG
        CALL EIRENE_ALLOC_CGRID
        CALL EIRENE_ALLOC_CSPEZ
        CALL EIRENE_ALLOC_CZT1(1)
        CALL EIRENE_ALLOC_CTRCEI
        CALL EIRENE_ALLOC_CGEOM(1)
        CALL EIRENE_ALLOC_CSDVI(1)
        CALL EIRENE_ALLOC_CTETRA
        CALL EIRENE_ALLOC_CPES
        IF (ITNR == 1) CALL EIRENE_ALLOC_COMSOU(1)
        CALL EIRENE_ALLOC_COMSPL
        CALL EIRENE_ALLOC_CTEXT(1)
        CALL EIRENE_ALLOC_CLGIN
        CALL EIRENE_ALLOC_COMXS(1)
        CALL EIRENE_ALLOC_CTRIG
        CALL EIRENE_ALLOC_COMNNL
        CALL EIRENE_ALLOC_CFPLK

        TIME=EIRENE_SECOND_OWN()
        write (iunout,*) ' CPU TIME for memory allocation ',time-timi
 
cdr make sure that nstrai is properly set in find_param.f
        IF (ITNR == 1) NLSRON(1:NSTRAI) = .TRUE.
C
C   SET SOME CONSTANTS
C
        CALL EIRENE_SETCON
 
      END IF  ! MY_PE == 0
C
C  each internal iteration or time-step starts here
101   CONTINUE
C  IITER=... , ITIME=...
c  re-initialize some "ifirst"-blocks
      CALL EIRENE_PLNXTB(3,'EIRENE.F')
 
      IF (MY_PE == 0) THEN
 
      TIMI=EIRENE_SECOND_OWN()
C
      CALL EIRENE_INPUT
 
      CALL EIRENE_ALLOC_COUTAU
C
C  CHECK PARAMETER STATEMENTS, STORAGE REQUIREMENTS
C
      CALL EIRENE_SETPRM
 
      CALL EIRENE_ALLOC_CSTEP
      CALL EIRENE_ALLOC_CSPEI
      CALL EIRENE_ALLOC_CSDVI(2)
      CALL EIRENE_ALLOC_CSDVI_BGK
      CALL EIRENE_ALLOC_CSDVI_COP
      CALL EIRENE_ALLOC_CLAST
 
      CALL EIRENE_STTXT1
C
      TIME=EIRENE_SECOND_OWN()
      WRITE (iunout,*) 'CPU-TIME CONSUMED IN INPUT: ',TIME-TIMI,' SEC'
      CALL EIRENE_LEER(1)
C
C  SET UP SPLITTING SURFACES, IMPORTANCE FUNCTION AND OTHER DATA
C  FOR NONANALOG METHODS
C
      IF (.NOT.NLANA) THEN
        CALL EIRENE_NANALG
      ELSEIF (NLANA) THEN
C  TURN OF ALL NON-ANALOG SAMPLING
        CALL EIRENE_MASBOX('NON-ANALOG SAMPLING DE-ACTIVATED')
C 1: NO SPLITTING AND RUSSIAN ROULETTE
        WRITE (iunout,*) 'SUBROUTINE NANALG NOT CALLED'
C 2: SPECIES SOURCE SAMPLING
        DO ISTRAI=1,NSTRAI
          NSPEZ(ISTRAI)=MAX(0,NSPEZ(ISTRAI))
        ENDDO
        WRITE (iunout,*) 'NON-ANALOG SOURCE SPECIES SAMPLING TURNED OFF'
C 3: SUPPRESSION OF ABSORPTION AT SURFACES TURNED OFF
        WMINS=1.D30
        WRITE (iunout,*)
     .    'SUPPRESSION OF ABSORPTION AT SURFACES TURNED OFF'
C 4: SUPPRESSION OF ABSORPTION AT COLLISIONS TURNED OFF
        WMINV=1.D30
        WRITE (iunout,*)
     .    'SUPPRESSION OF ABSORPTION AT COLLISIONS TURNED OFF'
        CALL EIRENE_LEER(2)
      ENDIF
C
      TIMI=EIRENE_SECOND_OWN()
C
C
C  PARAMETERS FOR BGK ITERATIONS
C
      NBGVI=NRBGI
      NFSTVI(NTALB)=NBGVI
      NBGVI_STAT=0
      IF (NSIGI_BGK > 0) NBGVI_STAT=NBGVI+2*(NATMI+NMOLI)
      IF (NBGVI_STAT > NBGV_STAT) THEN
        CALL EIRENE_MASPRM('NBGVI_STAT',10,NBGVI_STAT,
     .              'NBGV_STAT',9,NBGV_STAT,IERROR)
        CALL EIRENE_EXIT_OWN(1)
      END IF
C
      IF (TRCAMD) THEN
        CALL EIRENE_LEER(1)
        WRITE (iunout,*) 'NRCXI,NRCX ',NRCXI,NRCX
        WRITE (iunout,*) 'NRELI,NREL ',NRELI,NREL
        WRITE (iunout,*) 'NRPII,NRPI ',NRPII,NRPI
        WRITE (iunout,*) 'NREII,NREI ',NREII,NREI
        WRITE (iunout,*) 'NRRCI,NREC ',NRRCI,NREC
        CALL EIRENE_LEER(1)
      ENDIF
C
C
C  READ EIRENE STATISTICAL RECOMMENDATIONS FROM PREVIOUS RUN,
C  AND CARRY THEM OUT
C
      IF (NFILEK.EQ.2.OR.NFILEK.EQ.3) THEN
        CALL EIRENE_RREC
        WRITE (iunout,*) 'STRATIFIED SOURCE SAMPLING:'
        WRITE (iunout,*) 'NPTS(ISTRA) ARE MODIFIED, DUE TO NFILEK.GE.2 '
        DO 162 ISTRAI=1,NSTRAI
          WRITE (iunout,*) ISTRAI,' NPTS(INP)= ',NPTS(ISTRAI),
     .                      ' NPTS(MOD)= ',NRECOM(ISTRAI)
          NPTS(ISTRAI)=NRECOM(ISTRAI)
162     CONTINUE
      ENDIF
C
C  IF NLERG:
C  PERFORM A RUN, ONE-SPEED, COLLISION-LESS, UNTIL TIME-LIMIT
C  FOR CELL VOLUME ESTIMATION FROM ERGODIC PRINZIPLE
C
      IF (NLERG) CALL EIRENE_ERGOD
C
C  IF NLMOVIE:
C  PERFORM A RUN, MANY TIMESTEPS, CONSTANT NUMBER OF PARTICLES IN
C  PICTURE, COLD START FROM PREVIOUS CENSUS.
C  FOR MOVIE OF PARTICLE TRAJECTORIES
C  INVERT ORDER OF STRATA IN ORDER TO HAVE CENSUS STRATUM FIRST.
C
      IF (NLMOVIE) CALL EIRENE_MOVIE

C  ATOMIC & MOLECULAR DATA DIAGNOSTICS ON ADDITIONAL INPUT ARRAY ADIN
C
      CALL EIRENE_AMDIAG
C
C  PRINT VOLUME AVERAGED INPUT TALLIES.
C
      CALL EIRENE_OUTPLA(0)
C
      TIME=EIRENE_SECOND_OWN()
C     WRITE (iunout,*) 'CPU-TIME CONSUMED IN XSECT: ',TIME-TIMI,' SEC'
      CALL EIRENE_LEER(1)
C
C               2.         PLOT GEOMETRY
C
200   CONTINUE
      IF (IITER.GT.1.OR.ITIMV.GT.1) GOTO 300  ! GEOMETRY PLOT ONLY ONCE
 
C     TIMI=EIRENE_SECOND_OWN()
      CALL EIRENE_PLT2D
C     TIME=EIRENE_SECOND_OWN()
C     WRITE (iunout,*) 'CPU-TIME CONSUMED IN PLT2D: ',TIME-TIMI,' SEC'
C
C               3.         MONTE CARLO CALCULATION
C
300   CONTINUE
 
      END IF   ! MY_PE == 0
 
      if (nprs > 1) CALL EIRENE_BROADCAST
 
      CALL EIRENE_MCARLO
C
C               4.         OUTPUT , INTERFACE  AND PLOTTING
C
400   CONTINUE
C
C  OUTPUT FOR SELECTED STRATA AND/OR SUM OVER STRATA
C
      IF (MY_PE == 0) THEN
      DO 450 ISTRAI=1,NSTRAI
          ISTRA=ISTRAI
          IF (TRCSRC(ISTRA).OR.(NSTRAI.EQ.1.AND.TRCSRC(0)))
     .        CALL EIRENE_OUTEIR(ISTRA)
          IF (PLTSRC(ISTRA).OR.(NSTRAI.EQ.1.AND.PLTSRC(0)))
     .        CALL EIRENE_PLTEIR(ISTRA)
450   CONTINUE
C

 
      IF ((NSTRAI.GT.1) .AND. (NSMSTRA==1))  THEN
        IF (TRCSRC(0)) CALL EIRENE_OUTEIR(0)
        IF (PLTSRC(0)) CALL EIRENE_PLTEIR(0)
      ENDIF
C
C  WRITE FILES FOR RAPS GRAPHICS
C
      IF (IRAPS.GT.0) THEN
        CALL EIRENE_RPSOUT
        NRAPS=60
        IRAPS=0
      ENDIF
C
C  LAST CALL TO INTERFACING ROUTINE (GLOBAL BALANCES, ETC)
C
      IF (NMODE.GT.0) CALL EIRENE_IF4COP
C
!dr   IF (NFILEN.EQ.2.OR.NFILEN.EQ.7) RETURN
C
C  CALL WRREC TO EVALUATE EIRENE STATISTICAL RECOMMENDATIONS
C  FOR NEXT RUN  AND WRITE THEM ON FT 14
C
      IF (NFILEK.EQ.1.OR.NFILEK.EQ.3) THEN
c   achtung !!!!!!!!!!!!!
c   fuer parallele version noch nicht richtig
c   noch mal ganz scharf nachdenken !!!!!!!!
        CALL EIRENE_WRREC
      ENDIF
 
 
C  POST PROCESSING FOR BACKGROUND TALLIES, E.G. FOR DIAGNO, ITERATION, ETC.
      CALL EIRENE_PLASMA_DERIV(1)
C  PRINT THOSE BACKGROUND TALLIES WHICH HAVE BEEN MODIFIED
C  IN PLASMA_DERIV(1)
      CALL EIRENE_OUTPLA(1)

      END IF  ! MY_PE == 0
C
C  ITERATIVE MONTE CARLO PROBLEM: EIRENE RECALL OPTION
C
C  SUBROUTINE MODUSR IS A USER SUPPLIED SUBROUTINE, WHICH MAY BE USED
C  TO MODIFY SOME OF THE INPUT VARIABLES FOR THE NEXT ITERATION STEP.
C  MODUSR IS ALSO CALLED AFTER THE LAST ITERATION TO ALLOW
C  WRITING OF DATA ONTO SOME FILE AFTER EACH ITERATION
C
      IF (NITER.GE.1.AND.IITER.LE.NITER) THEN
        IF (MY_PE == 0) THEN
          IF (NBGK > 0) CALL EIRENE_MODBGK
          CALL EIRENE_MODUSR
        END IF
        IITER=IITER+1
        IF (IITER.LE.NITER) THEN
          DUMMY=EIRENE_RESET_SECOND()
          IPRNLI=0
          GOTO 101
        ENDIF
      ENDIF

      IF (MY_PE == 0) THEN
C
C  CALL DIAGNOSTIC MODULE (COMPUTE LINE INTEGRALS FROM EIRENE TALLIES)
C
 
      IF (NCHORI.GT.0) CALL EIRENE_DIAGNO

csw  user defined output
      CALL EIRENE_OUTUSR
 
      END IF   ! MY_PE == 0
C
C  SUBROUTINE STOSS IS A SUBROUTINE, IN WHICH BINARY COLLISION
C  EVENTS BETWEEN TEST PARTICLES ARE CARRIED OUT
C  STOSS IS ALSO CALLED AFTER THE LAST "TIMESTEP"
C
      IF (NTIME.GE.1) THEN
C  COLLISIONS BETWEEN TEST PARTICLES ON CENSUS, OLD DSMC ALGORITHM, NOT AVAILABLE ANY MORE
C       CALL STOSS
C  MODIFY BACKGROUND (TIME DEP. MODE)
        IF (MY_PE == 0) CALL EIRENE_MOD_TMSTEP
        ITIMV=ITIMV+1
        IF (ITIMV.LE.NTIME) THEN
C  DO ONE MORE COMPLETE TIME-CYCLE IN THIS EIRENE RUN
c  A SINGLE TIME CYCLE MAY INVOLVE MANY NON-LIN. ITERATIONS.
C  HENCE: RESET IITER TO 1
          DUMMY=EIRENE_RESET_SECOND()
          IITER=1
          IPRNLI=0
          GOTO 101
        ENDIF
      ENDIF

C  PRINT OUTPUT FOR IDL BASED EXTERNAL GRAPHICS AND POST PROCESSING
      IF (PLIDL.AND.(MY_PE == 0)) THEN
         CALL EIRENE_MASBOX
     .          ('OUTPUT OPTION: IDL, PER STRATUM ')
        call eirene_outidlconf
        call eirene_outidlpla
        call eirene_outidltal
      END IF

      call EIRENE_REINITIALIZATION_OF_EIRENE
 
      IF (NLLAST) THEN
         CALL EIRENE_DEALLOC_COMUSR
!pb      CALL EIRENE_DEALLOC_CREFMOD
         CALL EIRENE_DEALLOC_CREF
         CALL EIRENE_DEALLOC_CESTIM
         CALL EIRENE_DEALLOC_CADGEO
         CALL EIRENE_DEALLOC_CAI
         CALL EIRENE_DEALLOC_CGRPTL
         CALL EIRENE_DEALLOC_CPLOT
         CALL EIRENE_DEALLOC_CINIT
         CALL EIRENE_DEALLOC_CUPD
         IF (NCHORI > 0) CALL EIRENE_DEALLOC_COMSIG
         CALL EIRENE_DEALLOC_CPOLYG
         CALL EIRENE_DEALLOC_CGRID
         CALL EIRENE_DEALLOC_CSPEZ
         CALL EIRENE_DEALLOC_CZT1
         CALL EIRENE_DEALLOC_CTRCEI
         IF (NMODE .NE. 0) CALL EIRENE_DEALLOC_CCOUPL
         CALL EIRENE_DEALLOC_CGEOM
         CALL EIRENE_DEALLOC_CSDVI
         CALL EIRENE_DEALLOC_CSDVI_BGK
         CALL EIRENE_DEALLOC_CSDVI_COP
         CALL EIRENE_DEALLOC_CTETRA
         CALL EIRENE_DEALLOC_CTRIG
         CALL EIRENE_DEALLOC_COMPRT
         CALL EIRENE_DEALLOC_CPES
         CALL EIRENE_DEALLOC_COMNNL
         CALL EIRENE_DEALLOC_COMSOU
         CALL EIRENE_DEALLOC_CSTEP
         CALL EIRENE_DEALLOC_COMSPL
         CALL EIRENE_DEALLOC_CTEXT
         CALL EIRENE_DEALLOC_CLGIN
         CALL EIRENE_DEALLOC_COUTAU
         CALL EIRENE_DEALLOC_COMXS
         CALL EIRENE_DEALLOC_CSPEI
         CALL EIRENE_DEALLOC_CLAST
         call EIRENE_dealloc_cfplk
         CALL EIRENE_LOCAT2            ! DEALLOCATE LOCAL ARRAYS IN LOCATE
         CALL EIRENE_SAMSF2            ! DEALLOCATE LOCAL ARRAYS IN SAMSRF
         CALL EIRENE_STATS3            ! DEALLOCATE LOCAL ARRAYS IN STATIS
C
         IF (MPI_INITIALIZE) CALL MPI_FINALIZE(IER)
      END IF
 


cdr april 2015
c  nprs: total number of processors used in this run
c  my_pe is the current processor
c
c  in case of multi-timesteps, t-dep coupling, (or internal iterations?),
c  output is reduced by the next three lines.
c  this leads to confusing (missing) output then.
c  probably these next three lines must go out?
cdr april 2015

!pb   IF (MY_PE > 0) THEN
      IF (NPRS > 1) THEN
         CLOSE (UNIT=IUNOUT)
      END IF
 
      RETURN
 
C     the following entry is for reinitialization of EIRENE (DMH)
 
      ENTRY EIRENE_EIRENE_REINIT
      inentry = 1
      return
      END
