cdr    dec. 15:  added species index ipls, for volumetric energy source tallies for bulk ions
cdr              eapl,empl,eipl,ephpl
cdr   24.09.14:  scaling of new sputter tallies with fatm, fmol,fion,nphot: corrected 
c  spring 2014:  new sputter tallies introduced: emitted species resolved
C  15.02.05 :    double printout: fatm2,....taken out. use only getscl4, not getscl
C   6. 7.05 :    call ph_integrate for photon-background tallies taken out.
C                no more additional photon background tallies active
C  15.12.05 :    rescaling connected to spump surface tally

 
      SUBROUTINE EIRENE_SCALE_TALLIES (ISTRA)
C
C  RESCALE TRACKLENGTH ESTIMATED VOLUME AVERAGED TALLIES 
C  WITH PARTICLE BALANCE CORRECTION FACTORS FATM,FMOL,FION,FPHOT
C  TO ENFORCE PERFECT GLOBAL PARTICLE BALANCE
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR
      USE EIRMOD_COMPRT, ONLY : IUNOUT
      USE EIRMOD_CLOGAU
      USE EIRMOD_COUTAU
      USE EIRMOD_CGRID
      USE EIRMOD_CCONA
      USE EIRMOD_CESTIM
 
      IMPLICIT NONE
 
      INTEGER, INTENT(IN) :: ISTRA
      REAL(DP) :: FATM, FMOL, FION, FPHOT, FADD
      INTEGER :: IATM, IMOL, IION, IPLS, IPHOT, IADV, ICLV, IBGV, ICPV,
     .           J, ISPC
C
!     CALL GETSCL (ISTRA,FATM,FMOL,FION,FPHOT)
      CALL EIRENE_GETSCL4 (ISTRA,FATM,FMOL,FION,FPHOT)
C
      IF (.NOT.NLSCL) THEN
 
        CALL EIRENE_LEER(1)
        WRITE (iunout,*) 'NO RESCALING DONE (NLSCL=FALSE)'
        CALL EIRENE_LEER(2)
 
      ELSEIF (NLSCL) THEN
 
        FASCL(ISTRA) = FATM
        FMSCL(ISTRA) = FMOL
        FISCL(ISTRA) = FION
        FPHSCL(ISTRA)= FPHOT
C
C  CARRY OUT SCALING OF VOLUME AND SURFACE TALLIES, RESP.
C
C  ATOM TALLIES
C
c  volumetric atomic tallies
        DO 2101 IATM=1,NATMI
          DO 111 J=1,NSBOX_TAL
            IF (LPDENA) PDENA(IATM,J)=PDENA(IATM,J)*FATM
            IF (LEDENA) EDENA(IATM,J)=EDENA(IATM,J)*FATM
            IF (LPAAT) PAAT(IATM,J)=PAAT(IATM,J)*FATM
            IF (LPMAT) PMAT(IATM,J)=PMAT(IATM,J)*FMOL
            IF (LPIAT) PIAT(IATM,J)=PIAT(IATM,J)*FION
            IF (LPPHAT) PPHAT(IATM,J)=PPHAT(IATM,J)*FPHOT
            IF (LPGENA) PGENA(IATM,J)=PGENA(IATM,J)*FATM
            IF (LEGENA) EGENA(IATM,J)=EGENA(IATM,J)*FATM
            IF (LVGENA) VGENA(IATM,J)=VGENA(IATM,J)*FATM
            IF (LVXDENA) VXDENA(IATM,J)=VXDENA(IATM,J)*FATM
            IF (LVYDENA) VYDENA(IATM,J)=VYDENA(IATM,J)*FATM
            IF (LVZDENA) VZDENA(IATM,J)=VZDENA(IATM,J)*FATM
111       CONTINUE
c  atomic surface tallies
          DO 310 J=1,NLIMPS
            IF (LPOTAT) POTAT(IATM,J)=POTAT(IATM,J)*FATM
            IF (LPRFAAT) PRFAAT(IATM,J)=PRFAAT(IATM,J)*FATM
            IF (LPRFMAT) PRFMAT(IATM,J)=PRFMAT(IATM,J)*FMOL
            IF (LPRFIAT) PRFIAT(IATM,J)=PRFIAT(IATM,J)*FION
            IF (LPRFPHAT) PRFPHAT(IATM,J)=PRFPHAT(IATM,J)*FPHOT
            IF (LEOTAT) EOTAT(IATM,J)=EOTAT(IATM,J)*FATM
            IF (LERFAAT) ERFAAT(IATM,J)=ERFAAT(IATM,J)*FATM
            IF (LERFMAT) ERFMAT(IATM,J)=ERFMAT(IATM,J)*FMOL
            IF (LERFIAT) ERFIAT(IATM,J)=ERFIAT(IATM,J)*FION
            IF (LERFPHAT) ERFPHAT(IATM,J)=ERFPHAT(IATM,J)*FPHOT
            IF (LSPTAAT) SPTAAT(IATM,J)=SPTAAT(IATM,J)*FATM
            IF (LSPTMAT) SPTMAT(IATM,J)=SPTMAT(IATM,J)*FMOL
            IF (LSPTIAT) SPTIAT(IATM,J)=SPTIAT(IATM,J)*FION
            IF (LSPTPHAT) SPTPHAT(IATM,J)=SPTPHAT(IATM,J)*FPHOT
cdr  ?? scaling with bulk flux? 
cdr         IF (LSPTPAT) SPTPAT(IATM,J)=SPTPAT(IATM,J)*FATM

            IF (LSPUMP) SPUMP (NSPH+IATM,J)=SPUMP (NSPH+IATM,J)*FATM
310       CONTINUE

2101    CONTINUE

        if (lsptatot) sptatot = sptatot * fatm

c  integrated atomic tallies, both volumetric and surface averaged 
        DO 2111 IATM=0,NATMI
          PDENAI(IATM,ISTRA)=PDENAI(IATM,ISTRA)*FATM
          EDENAI(IATM,ISTRA)=EDENAI(IATM,ISTRA)*FATM
          PAATI(IATM,ISTRA)=PAATI(IATM,ISTRA)*FATM
          PMATI(IATM,ISTRA)=PMATI(IATM,ISTRA)*FMOL
          PIATI(IATM,ISTRA)=PIATI(IATM,ISTRA)*FION
          PPHATI(IATM,ISTRA)=PPHATI(IATM,ISTRA)*FPHOT
          PGENAI(IATM,ISTRA)=PGENAI(IATM,ISTRA)*FATM
          EGENAI(IATM,ISTRA)=EGENAI(IATM,ISTRA)*FATM
          VGENAI(IATM,ISTRA)=VGENAI(IATM,ISTRA)*FATM
          VXDENAI(IATM,ISTRA)=VXDENAI(IATM,ISTRA)*FATM
          VYDENAI(IATM,ISTRA)=VYDENAI(IATM,ISTRA)*FATM
          VZDENAI(IATM,ISTRA)=VZDENAI(IATM,ISTRA)*FATM

          POTATI(IATM,ISTRA)=POTATI(IATM,ISTRA)*FATM
          PRFAAI(IATM,ISTRA)=PRFAAI(IATM,ISTRA)*FATM
          PRFMAI(IATM,ISTRA)=PRFMAI(IATM,ISTRA)*FMOL
          PRFIAI(IATM,ISTRA)=PRFIAI(IATM,ISTRA)*FION
          PRFPHAI(IATM,ISTRA)=PRFPHAI(IATM,ISTRA)*FPHOT
          EOTATI(IATM,ISTRA)=EOTATI(IATM,ISTRA)*FATM
          ERFAAI(IATM,ISTRA)=ERFAAI(IATM,ISTRA)*FATM
          ERFMAI(IATM,ISTRA)=ERFMAI(IATM,ISTRA)*FMOL
          ERFIAI(IATM,ISTRA)=ERFIAI(IATM,ISTRA)*FION
          ERFPHAI(IATM,ISTRA)=ERFPHAI(IATM,ISTRA)*FPHOT
          SPTAATI(IATM,ISTRA)=SPTAATI(IATM,ISTRA)*FATM
          SPTMATI(IATM,ISTRA)=SPTMATI(IATM,ISTRA)*FMOL
          SPTIATI(IATM,ISTRA)=SPTIATI(IATM,ISTRA)*FION
          SPTPHATI(IATM,ISTRA)=SPTPHATI(IATM,ISTRA)*FPHOT
cdr  ?? scaling with bulk flux ?? 
cdr       SPTPATI(IATM,ISTRA)=SPTPATI(IATM,ISTRA)*FATM

          SPUMPI(NSPH+IATM,ISTRA)=SPUMPI(NSPH+IATM,ISTRA)*FATM
          
2111    CONTINUE

        sptatti(istra) = sptatti(istra)*fatm

        DO 2112 J=1,NSBOX_TAL
          IF (LEAAT) EAAT(J)=EAAT(J)*FATM
          IF (LEMAT) EMAT(J)=EMAT(J)*FMOL
          IF (LEIAT) EIAT(J)=EIAT(J)*FION
          IF (LEPHAT) EPHAT(J)=EPHAT(J)*FPHOT
2112    CONTINUE
        EAATI(ISTRA)=EAATI(ISTRA)*FATM
        EMATI(ISTRA)=EMATI(ISTRA)*FMOL
        EIATI(ISTRA)=EIATI(ISTRA)*FION
        EPHATI(ISTRA)=EPHATI(ISTRA)*FPHOT
C
C  MOLECULE TALLIES
C
        DO 2115 IMOL=1,NMOLI
          DO 115 J=1,NSBOX_TAL
            IF (LPDENM) PDENM(IMOL,J)=PDENM(IMOL,J)*FMOL
            IF (LEDENM) EDENM(IMOL,J)=EDENM(IMOL,J)*FMOL
            IF (LPAML) PAML(IMOL,J)=PAML(IMOL,J)*FATM
            IF (LPMML) PMML(IMOL,J)=PMML(IMOL,J)*FMOL
            IF (LPIML) PIML(IMOL,J)=PIML(IMOL,J)*FION
            IF (LPPHML) PPHML(IMOL,J)=PPHML(IMOL,J)*FPHOT
            IF (LPGENM) PGENM(IMOL,J)=PGENM(IMOL,J)*FMOL
            IF (LEGENM) EGENM(IMOL,J)=EGENM(IMOL,J)*FMOL
            IF (LVGENM) VGENM(IMOL,J)=VGENM(IMOL,J)*FMOL
            IF (LVXDENM) VXDENM(IMOL,J)=VXDENM(IMOL,J)*FMOL
            IF (LVYDENM) VYDENM(IMOL,J)=VYDENM(IMOL,J)*FMOL
            IF (LVZDENM) VZDENM(IMOL,J)=VZDENM(IMOL,J)*FMOL
115       CONTINUE
          DO 315 J=1,NLIMPS
            IF (LPOTML) POTML(IMOL,J)=POTML(IMOL,J)*FMOL
            IF (LPRFAML) PRFAML(IMOL,J)=PRFAML(IMOL,J)*FATM
            IF (LPRFMML) PRFMML(IMOL,J)=PRFMML(IMOL,J)*FMOL
            IF (LPRFIML) PRFIML(IMOL,J)=PRFIML(IMOL,J)*FION
            IF (LPRFPHML) PRFPHML(IMOL,J)=PRFPHML(IMOL,J)*FPHOT
            IF (LEOTML) EOTML(IMOL,J)=EOTML(IMOL,J)*FMOL
            IF (LERFAML) ERFAML(IMOL,J)=ERFAML(IMOL,J)*FATM
            IF (LERFMML) ERFMML(IMOL,J)=ERFMML(IMOL,J)*FMOL
            IF (LERFIML) ERFIML(IMOL,J)=ERFIML(IMOL,J)*FION
            IF (LERFPHML) ERFPHML(IMOL,J)=ERFPHML(IMOL,J)*FPHOT
            IF (LSPTAML) SPTAML(IMOL,J)=SPTAML(IMOL,J)*FATM
            IF (LSPTMML) SPTMML(IMOL,J)=SPTMML(IMOL,J)*FMOL
            IF (LSPTIML) SPTIML(IMOL,J)=SPTIML(IMOL,J)*FION
            IF (LSPTPHML) SPTPHML(IMOL,J)=SPTPHML(IMOL,J)*FPHOT
cdr  ?? scaling with bulk flux ??  
cdr         IF (LSPTPML) SPTPML(IMOL,J)=SPTPML(IMOL,J)*FMOL
            IF (LSPUMP) SPUMP (NSPA+IMOL,J)=SPUMP(NSPA+IMOL,J)*FMOL
315       CONTINUE
2115    CONTINUE

        if (lsptmtot) sptmtot = sptmtot*fmol 
 
        DO 2116 IMOL=0,NMOLI
          PDENMI(IMOL,ISTRA)=PDENMI(IMOL,ISTRA)*FMOL
          EDENMI(IMOL,ISTRA)=EDENMI(IMOL,ISTRA)*FMOL
          PAMLI(IMOL,ISTRA)=PAMLI(IMOL,ISTRA)*FATM
          PMMLI(IMOL,ISTRA)=PMMLI(IMOL,ISTRA)*FMOL
          PIMLI(IMOL,ISTRA)=PIMLI(IMOL,ISTRA)*FION
          PPHMLI(IMOL,ISTRA)=PPHMLI(IMOL,ISTRA)*FPHOT
          PGENMI(IMOL,ISTRA)=PGENMI(IMOL,ISTRA)*FMOL
          EGENMI(IMOL,ISTRA)=EGENMI(IMOL,ISTRA)*FMOL
          VGENMI(IMOL,ISTRA)=VGENMI(IMOL,ISTRA)*FMOL
          VXDENMI(IMOL,ISTRA)=VXDENMI(IMOL,ISTRA)*FMOL
          VYDENMI(IMOL,ISTRA)=VYDENMI(IMOL,ISTRA)*FMOL
          VZDENMI(IMOL,ISTRA)=VZDENMI(IMOL,ISTRA)*FMOL

          POTMLI(IMOL,ISTRA)=POTMLI(IMOL,ISTRA)*FMOL
          PRFAMI(IMOL,ISTRA)=PRFAMI(IMOL,ISTRA)*FATM
          PRFMMI(IMOL,ISTRA)=PRFMMI(IMOL,ISTRA)*FMOL
          PRFIMI(IMOL,ISTRA)=PRFIMI(IMOL,ISTRA)*FION
          PRFPHMI(IMOL,ISTRA)=PRFPHMI(IMOL,ISTRA)*FPHOT
          EOTMLI(IMOL,ISTRA)=EOTMLI(IMOL,ISTRA)*FMOL
          ERFAMI(IMOL,ISTRA)=ERFAMI(IMOL,ISTRA)*FATM
          ERFMMI(IMOL,ISTRA)=ERFMMI(IMOL,ISTRA)*FMOL
          ERFIMI(IMOL,ISTRA)=ERFIMI(IMOL,ISTRA)*FION
          ERFPHMI(IMOL,ISTRA)=ERFPHMI(IMOL,ISTRA)*FPHOT
          SPTAMLI(IMOL,ISTRA)=SPTAMLI(IMOL,ISTRA)*FATM
          SPTMMLI(IMOL,ISTRA)=SPTMMLI(IMOL,ISTRA)*FMOL
          SPTIMLI(IMOL,ISTRA)=SPTIMLI(IMOL,ISTRA)*FION
          SPTPHMLI(IMOL,ISTRA)=SPTPHMLI(IMOL,ISTRA)*FPHOT
cdr  ?? scaling with bulk flux ??  
cdr       SPTPMLI(IMOL,ISTRA)=SPTPMLI(IMOL,ISTRA)*FMOL
          SPUMPI(NSPA+IMOL,ISTRA)=SPUMPI(NSPA+IMOL,ISTRA)*FMOL
          
2116    CONTINUE

        sptmtti(istra) = sptmtti(istra)*fmol
 
        DO 2117 J=1,NSBOX_TAL
          IF (LEAML) EAML(J)=EAML(J)*FATM
          IF (LEMML) EMML(J)=EMML(J)*FMOL
          IF (LEIML) EIML(J)=EIML(J)*FION
          IF (LEPHML) EPHML(J)=EPHML(J)*FPHOT
2117    CONTINUE
        EAMLI(ISTRA)=EAMLI(ISTRA)*FATM
        EMMLI(ISTRA)=EMMLI(ISTRA)*FMOL
        EIMLI(ISTRA)=EIMLI(ISTRA)*FION
        EPHMLI(ISTRA)=EPHMLI(ISTRA)*FPHOT
C
C  TEST ION TALLIES
C
        DO 420 IION=1,NIONI
          DO 421 J=1,NSBOX_TAL
            IF (LPDENI) PDENI(IION,J)=PDENI(IION,J)*FION
            IF (LEDENI) EDENI(IION,J)=EDENI(IION,J)*FION
            IF (LPAIO) PAIO(IION,J)=PAIO(IION,J)*FATM
            IF (LPMIO) PMIO(IION,J)=PMIO(IION,J)*FMOL
            IF (LPIIO) PIIO(IION,J)=PIIO(IION,J)*FION
            IF (LPPHIO) PPHIO(IION,J)=PPHIO(IION,J)*FPHOT
            IF (LPGENI) PGENI(IION,J)=PGENI(IION,J)*FION
            IF (LEGENI) EGENI(IION,J)=EGENI(IION,J)*FION
            IF (LVGENI) VGENI(IION,J)=VGENI(IION,J)*FION
            IF (LVXDENI) VXDENI(IION,J)=VXDENI(IION,J)*FION
            IF (LVYDENI) VYDENI(IION,J)=VYDENI(IION,J)*FION
            IF (LVZDENI) VZDENI(IION,J)=VZDENI(IION,J)*FION
421       CONTINUE
          DO 422 J=1,NLIMPS
            IF (LPOTIO) POTIO(IION,J)=POTIO(IION,J)*FION
            IF (LPRFAIO) PRFAIO(IION,J)=PRFAIO(IION,J)*FATM
            IF (LPRFMIO) PRFMIO(IION,J)=PRFMIO(IION,J)*FMOL
            IF (LPRFIIO) PRFIIO(IION,J)=PRFIIO(IION,J)*FION
            IF (LPRFPHIO) PRFPHIO(IION,J)=PRFPHIO(IION,J)*FPHOT
            IF (LEOTIO) EOTIO(IION,J)=EOTIO(IION,J)*FION
            IF (LERFAIO) ERFAIO(IION,J)=ERFAIO(IION,J)*FATM
            IF (LERFMIO) ERFMIO(IION,J)=ERFMIO(IION,J)*FMOL
            IF (LERFIIO) ERFIIO(IION,J)=ERFIIO(IION,J)*FION
            IF (LERFPHIO) ERFPHIO(IION,J)=ERFPHIO(IION,J)*FPHOT
            IF (LSPTAIO) SPTAIO(IION,J)=SPTAIO(IION,J)*FATM
            IF (LSPTMIO) SPTMIO(IION,J)=SPTMIO(IION,J)*FMOL
            IF (LSPTIIO) SPTIIO(IION,J)=SPTIIO(IION,J)*FION
            IF (LSPTPHIO) SPTPHIO(IION,J)=SPTPHIO(IION,J)*FPHOT
cdr  ?? scaling with bulk flux ??  
cdr         IF (LSPTPIO) SPTPIO(IION,J)=SPTPIO(IION,J)*FION
            IF (LSPUMP) SPUMP(NSPAM+IION,J)=SPUMP(NSPAM+IION,J)*FION
422       CONTINUE
420     CONTINUE
 
        if (lsptitot) sptitot = sptitot*fion

        DO 431 IION=0,NIONI
          PDENII(IION,ISTRA)=PDENII(IION,ISTRA)*FION
          EDENII(IION,ISTRA)=EDENII(IION,ISTRA)*FION
          PAIOI(IION,ISTRA)=PAIOI(IION,ISTRA)*FATM
          PMIOI(IION,ISTRA)=PMIOI(IION,ISTRA)*FMOL
          PIIOI(IION,ISTRA)=PIIOI(IION,ISTRA)*FION
          PPHIOI(IION,ISTRA)=PPHIOI(IION,ISTRA)*FPHOT
          PGENII(IION,ISTRA)=PGENII(IION,ISTRA)*FION
          EGENII(IION,ISTRA)=EGENII(IION,ISTRA)*FION
          VGENII(IION,ISTRA)=VGENII(IION,ISTRA)*FION
          VXDENII(IION,ISTRA)=VXDENII(IION,ISTRA)*FION
          VYDENII(IION,ISTRA)=VYDENII(IION,ISTRA)*FION
          VZDENII(IION,ISTRA)=VZDENII(IION,ISTRA)*FION

          POTIOI(IION,ISTRA)=POTIOI(IION,ISTRA)*FION
          PRFAII(IION,ISTRA)=PRFAII(IION,ISTRA)*FATM
          PRFMII(IION,ISTRA)=PRFMII(IION,ISTRA)*FMOL
          PRFIII(IION,ISTRA)=PRFIII(IION,ISTRA)*FION
          PRFPHII(IION,ISTRA)=PRFPHII(IION,ISTRA)*FPHOT
          EOTIOI(IION,ISTRA)=EOTIOI(IION,ISTRA)*FION
          ERFAII(IION,ISTRA)=ERFAII(IION,ISTRA)*FATM
          ERFMII(IION,ISTRA)=ERFMII(IION,ISTRA)*FMOL
          ERFIII(IION,ISTRA)=ERFIII(IION,ISTRA)*FION
          ERFPHII(IION,ISTRA)=ERFPHII(IION,ISTRA)*FPHOT
          SPTAIOI(IION,ISTRA)=SPTAIOI(IION,ISTRA)*FATM
          SPTMIOI(IION,ISTRA)=SPTMIOI(IION,ISTRA)*FMOL
          SPTIIOI(IION,ISTRA)=SPTIIOI(IION,ISTRA)*FION
          SPTPHIOI(IION,ISTRA)=SPTPHIOI(IION,ISTRA)*FPHOT
cdr  ?? scaling with bulk flux ??  
cdr       SPTPIOI(IION,ISTRA)=SPTPIOI(IION,ISTRA)*FION
          SPUMPI(NSPAM+IION,ISTRA)=SPUMPI(NSPAM+IION,ISTRA)*FION
          
431     CONTINUE

        sptitti(istra) = sptitti(istra)*fion
        
        DO 432 J=1,NSBOX_TAL
          IF (LEAIO) EAIO(J)=EAIO(J)*FATM
          IF (LEMIO) EMIO(J)=EMIO(J)*FMOL
          IF (LEIIO) EIIO(J)=EIIO(J)*FION
          IF (LEPHIO) EPHIO(J)=EPHIO(J)*FPHOT
432     CONTINUE
        EAIOI(ISTRA)=EAIOI(ISTRA)*FATM
        EMIOI(ISTRA)=EMIOI(ISTRA)*FMOL
        EIIOI(ISTRA)=EIIOI(ISTRA)*FION
        EPHIOI(ISTRA)=EPHIOI(ISTRA)*FPHOT
C
C  PHOTON TALLIES
C
        DO IPHOT=1,NPHOTI
          DO J=1,NSBOX_TAL
            IF (LPDENPH) PDENPH(IPHOT,J)=PDENPH(IPHOT,J)*FPHOT
            IF (LEDENPH) EDENPH(IPHOT,J)=EDENPH(IPHOT,J)*FPHOT
            IF (LPAPHT)  PAPHT (IPHOT,J)=PAPHT (IPHOT,J)*FATM
            IF (LPMPHT)  PMPHT (IPHOT,J)=PMPHT (IPHOT,J)*FMOL
            IF (LPIPHT)  PIPHT (IPHOT,J)=PIPHT (IPHOT,J)*FION
            IF (LPPHPHT) PPHPHT(IPHOT,J)=PPHPHT(IPHOT,J)*FPHOT
            IF (LPGENPH) PGENPH(IPHOT,J)=PGENPH(IPHOT,J)*FPHOT
            IF (LEGENPH) EGENPH(IPHOT,J)=EGENPH(IPHOT,J)*FPHOT
            IF (LVGENPH) VGENPH(IPHOT,J)=VGENPH(IPHOT,J)*FPHOT
            IF (LVXDENPH) VXDENPH(IPHOT,J)=VXDENPH(IPHOT,J)*FPHOT
            IF (LVYDENPH) VYDENPH(IPHOT,J)=VYDENPH(IPHOT,J)*FPHOT
            IF (LVZDENPH) VZDENPH(IPHOT,J)=VZDENPH(IPHOT,J)*FPHOT
          END DO
C  SURFACE AVERAGED TALLIES
          DO J=1,NLIMPS
            IF (LPOTPHT)  POTPHT (IPHOT,J)=POTPHT (IPHOT,J)*FPHOT
            IF (LPRFAPHT) PRFAPHT(IPHOT,J)=PRFAPHT(IPHOT,J)*FATM
            IF (LPRFMPHT) PRFMPHT(IPHOT,J)=PRFMPHT(IPHOT,J)*FMOL
            IF (LPRFIPHT) PRFIPHT(IPHOT,J)=PRFIPHT(IPHOT,J)*FION
            IF (LPRFPHPHT) PRFPHPHT(IPHOT,J)=PRFPHPHT(IPHOT,J)*FPHOT
            IF (LPRFPPHT) PRFPPHT(IPHOT,J)=PRFPPHT(IPHOT,J)*FPHOT
            IF (LEOTPHT) EOTPHT (IPHOT,J)=EOTPHT (IPHOT,J)*FPHOT
            IF (LERFAPHT) ERFAPHT(IPHOT,J)=ERFAPHT(IPHOT,J)*FATM
            IF (LERFMPHT) ERFMPHT(IPHOT,J)=ERFMPHT(IPHOT,J)*FMOL
            IF (LERFIPHT) ERFIPHT(IPHOT,J)=ERFIPHT(IPHOT,J)*FION
            IF (LERFPHPHT) ERFPHPHT(IPHOT,J)=ERFPHPHT(IPHOT,J)*FPHOT
            IF (LERFPPHT) ERFPPHT(IPHOT,J)=ERFPPHT(IPHOT,J)*FPHOT
            IF (LSPTAPHT) SPTAPHT(IPHOT,J)=SPTAPHT(IPHOT,J)*FATM
            IF (LSPTMPHT) SPTMPHT(IPHOT,J)=SPTMPHT(IPHOT,J)*FMOL
            IF (LSPTIPHT) SPTIPHT(IPHOT,J)=SPTIPHT(IPHOT,J)*FION
            IF (LSPTPHPHT) SPTPHPHT(IPHOT,J)=SPTPHPHT(IPHOT,J)*FPHOT
cdr  ?? scaling with bulk flux ?? 
cdr         IF (LSPTPPHT) SPTPPHT(IPHOT,J)=SPTPPHT(IPHOT,J)*FPHOT
            IF (LSPUMP) SPUMP (IPHOT,J)=SPUMP (IPHOT,J)*FPHOT
          END DO
        END DO

        if (lsptphtot) sptphtot = sptphtot*fphot

        DO IPHOT=0,NPHOTI
          PDENPHI(IPHOT,ISTRA)=PDENPHI(IPHOT,ISTRA)*FPHOT
          EDENPHI(IPHOT,ISTRA)=EDENPHI(IPHOT,ISTRA)*FPHOT
          PAPHTI (IPHOT,ISTRA)=PAPHTI (IPHOT,ISTRA)*FATM
          PMPHTI (IPHOT,ISTRA)=PMPHTI (IPHOT,ISTRA)*FMOL
          PIPHTI (IPHOT,ISTRA)=PIPHTI (IPHOT,ISTRA)*FION
          PPHPHTI(IPHOT,ISTRA)=PPHPHTI(IPHOT,ISTRA)*FPHOT
          PGENPHI(IPHOT,ISTRA)=PGENPHI(IPHOT,ISTRA)*FPHOT
          EGENPHI(IPHOT,ISTRA)=EGENPHI(IPHOT,ISTRA)*FPHOT
          VGENPHI(IPHOT,ISTRA)=VGENPHI(IPHOT,ISTRA)*FPHOT
          VXDENPHI(IPHOT,ISTRA)=VXDENPHI(IPHOT,ISTRA)*FPHOT
          VYDENPHI(IPHOT,ISTRA)=VYDENPHI(IPHOT,ISTRA)*FPHOT
          VZDENPHI(IPHOT,ISTRA)=VZDENPHI(IPHOT,ISTRA)*FPHOT

          POTPHTI(IPHOT,ISTRA)=POTPHTI(IPHOT,ISTRA)*FPHOT
          PRFAPHTI(IPHOT,ISTRA)=PRFAPHTI(IPHOT,ISTRA)*FATM
          PRFMPHTI(IPHOT,ISTRA)=PRFMPHTI(IPHOT,ISTRA)*FMOL
          PRFIPHTI(IPHOT,ISTRA)=PRFIPHTI(IPHOT,ISTRA)*FION
          PRFPHPHTI(IPHOT,ISTRA)=PRFPHPHTI(IPHOT,ISTRA)*FPHOT
          EOTPHTI(IPHOT,ISTRA)=EOTPHTI(IPHOT,ISTRA)*FPHOT
          ERFAPHTI(IPHOT,ISTRA)=ERFAPHTI(IPHOT,ISTRA)*FATM
          ERFMPHTI(IPHOT,ISTRA)=ERFMPHTI(IPHOT,ISTRA)*FMOL
          ERFIPHTI(IPHOT,ISTRA)=ERFIPHTI(IPHOT,ISTRA)*FION
          ERFPHPHTI(IPHOT,ISTRA)=ERFPHPHTI(IPHOT,ISTRA)*FPHOT
          SPTAPHTI(IPHOT,ISTRA)=SPTAPHTI(IPHOT,ISTRA)*FATM
          SPTMPHTI(IPHOT,ISTRA)=SPTMPHTI(IPHOT,ISTRA)*FMOL
          SPTIPHTI(IPHOT,ISTRA)=SPTIPHTI(IPHOT,ISTRA)*FION
          SPTPHPHTI(IPHOT,ISTRA)=SPTPHPHTI(IPHOT,ISTRA)*FPHOT
cdr  ?? scaling with bulk flux ?? 
cdr       SPTPPHTI(IPHOT,ISTRA)=SPTPPHTI(IPHOT,ISTRA)*FPHOT
          SPUMPI(IPHOT,ISTRA)=SPUMPI(IPHOT,ISTRA)*FPHOT
          
        END DO

        sptphtti(istra) = sptphtti(istra)*fphot

        DO J=1,NSBOX_TAL
          IF (LEAPHT) EAPHT(J)=EAPHT(J)*FATM
          IF (LEMPHT) EMPHT(J)=EMPHT(J)*FMOL
          IF (LEIPHT) EIPHT(J)=EIPHT(J)*FION
          IF (LEPHPHT) EPHPHT(J)=EPHPHT(J)*FPHOT
        END DO
        EAPHTI(ISTRA)=EAPHTI(ISTRA)*FATM
        EMPHTI(ISTRA)=EMPHTI(ISTRA)*FMOL
        EIPHTI(ISTRA)=EIPHTI(ISTRA)*FION
        EPHPHTI(ISTRA)=EPHPHTI(ISTRA)*FPHOT
 
csw integrate/scale internal photon tallies
cdr     IF (NPHOTI > 0)
cdr  .    CALL PH_INTEGRATE(ISTRA,FLXFAC(ISTRA)/ELCHA,
cdr  .                    fphot,fatm,fmol,fion)
C
C  ADDITIONAL TRACKLENGTH ESTIMATED TALLIES
C
        IF (LADDV) THEN
          DO 423 IADV=1,NADVI
            IF (IADRC(IADV).EQ.0) THEN
              FADD=FPHOT
            ELSEIF (IADRC(IADV).EQ.1) THEN
              FADD=FATM
            ELSEIF (IADRC(IADV).EQ.2) THEN
              FADD=FMOL
            ELSEIF (IADRC(IADV).EQ.3) THEN
              FADD=FION
            ELSE
              GOTO 423
            ENDIF
            DO 424 J=1,NSBOX_TAL
              ADDV(IADV,J)=ADDV(IADV,J)*FADD
424         CONTINUE
            ADDVI(IADV,ISTRA)=ADDVI(IADV,ISTRA)*FADD
423       CONTINUE
        END IF
C
C  ADDITIONAL COLLISION ESTIMATED TALLIES
C
        IF (LCOLV) THEN
          DO 426 ICLV=1,NCLVI
            IF (ICLRC(ICLV).EQ.0) THEN
              FADD=FPHOT
            ELSEIF (ICLRC(ICLV).EQ.1) THEN
              FADD=FATM
            ELSEIF (ICLRC(ICLV).EQ.2) THEN
              FADD=FMOL
            ELSEIF (ICLRC(ICLV).EQ.3) THEN
              FADD=FION
            ELSE
              GOTO 426
            ENDIF
            DO 427 J=1,NSBOX_TAL
              COLV(ICLV,J)=COLV(ICLV,J)*FADD
427         CONTINUE
            COLVI(ICLV,ISTRA)=COLVI(ICLV,ISTRA)*FADD
426       CONTINUE
        END IF
C
C  SNAPSHOT TALLIES
C
C  TO BE WRITTEN
C
C  TALLIES FOR COUPLING TO FLUID PLASMA CODE
C
        IF (LCOPV) THEN
          DO 435 ICPV=1,NCPVI
            IF (ICPRC(ICPV).EQ.1) THEN
              FADD=FATM
            ELSEIF (ICPRC(ICPV).EQ.2) THEN
              FADD=FMOL
            ELSEIF (ICPRC(ICPV).EQ.3) THEN
              FADD=FION
            ELSEIF (ICPRC(ICPV).EQ.0) THEN
              FADD=FPHOT
            ELSE
              GOTO 435
            ENDIF
            DO 436 J=1,NSBOX_TAL
              COPV(ICPV,J)=COPV(ICPV,J)*FADD
436         CONTINUE
            COPVI(ICPV,ISTRA)=COPVI(ICPV,ISTRA)*FADD
435       CONTINUE
        END IF
C
C  TALLIES FOR BGK SELF COLLISION ITERATIONS
C
        IF (LBGKV) THEN
          DO 437 IBGV=1,NBGVI
            IF (IBGRC(IBGV).EQ.1) THEN
              FADD=FATM
            ELSEIF (IBGRC(IBGV).EQ.2) THEN
              FADD=FMOL
            ELSEIF (IBGRC(IBGV).EQ.3) THEN
              FADD=FION
            ELSEIF (IBGRC(IBGV).EQ.0) THEN
              FADD=FPHOT
            ELSE
              GOTO 437
            ENDIF
            DO 438 J=1,NSBOX_TAL
              BGKV(IBGV,J)=BGKV(IBGV,J)*FADD
438         CONTINUE
            BGKVI(IBGV,ISTRA)=BGKVI(IBGV,ISTRA)*FADD
437       CONTINUE
        END IF
C
C  BULK ION TALLIES
C
        DO IPLS=1,NPLSI
          DO J=1,NSBOX_TAL
            IF (LPAPL) PAPL(IPLS,J)=PAPL(IPLS,J)*FATM
            IF (LPMPL) PMPL(IPLS,J)=PMPL(IPLS,J)*FMOL
            IF (LPIPL) PIPL(IPLS,J)=PIPL(IPLS,J)*FION
            IF (LPPHPL) PPHPL(IPLS,J)=PPHPL(IPLS,J)*FPHOT
            IF (LEAPL) EAPL(IPLS,J)=EAPL(IPLS,J)*FATM
            IF (LEMPL) EMPL(IPLS,J)=EMPL(IPLS,J)*FMOL
            IF (LEIPL) EIPL(IPLS,J)=EIPL(IPLS,J)*FION
            IF (LEPHPL) EPHPL(IPLS,J)=EPHPL(IPLS,J)*FPHOT
            IF (LMAPL) MAPL(IPLS,J)=MAPL(IPLS,J)*FATM
            IF (LMMPL) MMPL(IPLS,J)=MMPL(IPLS,J)*FMOL
            IF (LMIPL) MIPL(IPLS,J)=MIPL(IPLS,J)*FION
            IF (LMPHPL) MPHPL(IPLS,J)=MPHPL(IPLS,J)*FPHOT
          END DO
        END DO
        DO IPLS=0,NPLSI
          PAPLI(IPLS,ISTRA)=PAPLI(IPLS,ISTRA)*FATM
          PMPLI(IPLS,ISTRA)=PMPLI(IPLS,ISTRA)*FMOL
          PIPLI(IPLS,ISTRA)=PIPLI(IPLS,ISTRA)*FION
          PPHPLI(IPLS,ISTRA)=PPHPLI(IPLS,ISTRA)*FPHOT
          EAPLI(IPLS,ISTRA)=EAPLI(IPLS,ISTRA)*FATM
          EMPLI(IPLS,ISTRA)=EMPLI(IPLS,ISTRA)*FMOL
          EIPLI(IPLS,ISTRA)=EIPLI(IPLS,ISTRA)*FION
          EPHPLI(IPLS,ISTRA)=EPHPLI(IPLS,ISTRA)*FPHOT
          MAPLI(IPLS,ISTRA)=MAPLI(IPLS,ISTRA)*FATM
          MMPLI(IPLS,ISTRA)=MMPLI(IPLS,ISTRA)*FMOL
          MIPLI(IPLS,ISTRA)=MIPLI(IPLS,ISTRA)*FION
          MPHPLI(IPLS,ISTRA)=MPHPLI(IPLS,ISTRA)*FPHOT
        END DO
C
C  ELECTRON TALLIES
C
        DO 551 J=1,NSBOX_TAL
          IF (LPAEL) PAEL(J)=PAEL(J)*FATM
          IF (LPMEL) PMEL(J)=PMEL(J)*FMOL
          IF (LPIEL) PIEL(J)=PIEL(J)*FION
          IF (LPPHEL) PPHEL(J)=PPHEL(J)*FPHOT
551     CONTINUE
        PAELI(ISTRA)=PAELI(ISTRA)*FATM
        PMELI(ISTRA)=PMELI(ISTRA)*FMOL
        PIELI(ISTRA)=PIELI(ISTRA)*FION
        PPHELI(ISTRA)=PPHELI(ISTRA)*FPHOT
        DO 552 J=1,NSBOX_TAL
          IF (LEAEL) EAEL(J)=EAEL(J)*FATM
          IF (LEMEL) EMEL(J)=EMEL(J)*FMOL
          IF (LEIEL) EIEL(J)=EIEL(J)*FION
          IF (LEPHEL) EPHEL(J)=EPHEL(J)*FPHOT
552     CONTINUE
        EAELI(ISTRA)=EAELI(ISTRA)*FATM
        EMELI(ISTRA)=EMELI(ISTRA)*FMOL
        EIELI(ISTRA)=EIELI(ISTRA)*FION
        EPHELI(ISTRA)=EPHELI(ISTRA)*FPHOT
C
C  SPECTRUM TALLIES
C 
        DO ISPC=1,NADSPC
          SELECT CASE (ESTIML(ISPC)%PSPC%IPRTYP)
          CASE (0)
            FADD = FPHOT
          CASE (1)
            FADD = FATM
          CASE (2)
            FADD = FMOL
          CASE (3)
            FADD = FION
          CASE DEFAULT
            FADD = 1._DP
          END SELECT
          ESTIML(ISPC)%PSPC%SPC = ESTIML(ISPC)%PSPC%SPC * FADD
          ESTIML(ISPC)%PSPC%SPCS = ESTIML(ISPC)%PSPC%SPCS * FADD
        END DO
 
C
        CALL EIRENE_LEER(1)
        WRITE (iunout,*) ('RESCALING OF TRACKLENGTH TALLIES COMPLETED')
        WRITE (iunout,*) ('RESCALING FACTORS:                        ')
        CALL EIRENE_MASR4 ('FATM,FMOL,FION,FPHOT            ',
     .               FATM, FMOL, FION, FPHOT)
!       CALL MASR4 ('FATM2,FMOL2,FION2,FPHOT2        ',
!    .               FATM2, FMOL2, FION2, FPHOT2)
        CALL EIRENE_LEER(2)
C
      ENDIF
 
      RETURN
      END SUBROUTINE EIRENE_SCALE_TALLIES
