      SUBROUTINE EIRENE_SCAL_SURF_TALLIES (ISTR)
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CESTIM
      USE EIRMOD_COUTAU
      USE EIRMOD_CCONA
 
      IMPLICIT NONE
 
      INTEGER, INTENT(IN) :: ISTR
      INTEGER :: I, IATM, IMOL, IION, IPHOT, IPLS, ISPC
      REAL(DP) :: DEL, DELI, ELEFT, ERIGHT
 
      ESTIMS=ESTIMS*FLXFAC(ISTR)
C
      ETOTA(ISTR)=ETOTA(ISTR)*FLXFAC(ISTR)
      ETOTM(ISTR)=ETOTM(ISTR)*FLXFAC(ISTR)
      ETOTI(ISTR)=ETOTI(ISTR)*FLXFAC(ISTR)
      ETOTP(ISTR)=ETOTP(ISTR)*FLXFAC(ISTR)
      ETOTPH(ISTR)=ETOTPH(ISTR)*FLXFAC(ISTR)
      PTRASH(ISTR)=PTRASH(ISTR)*FLXFAC(ISTR)
      ETRASH(ISTR)=ETRASH(ISTR)*FLXFAC(ISTR)
      DO 610 IATM=0,NATM
        WTOTA(IATM,ISTR)=WTOTA(IATM,ISTR)*FLXFAC(ISTR)
610   CONTINUE
      DO 615 IMOL=0,NMOL
        WTOTM(IMOL,ISTR)=WTOTM(IMOL,ISTR)*FLXFAC(ISTR)
615   CONTINUE
      DO 620 IION=0,NION
        EELFI(IION,ISTR)=EELFI(IION,ISTR)*FLXFAC(ISTR)
        WTOTI(IION,ISTR)=WTOTI(IION,ISTR)*FLXFAC(ISTR)
620   CONTINUE
      DO 622 IPHOT=0,NPHOT
        WTOTPH(IPHOT,ISTR)=WTOTPH(IPHOT,ISTR)*FLXFAC(ISTR)
 622  CONTINUE
      DO 625 IPLS=0,NPLS
        WTOTP(IPLS,ISTR)=WTOTP(IPLS,ISTR)*FLXFAC(ISTR)
625   CONTINUE
      WTOTE(ISTR)=WTOTE(ISTR)*FLXFAC(ISTR)
 
C   SCALE AND INTEGRATE SURFACE SPECTRA
 
      DO ISPC=1,NADSPC
        IF (ESTIML(ISPC)%PSPC%ISRFCLL == 0) THEN
C  SURFACE FLUX SPECTRA
          ESTIML(ISPC)%PSPC%SPCS = 0._DP
          DO I = 0, ESTIML(ISPC)%PSPC%NSPC+1
            IF (I.EQ.0) THEN

              ELEFT = MIN(ESTIML(ISPC)%PSPC%SPCMIN,
     .                   ESTIML(ISPC)%PSPC%ESP_MIN)
              ERIGHT= ESTIML(ISPC)%PSPC%SPCMIN
            ELSE IF (I.EQ.ESTIML(ISPC)%PSPC%NSPC+1) THEN
              ELEFT = ESTIML(ISPC)%PSPC%SPCMAX
              ERIGHT= MAX(ESTIML(ISPC)%PSPC%SPCMAX,
     .                   ESTIML(ISPC)%PSPC%ESP_MAX)
            ELSE
              ELEFT = ESTIML(ISPC)%PSPC%SPCMIN+
     .               ESTIML(ISPC)%PSPC%SPCDEL*(I-1)
              ERIGHT= ESTIML(ISPC)%PSPC%SPCMIN+
     .               ESTIML(ISPC)%PSPC%SPCDEL*I
            END IF
            IF (ESTIML(ISPC)%PSPC%LOG) THEN
              DEL = 10._DP**ERIGHT-10._DP**ELEFT+EPS60
            ELSE
              DEL = ERIGHT-ELEFT+EPS60
            END IF
            DELI = 1._DP/(DEL+EPS60)
C  SCALE: FROM SCORING PER ENERGY BIN --> TALLY UNITS: PER EV 
            ESTIML(ISPC)%PSPC%SPC(I) =
     .      ESTIML(ISPC)%PSPC%SPC(I)*FLXFAC(ISTR)*DELI
C  INTEGRATE
            ESTIML(ISPC)%PSPC%SPCS = ESTIML(ISPC)%PSPC%SPCS +
     .                               ESTIML(ISPC)%PSPC%SPC(I)*DEL
          END DO
        END IF
      END DO
 
      RETURN
 
      END SUBROUTINE EIRENE_SCAL_SURF_TALLIES
