c  16.12.05  cleaned up
      SUBROUTINE EIRENE_STAT_SUMOSTRA
C
C    STATISTICS, SUM OVER STRATA
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CSDVI
      USE EIRMOD_CGRID
      USE EIRMOD_CSPEI
      USE EIRMOD_CCONA
      USE EIRMOD_COMSOU
      USE EIRMOD_CESTIM

      IMPLICIT NONE

      REAL(DP) :: ST
      INTEGER :: K, I, ISPC, J, ISDV, ICELL
C  VOLUME TALLIES
      DO 1207 K=1,NSIGVI
        DO 1208 I=1,NSBOX_TAL
          ST=MAX(0._DP,STV(K,I))
          STV(K,I)=SQRT(ST)/(ABS(EE(K,I))+EPS60)
 1208   CONTINUE
        ST=MAX(0._DP,STVS(K))
        STVS(K)=SQRT(ST)/(ABS(EES(K))+EPS60)
 1207 CONTINUE
C  SPECTRUM TALLIES
      IF ((NSTRAI > 1) .AND. (NSMSTRA > 0)) THEN
        IF (NSIGI_SPC.GT.0) THEN
          DO ISPC=1,NADSPC
            DO I=0,SMESTL(ISPC)%NSPC+1
              ST=MAX(0._DP,SMESTL(ISPC)%STV(I))
              SMESTL(ISPC)%STV(I)=SQRT(ST)/
     .                     (ABS(SMESTL(ISPC)%GG(I))+EPS60)
            END DO
            ST=MAX(0._DP,SMESTL(ISPC)%STVS)
            SMESTL(ISPC)%STVS=SQRT(ST)/
     .                             (ABS(SMESTL(ISPC)%GGS)+EPS60)
          END DO
        ENDIF
      ENDIF
C  SURFACE TALLIES
      DO 1221 K=1,NSIGSI
        DO 1222 J=1,NLIMPS
          ST=MAX(0._DP,STVW(K,J))
          STVW(K,J)=SQRT(ST)/(ABS(FF(K,J))+EPS60)
 1222   CONTINUE
        ST=MAX(0._DP,STVWS(K))
        STVWS(K)=SQRT(ST)/(ABS(FFS(K))+EPS60)
 1221 CONTINUE
C
      DO 1240 ISDV=1,NSIGCI
        DO 1242 ICELL=1,NSBOX_TAL
          STVC(1,ISDV,ICELL)=SQRT(MAX(0._DP,STVC(1,ISDV,ICELL)))
          STVC(2,ISDV,ICELL)=SQRT(MAX(0._DP,STVC(2,ISDV,ICELL)))
 1242   CONTINUE
        STVCS(1,ISDV)=SQRT(MAX(0._DP,STVCS(1,ISDV)))
        STVCS(2,ISDV)=SQRT(MAX(0._DP,STVCS(2,ISDV)))
 1240 CONTINUE
C
C  CONVERT RELATIVE ERRORS TO %-ERRORS
C
      STV  = STV*100._DP
      STVS = STVS*100._DP
      STVW  = STVW*100._DP
      STVWS = STVWS*100._DP
C
      IF ((NSTRAI > 1) .AND. (NSMSTRA > 0)) THEN
        IF (NSIGI_SPC.GT.0) THEN
          DO ISPC=1,NADSPC
            SMESTL(ISPC)%STVS=SMESTL(ISPC)%STVS*100.D0
            DO J=0,SMESTL(ISPC)%NSPC+1
              SMESTL(ISPC)%STV(J)=SMESTL(ISPC)%STV(J)*100.D0
            END DO
          END DO
        ENDIF
      ENDIF

      RETURN

      END SUBROUTINE EIRENE_STAT_SUMOSTRA
