C  sept. 05:  5 tallies added to step functions.  see also: CSTEP.f
C  nov.  05:  add eltot and ve to step function data.
C
C  same as  WRPLAM.f, RPLAM.f, but for XDR format
C
      SUBROUTINE EIRENE_WRPLAM_XDR_SHRT(TRCFLE,IFLG)
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      USE EIRMOD_CCOUPL
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: IFLG
      LOGICAL, INTENT(IN) :: TRCFLE
      INTEGER :: IUN

      IF(.NOT.ASSOCIATED(NFLA)) THEN
         WRITE(iunout,*) 
     w         "ERROR IN WRPLAM_XDR_SHRT: NFLA WAS NOT ASSOCIATED. ",
     w         "NO DATA WILL BE STORED IN FORT.13"
         RETURN
      END IF
C
      CALL FXDROPN ('fort13','ENCODE',iun)
 
      CALL FXDRDBL (IUN,TIIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)
      CALL FXDRDBL (IUN,DIIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)
      CALL FXDRDBL (IUN,VXIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)
      CALL FXDRDBL (IUN,VYIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)
      CALL FXDRDBL (IUN,VZIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)
 
      CALL FXDRCLS (IUN)
      RETURN
C
C
C
      ENTRY EIRENE_RPLAM_XDR_SHRT(TRCFLE,IFLG)
C
      CALL FXDROPN ('fort13','DECODE',iun)

      CALL FXDRDBL (IUN,TIIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)
      CALL FXDRDBL (IUN,DIIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)
      CALL FXDRDBL (IUN,VXIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)
      CALL FXDRDBL (IUN,VYIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)
      CALL FXDRDBL (IUN,VZIN(NFLA+1:NPLSI,1:NRAD),(NPLSI-NFLA+1)*NRAD)

      CALL FXDRCLS (IUN)
      RETURN
      END
