cdr jan 16: remove redundant iflg for short (SHRT) versions 
C
C  same as  WRPLAM.f, RPLAM.f, but for XDR format
C
      SUBROUTINE EIRENE_WRPLAM_XDR(TRCFLE,IFLG)
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CLOGAU
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: IFLG
      LOGICAL TRCFLE
C
      IF (NLSHRT13) THEN
        CALL EIRENE_WRPLAM_XDR_SHRT (TRCFLE)
      ELSE 
        CALL EIRENE_WRPLAM_XDR_LONG (TRCFLE,IFLG)
      ENDIF
      RETURN
C
C
C
      ENTRY EIRENE_RPLAM_XDR(TRCFLE,IFLG)
C
      IF (NLSHRT13) THEN
        CALL EIRENE_RPLAM_XDR_SHRT (TRCFLE)
      ELSE 
        CALL EIRENE_RPLAM_XDR_LONG (TRCFLE,IFLG)
      ENDIF
      RETURN
      END
