

      SUBROUTINE EIRENE_BROAD_IESTR(IESTR)
      USE EIRMOD_MPI
      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IESTR
      INTEGER :: IER

      CALL EIRENE_CHECK_EXIT
      CALL MPI_BARRIER (MPI_COMM_WORLD,IER)
      CALL MPI_BCAST (IESTR,1,MPI_INTEGER,0,MPI_COMM_WORLD,IER)
      CALL MPI_BARRIER (MPI_COMM_WORLD,IER)

      RETURN
      END
