      subroutine EIRENE_broad_pedist (xtim)

cdr  Purpose: .... 
      USE EIRMOD_PRECISION, ONLY: DP
      USE EIRMOD_PARMMOD, ONLY: NSTRA
      USE EIRMOD_COMSOU, ONLY: NPTS
      USE EIRMOD_CPES, ONLY: NPESTA, NPESTR, NPRS, NSTEFF, 
     >                       PROCFORSTRA
 
      IMPLICIT NONE
 
      INCLUDE 'mpif.h'
 
      real(dp), intent(in) :: xtim(0:nstra)
      INTEGER :: IER
 
      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)
 
      CALL MPI_BCAST (NPESTR,NSTRA+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPESTA,NSTRA+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPTS,NSTRA,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSTEFF,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (XTIM,NSTRA+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (PROCFORSTRA,NSTRA*NPRS,MPI_LOGICAL,0,
     .                MPI_COMM_WORLD,ier)
 
      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)
 
      RETURN
      END SUBROUTINE EIRENE_broad_pedist
