!  30.08.06:  broadcast of density-models and spectra introduced
!             broadcast of logicals for living and missing tallies added
!             broadcast of reaction data adopted to new structure
!  10.01.07:  increase number of entries in LLOGAU
!  02.03.07:  remove escd2* arrays
!  20.06.07:  MAXLEVEL used for broadcast of RSPLST and ISPLST
!  20.06.07:  NCONA used for broadcast of RCONA
!  20.06.07:  NUM_PARM used for broadcast of parameters in PARMMOD
!  20.06.07:  NSPEZV_DIM used for broadcast of NSPEZV
!  20.06.07:  NLOGAU used for broadcast of LLOGAU
!  01.07.09:  broadcast of HFTR0-3 arrays removed. this is done in broadref.f
!  01.03.11:  NSPEZV_DIM removed
cdr 15.10.14:  renaming of arrays for variances for sum over strata 'smestl' spectrum tallies
cdr  JAN  16:  additional species index for eplds-->eplei, eplpi

cdr  unification of naming conventions for electron impact collisions

!pb  APR  16:  ipplds -> ipplei, pplds -> pplei
!pb  APR  16:  ipatds -> ipatei, patds -> patei, eatds -> eatei
!pb  APR  16:  ipmlds -> ipmlei, pmlds -> pmlei, emlds -> emlei
!pb  APR  16:  ipiods -> ipioei, piods -> pioei, eiods -> eioei
!pb  APR  16:  pelds -> pelei, eelds -> eelei
!pb  MAY  16:  tabds1 -> tabei1
!pb  MAY  16:  nrds -> nrei
!pb  JUL  16:  ehvds1 -> ehvei1
!dr  sept 16:  nmdsi  -> nmeii
!dr  sept 16:  nidsi  -> nieii

cdr  sept 16:  ETH (collision threshold energy) added to reaction data
cdr            RTMAX and ERTMAX added to reaction data: max. of "rate" sigma(v_rel)*v_rel
cdr            broadcast data for extrapolation from tables or fits, independent of IFIT
cdr  Nov  16:  nmds --> nmei,  nids --> niei.
cdr  Nov  16:  mxcolls --> mstor0
cdr  Jan  17:  only comments
cdr  July 17:  bug fix: dimensioning of LCUT(0:N2NDPLGS) corrected
cdr            remove NCHORD (is: NCHOR)
c    Aug. 17:  NMODE, LSMOPRO: exception wrt. MPI.  Why necessary?
c              broadcasting of CHRTLS was done twice.  removed once.
cpb  Dec. 17:  remove type SPECT_ARRAY, not needed in Fortran 2003
c    Jan. 18:  new submodule alloc_fit_form used to allocate, and initialize REACDAT(IR) 

      SUBROUTINE EIRENE_BROADCAST
cdr 
c     tbd: some text here, about logic of this code ??
c
cdr
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CESTIM
      USE EIRMOD_CREF
      USE EIRMOD_COMUSR
      USE EIRMOD_CADGEO
      USE EIRMOD_CAI
      USE EIRMOD_CCONA
      USE EIRMOD_CLOGAU
      USE EIRMOD_CINIT
      USE EIRMOD_COMSIG
      USE EIRMOD_CPOLYG
      USE EIRMOD_CGRID
      USE EIRMOD_CZT1
      USE EIRMOD_CTRCEI
      USE EIRMOD_CCOUPL
      USE EIRMOD_CGEOM
      USE EIRMOD_CSDVI
      USE EIRMOD_CSDVI_BGK
      USE EIRMOD_CSDVI_COP
      USE EIRMOD_CTETRA
      USE EIRMOD_COMPRT
      USE EIRMOD_CPES
      USE EIRMOD_COMSOU
      USE EIRMOD_CSTEP
      USE EIRMOD_COMSPL
      USE EIRMOD_CTEXT
      USE EIRMOD_CLGIN
      USE EIRMOD_COUTAU
      USE EIRMOD_COMXS
      USE EIRMOD_CTRIG
      USE EIRMOD_PHOTON
      USE EIRMOD_CFPLK
      USE EIRMOD_MPI
      IMPLICIT NONE

!      INCLUDE 'mpif.h'
      INTEGER :: IER, I, NSPS, KK, NRC, NNROT, IR, NREF, IRF, IAN, NMT,
     .           imerk
      REAL(DP) :: RHELP(3)
      INTEGER, ALLOCATABLE :: IHELP(:)
      CHARACTER, ALLOCATABLE :: CHELP(:)

      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)

      IF (MY_PE == 0) CALL EIRENE_COLLECT_PARM

      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INT_PARM,NUM_PARM,MPI_INTEGER,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)

c     ------------------------------------------------------------     c
c     for the trace ion module
!pb   CALL EIRENE_BROAD_TIM_PARMS
c     ------------------------------------------------------------     c
      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)

cdr:  LSMOPRO, NMODE:  what is special about them to require treatment as exception?  
      IF (MY_PE .NE. 0) THEN
        CALL EIRENE_DISTRIB_PARM
        CALL EIRENE_ALLOC_COMUSR(0)
        CALL MPI_BCAST (LSMOPRO,12,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (NMODE,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
        CALL EIRENE_ALLOCATE_MODULES
      Else
        CALL MPI_BCAST (LSMOPRO,12,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (NMODE,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      END IF

      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RADGEO,NADGEO,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IADGEO,MADGEO,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NLIMI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RATIO,NSTRA,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRECOM,NSTRA,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RCONA,NCONA,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (NFIRST,NTALV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NADDV,NTALV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IRESC1,NTALV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IRESC2,NTALV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFRSTW,NTALS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NADDW,NTALS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RCGM1,NCGM1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RCGM2,NCGM2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (AREAG,NLMPGS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPOINT,2*NPPART,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSTGRD,NRAD,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NGHPLS,4*N1STS*N2NDPLGS,
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NGHPOL,4*N1STS*N2NDPLGS,
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCLTAL,NRAD,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NNODES,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LDAMCEL,NRAD,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RCGRID,NCGRD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICGRID,MCGRD,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RLWMN,NLIMPS+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RLWMX,NLIMPS+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EWALL,NLIMPS+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EWBIN,NLIMPS+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TRANSP,2*NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FSHEAT,NLIMPS+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ZNML,NLIMPS+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ZNCL,NLIMPS+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RECYCF,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RECYCT,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RECPRM,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EXPPL,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EXPEL,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EXPIL,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RECYCS,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RECYCC,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (SPTPRM,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ESPUTS,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ESPUTC,NSPZ*(NLIMPS+1),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILSWCH,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILEQUI,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILTOR ,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILSIDE,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILIIN ,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILREF ,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILSPT ,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILCOL ,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILFIT ,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILCELL,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILBOX ,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILPLG ,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISPUT ,2*(NLIMPS+1),MPI_INTEGER,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NLIMII,NOPTIM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NLIMIE,NOPTIM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISWICH,6*(NLIMPS+1),
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILBLCK,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ILACLL,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (JUMLIM,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSTSI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INUMP,3*NSTS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IRPTA,3*NSTS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IRPTE,3*NSTS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISRF,NSPZ*(NLIMPS+1),
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISRT,NSPZ*(NLIMPS+1),
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISRS,NSPZ*(NLIMPS+1),
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISRC,NSPZ*(NLIMPS+1),
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INMP1I,(N1ST+1)*(N2ND+1)*(N3RD+1),
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INMP2I,(N1ST+1)*(N2ND+1)*(N3RD+1),
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INMP3I,(N1ST+1)*(N2ND+1)*(N3RD+1),
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IGFIL,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IGJUM0,NLIMPS+1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IGJUM1,(NLIMPS+1)*NLIMPB,
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IGJUM2,(NLIMPS+1)*NLIMPB,
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IGJUM3,(NOPTIM+1)*NLIMPB,
     .                MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (LLOGAU,NLOGAU,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

      IF (ALLOCATED(RCMSIG)) THEN
        CALL MPI_BCAST (RCMSIG,NCMSIG,MPI_REAL8,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (FUFFER,NCHOR*NCHEN,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (ENERGY,NCHEN,MPI_REAL8,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (ICMSIG,MCMSIG,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      END IF
      CALL MPI_BCAST (NCHORI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)      
      CALL MPI_BCAST (NCHENI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
cdr  additional output tallies added by code itself (rather than via input block 14).
      CALL MPI_BCAST (MOD_ADDV,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      IF (num_LINES > 0) THEN
        CALL EIRENE_BROAD_EMIS_LINES
      END IF

      CALL MPI_BCAST (RCMSOU,NOMSOU,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (SREC,NPLSP*(NREC+1),MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EIO,NPLSP*(NREC+1),MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EEL,NPLSP*(NREC+1),MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICMSOU,MOMSOU,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSTRAI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INGRDA,NSRFS*NSTRA*3,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INGRDE,NSRFS*NSTRA*3,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LCMSOU,LOMSOU,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

c  some array A(0:NSTRA)) that include sum over strata
      CALL MPI_BCAST (NLSYMP,NSTRAP,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NLSYMT,NSTRAP,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RCMSPL,NCMSPL,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RSPLST,MAXLEVEL*NPARTC,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICMSPL,MCMSPL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISPLST,MAXLEVEL*MPARTC,MPI_INTEGER,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LCMSPL,KCMSPL,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NLPRCS,NLIMPS+1,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (XSTOR,MSTOR1*MSTOR2,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (XSTORV,NSTORV,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ZMFPTHI,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TDGTEMX,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (TABEI1,NREI*NSTORDR,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TABRC1,NREC*NSTORDR,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TABPI3,NRPI*NSTORDR*NSTORDT,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TABCX3,NRCX*NSTORDR*NSTORDT,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TABEL3,NREL*NSTORDR*NSTORDT,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (FDLMPI,NRPI,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FDLMCX,NRCX,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FDLMEL,NREL,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (ADDPI,NRPI*NPLS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ADDCX,NRCX*NPLS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ADDEL,NREL*NPLS,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (FACRRC,NREC*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FACRPI,NRPI*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FACREL,NREL*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FACREI,NREI*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FACRCX,NRCX*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)

c  EI post collision species distribution 
      CALL MPI_BCAST (PELEI,NREI,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PATEI,NREI*NATMP,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PMLEI,NREI*NMOLP,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PIOEI,NREI*NIONP,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PPLEI,NREI*NPLSP,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (P2ND,NREI*NSPZP,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (P2NEI,NREI,MPI_REAL8,0,MPI_COMM_WORLD,ier)

c  PI post collision species distribution 
      CALL MPI_BCAST (PELPI,NRPI,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PATPI,NRPI*NATMP,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PMLPI,NRPI*NMOLP,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PIOPI,NRPI*NIONP,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PPLPI,NRPI*NPLSP,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (P2NP,NRPI*NSPZP,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (P2NPI,NRPI,MPI_REAL8,0,MPI_COMM_WORLD,ier)

c  EI post collision energetics
      CALL MPI_BCAST (EELEI1,NREI*NSTORDR,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EHVEI1,NREI*NSTORDR,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
c  RC post collision energetics
      CALL MPI_BCAST (EELRC1,NREC*NSTORDR,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
c  PI post collision energetics
      CALL MPI_BCAST (EELPI1,NRPI*NSTORDR,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EHVPI3,NRPI*NSTORDR*NSTORDT,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EPLPI3,NRPI*NSTORDR*NSTORDT,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
c  CX post collision energetics
      CALL MPI_BCAST (EPLCX3,NRCX*NSTORDR*NSTORDT,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
c  EL post collision energetics
      CALL MPI_BCAST (EPLEL3,NREL*NSTORDR*NSTORDT,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (EATEI,NREI*NATMP*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EMLEI,NREI*NMOLP*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EIOEI,NREI*NIONP*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EPLEI,NREI*NPLSP*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (EATPI,NRPI*NATMP*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EMLPI,NRPI*NMOLP*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EIOPI,NRPI*NIONP*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EPLPI,NRPI*NPLSP*2,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (MODCOL,35*MSTOR0,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (IESTCX,3*NRCX,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IESTEL,3*NREL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IESTPI,3*NRPI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IESTEI,3*NREI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (NRPII,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NREII,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRCXI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRELI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRRCI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRBGI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NAEII,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMEII,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIEII,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NACXI,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMCXI,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NICXI,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NAELI,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMELI,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIELI,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NAPII,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMPII,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIPII,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPRCI,NPLS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NAEIIM,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMEIIM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIEIIM,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NACXIM,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMCXIM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NICXIM,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NAELIM,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMELIM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIELIM,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NAPIIM,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMPIIM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIPIIM,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPRCIM,NPLS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPBGKA,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPBGKM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPBGKI,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPBGKP,2*NPLS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NATPRC,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMLPRC,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIOPRC,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPLPRC,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPHPRC,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NATPRC_2,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMLPRC_2,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIOPRC_2,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPLPRC_2,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPHPRC_2,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (N1STX,3*NRCX,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (N2NDX,3*NRCX,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSEACX,5*NATM*NPLS,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSEMCX,5*NMOL*NPLS,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSEICX,5*NION*NPLS,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSEAEL,5*NATM*NPLS,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSEMEL,5*NMOL*NPLS,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSEIEL,5*NION*NPLS,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSEPRC,5*NREC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NREACX,NRCX,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NREAPI,NRPI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NREAEL,NREL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NREAEI,NREI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NREARC,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (JEREAEI,NREI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (JEREARC,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NELREI,NREI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (JELREI,NREI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NREAHV,NREI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NELREL,NREL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NELRRC,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (JELRRC,NREC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NELRPI,NRPI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (JELRPI,NRPI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NELRCX,NRCX,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NELROT,NROT,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NREAOT,NROT,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRHVPI,NRPI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPATEI,NREI*NATMP,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPMLEI,NREI*NMOLP,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPIOEI,NREI*NIONP,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPPLEI,NREI*NPLSP,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPATPI,NRPI*NATMP,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPMLPI,NRPI*NMOLP,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPIOPI,NRPI*NIONP,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPPLPI,NRPI*NPLSP,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGACX,NATMP*(NRCX+1)*2,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGMCX,NMOLP*(NRCX+1)*2,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGICX,NIONP*(NRCX+1)*2,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGAEI,NATMP*(NREI+1),MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGMEI,NMOLP*(NREI+1),MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGIEI,NIONP*(NREI+1),MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGAEL,NATMP*(NREL+1)*2,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGMEL,NMOLP*(NREL+1)*2,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGIEL,NIONP*(NREL+1)*2,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGPRC,NPLSP*(NREC+1),MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGAPI,NATMP*(NRPI+1)*2,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGMPI,NMOLP*(NRPI+1)*2,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGIPI,NIONP*(NRPI+1)*2,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)


cdr   old data structure CREAC has been replaced by more general data structure REACDAT


      DO IR=-11, NREAC
c interaction potential, differential cross sections, etc.
        CALL MPI_BCAST (REACDAT(IR)%LPOT,1,MPI_LOGICAL,
     .                  0,MPI_COMM_WORLD,ier)
c total cross sections
        CALL MPI_BCAST (REACDAT(IR)%LCRS,1,MPI_LOGICAL,
     .                  0,MPI_COMM_WORLD,ier)
c reaction rate coefficients
        CALL MPI_BCAST (REACDAT(IR)%LRTC,1,MPI_LOGICAL,
     .                  0,MPI_COMM_WORLD,ier)
c momentum weighted rate coefficients
        CALL MPI_BCAST (REACDAT(IR)%LRTCMW,1,MPI_LOGICAL,
     .                  0,MPI_COMM_WORLD,ier)
c energy weighted rate coefficients
        CALL MPI_BCAST (REACDAT(IR)%LRTCEW,1,MPI_LOGICAL,
     .                  0,MPI_COMM_WORLD,ier)
c other data, such as population coefficients, CR-density ratios,....
        CALL MPI_BCAST (REACDAT(IR)%LOTH,1,MPI_LOGICAL,
     .                  0,MPI_COMM_WORLD,ier)
c ??
        CALL MPI_BCAST (REACDAT(IR)%LPHR,1,MPI_LOGICAL,
     .                  0,MPI_COMM_WORLD,ier)
c ??
        CALL MPI_BCAST (REACDAT(IR)%NOSEC,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)

c  reaction threshold, eV
        CALL MPI_BCAST (REACDAT(IR)%ETH,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
c  max of sigma * v  cm**3/s
        CALL MPI_BCAST (REACDAT(IR)%RTMAX,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
c  collision energy, at which rtmax is taken, eV
        CALL MPI_BCAST (REACDAT(IR)%ERTMAX,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)

c  data for interaction potential
        IF (REACDAT(IR)%LPOT) THEN
          IF (MY_PE .NE. 0) THEN
            IF (.NOT.ASSOCIATED(REACDAT(IR)%POT)) THEN
              CALL EIRENE_ALLOC_FIT_FORM (REACDAT(IR)%POT)
            END IF
          END IF
          CALL EIRENE_BROAD_FIT_FORM(REACDAT(IR)%POT)
        END IF
c  data for cross sections, cm**2
        IF (REACDAT(IR)%LCRS) THEN
          IF (MY_PE .NE. 0) THEN
            IF (.NOT.ASSOCIATED(REACDAT(IR)%CRS)) THEN
              CALL EIRENE_ALLOC_FIT_FORM (REACDAT(IR)%CRS)
            END IF
          END IF
          CALL EIRENE_BROAD_FIT_FORM(REACDAT(IR)%CRS)
        END IF
        IF (REACDAT(IR)%LRTC) THEN
c  data for rate coefficients, cm**3/s
          IF (MY_PE .NE. 0) THEN
            IF (.NOT.ASSOCIATED(REACDAT(IR)%RTC)) THEN
              CALL EIRENE_ALLOC_FIT_FORM (REACDAT(IR)%RTC)
            END IF
          END IF
          CALL EIRENE_BROAD_FIT_FORM(REACDAT(IR)%RTC)
        END IF
c  data for momentum weighted rate coefficients  g cm/s cm**3/s
        IF (REACDAT(IR)%LRTCMW) THEN
          IF (MY_PE .NE. 0) THEN
            IF (.NOT.ASSOCIATED(REACDAT(IR)%RTCMW)) THEN
              CALL EIRENE_ALLOC_FIT_FORM (REACDAT(IR)%RTCMW)
            END IF
          END IF
          CALL EIRENE_BROAD_FIT_FORM(REACDAT(IR)%RTCMW)
        END IF
c  data for energy weighted rate coefficients,  eV cm**3-s
        IF (REACDAT(IR)%LRTCEW) THEN
          IF (MY_PE .NE. 0) THEN
            IF (.NOT.ASSOCIATED(REACDAT(IR)%RTCEW)) THEN
              CALL EIRENE_ALLOC_FIT_FORM (REACDAT(IR)%RTCEW)
            END IF
          END IF
          CALL EIRENE_BROAD_FIT_FORM(REACDAT(IR)%RTCEW)
        END IF
c  other data, such as CR population coefficients
        IF (REACDAT(IR)%LOTH) THEN
          IF (MY_PE .NE. 0) THEN
            IF (.NOT.ASSOCIATED(REACDAT(IR)%OTH)) THEN
              CALL EIRENE_ALLOC_FIT_FORM (REACDAT(IR)%OTH)
            END IF
          END IF
          CALL EIRENE_BROAD_FIT_FORM(REACDAT(IR)%OTH)
        END IF
c  data for photon line transport
        IF (REACDAT(IR)%LPHR) THEN
          IF (MY_PE .NE. 0) THEN
            IF (.NOT.ASSOCIATED(REACDAT(IR)%PHR)) THEN
              CALL EIRENE_ALLOC_FIT_FORM (REACDAT(IR)%PHR)
            END IF
          END IF
          CALL EIRENE_BROAD_FIT_FORM(REACDAT(IR)%PHR)
        END IF
      END DO

      CALL MPI_BCAST (FACREA,(NREAC+12)*2,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DELPOT,NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FREACA,NATM*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FREACM,NMOL*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FREACI,NION*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FREACP,NPLS*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FREACPH,NPHOT*NREAC,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FDPOTA,NATM*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FDPOTM,NMOL*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FDPOTI,NION*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FDPOTP,NPLS*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FDPOTPH,NPHOT*NREAC,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EELECA,NATM*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EELECM,NMOL*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EELECI,NION*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EELECP,NPLS*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EELECPH,NPHOT*NREAC,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EBULKA,NATM*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EBULKM,NMOL*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EBULKI,NION*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EBULKP,NPLS*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EBULKPH,NPHOT*NREAC,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ESCD1A,NATM*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ESCD1M,NMOL*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ESCD1I,NION*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ESCD1P,NPLS*NREAC,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ESCD1PH,NPHOT*NREAC,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (ISWR,NREAC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (MODCLF,NREAC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (MASSP,NREAC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (MASST,NREAC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IFTFLG,6*(NREAC+12),MPI_INTEGER,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRCP,NPLS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRCA,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRCM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRCI,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRCPH,NPHOT,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IREACA,NATM*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IREACM,NMOL*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IREACI,NION*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IREACP,NPLS*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IREACPH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBULKA,NATM*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBULKM,NMOL*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBULKI,NION*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBULKP,NPLS*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBULKPH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD1A,NATM*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD1M,NMOL*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD1I,NION*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD1P,NPLS*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD1PH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD2A,NATM*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD2M,NMOL*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD2I,NION*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD2P,NPLS*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD2PH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD3A,NATM*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD3M,NMOL*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD3I,NION*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD3P,NPLS*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD3PH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD4A,NATM*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD4M,NMOL*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD4I,NION*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD4P,NPLS*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCD4PH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCDEA,NATM*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCDEM,NMOL*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCDEI,NION*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCDEP,NPLS*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISCDEPH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IESTMA,NATM*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IESTMM,NMOL*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IESTMI,NION*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBGKPH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IESTMPH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBGKA,NATM*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBGKM,NMOL*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBGKI,NION*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBGKPH,NPHOT*NREAC,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NREACI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (NADDI,NTALV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFRSTI,NTALV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFSTVI,NTALV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NDDWI,NTALS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFRTWI,NTALS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFSTWI,NTALS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFSTPI,NTALI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RCPLYG,NCPLYG,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RCPLY2,NCPLY2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICPLYG,MCPLYG,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
cdr dimensioning of LCUT array corrected:
      CALL MPI_BCAST (LCUT,N2NDPLGS+1,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (ISDVI,MSDVI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IIHC,2*NCV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IGHC,2*NCV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (NBGVI_STAT,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (NCPVI_STAT,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (FLSTEP,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ELSTEP,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FLTOT,(NSPZ+1)*NSTEP,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ELTOT,(NSPZ+1)*NSTEP,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VF,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VE,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (QUOT,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ADD,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (QUOTI,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ADDIV,NSTPP1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TESTEP,NSTPP2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TISTEP,NPLSTI*NSTEP*NGITT,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RRSTEP,NSTPP2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VXSTEP,NPLSV*NSTEP*NGITT,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VYSTEP,NPLSV*NSTEP*NGITT,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VZSTEP,NPLSV*NSTEP*NGITT,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DISTEP,NSTPP3,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FESTEP,NSTPP2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (SHSTEP,NSTPP2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (FISTEP,NSTPP3,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (MCSTEP,NSTPP3,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VPSTEP,NPLSV*NSTPP2,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IRSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IPSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ITSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IASTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IGSTEP,NSTPP2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISTUF,NSTEP,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSMAX,NSTEP,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPSTI,NSTEP,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPSTE,NSTEP,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RCTET1,NCTET1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RCTET2,NCTET2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICTET1,MCTET1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICTET2,MCTET2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (TXTSFL,72*NLIMPS,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTTAL,72*N1MX*NTALV,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTPLS,72*N1MX*NTALI,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTSOU,72*NSTRA,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTSIG,72*NCHOR,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTTLW,72*N2MX*NTALS,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (CHRTAL,72*NALV,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (CHRTLS,72*NALS,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTRUN,72,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTSPC,24*N1MX*NTALV,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTUNT,24*N1MX*NTALV,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTPSP,24*N1MX*NTALI,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTPUN,24*N1MX*NTALI,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTUNW,24*N2MX*NTALS,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TXTSPW,24*N2MX*NTALS,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TEXTLA,24*5,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TEXTLS,24*3,MPI_CHARACTER,
     .                0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (LTRCEI,LCTRC,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TRCSRC,NSTRA+1,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ITRCEI,MCTRC,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
!pb   CALL MPI_BCAST (NSPEZV,2*NSPEZV_DIM,MPI_INTEGER,0,
!pb  .                MPI_COMM_WORLD,ier)
!pb   CALL MPI_BCAST (NSPEZS,2*NLIMPS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPEZV,2*NVLPR,MPI_INTEGER,0,
     .                MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPEZS,2*NSRPR,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      IF (MY_PE .NE. 0) THEN
         IF (SIZE(XTRIAN) .NE. NKNOTS) THEN
            call EIRENE_dealloc_ctrig
            call EIRENE_alloc_ctrig
         END IF
      END IF

      CALL MPI_BCAST (XTRIAN,NKNOTS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (YTRIAN,NKNOTS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VTRIX,3*NTRIS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VTRIY,3*NTRIS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PTRIX,3*NTRIS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PTRIY,3*NTRIS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NECKE,3*NTRIS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCHBAR,3*NTRIS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSEITE,3*NTRIS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INMTI,3*NTRIS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INSPAT,3*NTRIS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INMTINSS,3*NTRIS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IREVERS,3*NTRIS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NRKNOT,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NTRII,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (INMTI3,NTRIS*N3RD,MPI_INTEGER,0,
     .                MPI_COMM_WORLD,ier)

!+++++++++++ In this block dynamical structures are proceeded with care
!+++++++++++ IYS 27.02.2015

      DO I = 1, NLIMPS
        NMT = SURF_TRIAN(I)%NUMTR
        CALL MPI_BCAST (NMT,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
        IF (NMT > 0) THEN
          IF (MY_PE /= 0) THEN
            SURF_TRIAN(I)%NUMTR = NMT
            IF (ASSOCIATED(SURF_TRIAN(I)%ITRIAS)) THEN! IYS
              IF (NMT.ne.UBOUND(SURF_TRIAN(I)%ITRIAS,1)) THEN ! IYS
                DEALLOCATE (SURF_TRIAN(I)%ITRIAS)  ! IYS
                NULLIFY (SURF_TRIAN(I)%ITRIAS)      ! IYS
                ALLOCATE (SURF_TRIAN(I)%ITRIAS(NMT)) ! IYS
              ENDIF
            ELSE  ! IYS
              ALLOCATE (SURF_TRIAN(I)%ITRIAS(NMT))
            ENDIF
            IF (ASSOCIATED(SURF_TRIAN(I)%ITRISI)) THEN! IYS
              IF (NMT.ne.UBOUND(SURF_TRIAN(I)%ITRISI,1)) THEN ! IYS
                DEALLOCATE (SURF_TRIAN(I)%ITRISI)  ! IYS
                NULLIFY (SURF_TRIAN(I)%ITRISI)      ! IYS
                ALLOCATE (SURF_TRIAN(I)%ITRISI(NMT)) ! IYS
              ENDIF
            ELSE  ! IYS
              ALLOCATE (SURF_TRIAN(I)%ITRISI(NMT))
            ENDIF
            IF (ASSOCIATED(SURF_TRIAN(I)%BGLT)) THEN! IYS
              IF (NMT+1.ne.UBOUND(SURF_TRIAN(I)%BGLT,1)) THEN ! IYS
                DEALLOCATE (SURF_TRIAN(I)%BGLT)  ! IYS
                NULLIFY (SURF_TRIAN(I)%BGLT)      ! IYS
                ALLOCATE (SURF_TRIAN(I)%BGLT(NMT+1)) ! IYS
              ENDIF
            ELSE  ! IYS
              ALLOCATE (SURF_TRIAN(I)%BGLT(NMT+1))
            END IF
          END IF
          CALL MPI_BCAST (SURF_TRIAN(I)%ITRIAS,NMT,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (SURF_TRIAN(I)%ITRISI,NMT,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (SURF_TRIAN(I)%BGLT,NMT+1,
     .                    MPI_REAL8,0,MPI_COMM_WORLD,ier)
        END IF
      END DO
!+++++++++++ IYS 27.02.2015
!+++++++++++ In this block dynamical structures are proceeded with care



      CALL MPI_BCAST (RCZT1,NZT1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RCZT2,NZT2,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ZT1,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ZRG,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RCINIT,NCINIT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICINIT,MCINIT,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LCNIT,LCINIT,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (CDENMODEL,10*NPLS,MPI_CHARACTER,0,
     .                MPI_COMM_WORLD,ier)

      DO IPLS=1,NPLS

        IF (VERIFY(CDENMODEL(IPLS),' ') == 0) CYCLE

        IF (MY_PE == 0) NREF = TDMPAR(IPLS)%TDM%NRE
        CALL MPI_BCAST(NREF,1,MPI_INTEGER,0,
     .                 MPI_COMM_WORLD,ier)

        ALLOCATE (IHELP(3*NREF))
        ALLOCATE (CHELP(1:24*NREF))

        IF (MY_PE == 0) THEN
          RHELP(1) = TDMPAR(IPLS)%TDM%G_BOLTZ
          RHELP(2) = TDMPAR(IPLS)%TDM%DELTAE
          RHELP(3) = TDMPAR(IPLS)%TDM%A_CORONA
          IHELP(1:NREF) = TDMPAR(IPLS)%TDM%ISP(1:NREF)
          IHELP(1+NREF:2*NREF) = TDMPAR(IPLS)%TDM%ITP(1:NREF)
          IHELP(1+2*NREF:3*NREF) = TDMPAR(IPLS)%TDM%ISTR(1:NREF)
          IAN = 0
          DO IRF=1,NREF
            CHELP(IAN+1:IAN+8) = TRANSFER(TDMPAR(IPLS)%TDM%FNAME(IRF),
     .                                    CHELP)
            CHELP(IAN+9:IAN+12) = TRANSFER(TDMPAR(IPLS)%TDM%H2(IRF),
     .                                    CHELP)
            CHELP(IAN+13:IAN+21) = TRANSFER(
     .                        TDMPAR(IPLS)%TDM%REACTION(IRF),CHELP)
            CHELP(IAN+22:IAN+24) = TRANSFER(TDMPAR(IPLS)%TDM%CR(IRF),
     .                                    CHELP)
            IAN = IAN + 24
          END DO
        END IF

        CALL MPI_BCAST(RHELP,3,MPI_REAL8,0,
     .                MPI_COMM_WORLD,ier)
        CALL MPI_BCAST(IHELP,3*NREF,MPI_INTEGER,0,
     .                MPI_COMM_WORLD,ier)
        CALL MPI_BCAST(CHELP,24*NREF,MPI_CHARACTER,0,
     .                MPI_COMM_WORLD,ier)

        IF (MY_PE > 0) THEN
csw
!pb          if(.not.allocated(tdmpar)) then
          if(.not.associated(tdmpar(ipls)%tdm)) then
csw
            ALLOCATE (TDMPAR(IPLS)%TDM)
            ALLOCATE (TDMPAR(IPLS)%TDM%ISP(NREF))
            ALLOCATE (TDMPAR(IPLS)%TDM%ITP(NREF))
            ALLOCATE (TDMPAR(IPLS)%TDM%ISTR(NREF))
            ALLOCATE (TDMPAR(IPLS)%TDM%FNAME(NREF))
            ALLOCATE (TDMPAR(IPLS)%TDM%H2(NREF))
            ALLOCATE (TDMPAR(IPLS)%TDM%REACTION(NREF))
            ALLOCATE (TDMPAR(IPLS)%TDM%CR(NREF))
csw
          endif
csw
          TDMPAR(IPLS)%TDM%NRE = NREF
          TDMPAR(IPLS)%TDM%G_BOLTZ = RHELP(1)
          TDMPAR(IPLS)%TDM%DELTAE = RHELP(2)
          TDMPAR(IPLS)%TDM%A_CORONA = RHELP(3)
          TDMPAR(IPLS)%TDM%ISP(1:NREF) = IHELP(1:NREF)
          TDMPAR(IPLS)%TDM%ITP(1:NREF) = IHELP(1+NREF:2*NREF)
          TDMPAR(IPLS)%TDM%ISTR(1:NREF) = IHELP(1+2*NREF:3*NREF)
          IAN = 0
          DO IRF=1,NREF
            TDMPAR(IPLS)%TDM%FNAME(IRF) = TRANSFER(CHELP(IAN+1:IAN+8),
     .            TDMPAR(IPLS)%TDM%FNAME(IRF))
            TDMPAR(IPLS)%TDM%H2(IRF) = TRANSFER(CHELP(IAN+9:IAN+12),
     .            TDMPAR(IPLS)%TDM%H2(IRF))
            TDMPAR(IPLS)%TDM%REACTION(IRF) =
     .            TRANSFER(CHELP(IAN+13:IAN+21),
     .            TDMPAR(IPLS)%TDM%REACTION(IRF))
            TDMPAR(IPLS)%TDM%CR(IRF) = TRANSFER(CHELP(IAN+22:IAN+24),
     .            TDMPAR(IPLS)%TDM%CR(IRF))
            IAN = IAN + 24
          END DO
        END IF

        DEALLOCATE (IHELP)
        DEALLOCATE (CHELP)

      END DO
      CALL MPI_BCAST(DBFNAME,100*NDBNAMES,MPI_CHARACTER,0,
     .               MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (TEIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TIIN,NPLSTI*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DEIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DIIN,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VXIN,NPLSV*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VYIN,NPLSV*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VZIN,NPLSV*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (BXIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (BYIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (BZIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (BFIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ADIN,NAIN*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VOL,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (WGHT,NSPZMC*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EXIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EYIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EZIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EFIN,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)


      CALL MPI_BCAST (TEINL,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TIINL,NPLSTI*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (EDRIFT,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DEINL,NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DIINL,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (BVIN,NPLSV*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (PARMOM,NPLS*NRAD,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (FLXOUT,NLMPGS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (SAREA,NLMPGS,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RMASSI,NION,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RMASSA,NATM,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RMASSM,NMOL,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RMASSP,NPLS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DIOD,NION,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DATD,NATM,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DMLD,NMOL,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DPLD,NPLS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DION,NION,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DATM,NATM,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DMOL,NMOL,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DPLS,NPLS,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DPHOT,NPHOT,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TVAC,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (DVAC,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (VVAC,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ALLOC,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (CORNER_PROFILES,SIZE(CORNER_PROFILES),
     .                MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TEDTEDX,NRTAL,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TEDTEDY,NRTAL,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (TEDTEDZ,NRTAL,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (TEXTS,8*NSPZ,MPI_CHARACTER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPA,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NATMI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NATMIM,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPAM,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMOLI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMOLIM,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPAMI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIONI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NIONIM,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPTOT,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPLSI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPLSIM,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPH,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPHOTI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPHOTIM,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSNVI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCPVI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NADVI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NBGVI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NALVI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCLVI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NADSI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NALSI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NAINI,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NBITS,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMASSA,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCHARA,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFOLA,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NGENA,NATM,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMASSM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCHARM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFOLM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NGENM,NMOL,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMASSP,NPLS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCHARP,NPLS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCHRGP,NPLS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NMASSI,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCHARI,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NCHRGI,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFOLI,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NGENI,NION,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFOLPH,NPHOT,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NGENPH,NPHOT,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPRT,NSPZ,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISPEZ,6*(1+NPHOTP)*(NATMP+1)*(NMOLP+1)*(NIONP+1)*
     .                      (NPLSP+1),MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISPEZI,6*NSPZ,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (MPLSTI,NPLS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (MPLSV,NPLS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IADVE,NADV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IADVS,NADV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IADVT,NADV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IADRC,NADV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICLVE,NCLV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICLVS,NCLV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICLVT,NCLV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICLRC,NCLV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISNVE,NSNV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISNVS,NSNV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISNVT,NSNV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ISNRC,NSNV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICPVE,NCPV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICPVS,NCPV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICPVT,NCPV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ICPRC,NCPV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBGVE,NBGV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBGVS,NBGV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBGVT,NBGV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IBGRC,NBGV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IADSE,NADS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IADSS,NADS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IADST,NADS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IADSC,NADS,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFRSTP,NTALI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NADDP,NTALI,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPAN,NTALV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NSPEN,NTALV,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LGVAC,NRAD*(NPLS+2),MPI_LOGICAL,0,MPI_COMM_WORLD,
     .                ier)
      CALL MPI_BCAST (LGDFT,NRAD,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPRLL,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
cpb   CALL MPI_BCAST (NMODE,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)  ! exception made for this variable
      CALL MPI_BCAST (NTCPU,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFILE,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFILEN,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFILEM,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFILEL,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFILEK,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NFILEJ,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NITER,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (IITER,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NTIME,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (ITIMV,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (NLIDENT,1,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

      IF (NMODE .NE. 0) THEN
         CALL EIRENE_ALLOC_CCOUPL(1)
         CALL EIRENE_ALLOC_CCOUPL(2)
      END IF

      IF (ALLOCATED(RCCPL)) THEN
        CALL MPI_BCAST (RCCPL,NCOUPL,MPI_REAL8,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (ICCPL1,MCOUPL1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (ICCPL2,MCOUPL2,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (LCCPL,LCOUPL,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      END IF
      CALL MPI_BCAST (B2BREM,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (B2RAD,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (B2QIE,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (B2VDP,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
      IF (ALLOCATED(NAINS)) THEN
        CALL MPI_BCAST (NAINS,NAIN,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (NAINT,NAIN,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      END IF

      CALL EIRENE_BROAD_COMNNL

      CALL EIRENE_BROAD_USR

      CALL MPI_BCAST (LIVTALV,NTALV,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LIVTALS,NTALS,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LMISTALV,NTALV,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LMISTALS,NTALS,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LEA,1,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LEM,1,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LEIO,1,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (LEPH,1,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

      IF (MY_PE .NE. 0) THEN
        CALL EIRENE_ALLOC_CESTIM(2)
        CALL EIRENE_ASSOCIATE_CESTIM
      END IF

      IF (NADSPC > 0) THEN
         IF (MY_PE .NE. 0) THEN
            IF (.NOT.ALLOCATED(ESTIML)) THEN
              ALLOCATE(ESTIML(NADSPC))
              ALLOCATE(SMESTL(NADSPC))
            END IF
         END IF
         DO I=1,NADSPC
           CALL MPI_BARRIER(MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPCMIN,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPCMAX,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPCDEL,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPCDELI,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%ESP_MIN,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%ESP_MAX,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%ESP_00,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPC_XPLT,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPC_YPLT,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPC_SAME,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPCVX,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPCVY,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%SPCVZ,1,MPI_REAL8,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%NSPC,1,MPI_INTEGER,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%ISPCTYP,1,MPI_INTEGER,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%ISPCSRF,1,MPI_INTEGER,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%IPRTYP,1,MPI_INTEGER,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%IPRSP,1,MPI_INTEGER,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%IMETSP,1,MPI_INTEGER,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%ISRFCLL,1,MPI_INTEGER,0,
     .                     MPI_COMM_WORLD,ier)
           CALL MPI_BCAST (ESTIML(I)%IDIREC,1,MPI_INTEGER,0,
     .                     MPI_COMM_WORLD,ier)
           IF (MY_PE .NE. 0) THEN
             NSPS = ESTIML(I)%NSPC
!pb             write (0,*) ' smestl, my_pe, imerk, nsps ',
!pb     .                     my_pe, imerk, nsps
             IF (.NOT.ASSOCIATED(ESTIML(I)%SPC)) THEN
               ALLOCATE(ESTIML(I)%SPC(0:NSPS+1))
               ALLOCATE(ESTIML(I)%SDV(0:NSPS+1))
               ALLOCATE(ESTIML(I)%SGM(0:NSPS+1))
               ALLOCATE(ESTIML(I)%STV(0:NSPS+1))
               ALLOCATE(ESTIML(I)%GG(0:NSPS+1))
C  variances for sum over strata
               ALLOCATE(SMESTL(I)%SPC(0:NSPS+1))
               ALLOCATE(SMESTL(I)%SDV(0:NSPS+1))
               ALLOCATE(SMESTL(I)%SGM(0:NSPS+1))
               ALLOCATE(SMESTL(I)%STV(0:NSPS+1))
               ALLOCATE(SMESTL(I)%GG(0:NSPS+1))
             END IF
             ESTIML(I)%SPC = 0._DP
             SMESTL(I) = ESTIML(I)
           END IF
         END DO
      ELSE
        IF (MY_PE .NE. 0) THEN
          IF (.NOT.ALLOCATED(ESTIML)) THEN
            ALLOCATE(ESTIML(1))
          END IF
        END IF
      END IF

      IF (NPHOTI > 0) THEN
        nnrot=0
        do iatm=1,natmi
          if(nrca(iatm) > 0) then
            do nrc=1,nrca(iatm)
              kk=ireaca(iatm,nrc)
              if(iswr(kk) == 7) then
                nNROT=nNROT+1
              endif
            enddo
          endif
        enddo
!pb  out! not needed for the time being
!pb        IF (MY_PE .NE. 0) call PH_ALLOC_XSECTA(nnrot)
        IF (NNROT > 0) THEN
          CALL MPI_BCAST (PHV_LGAOT,(NATM+1)*(NNROT+1)*6,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (PHV_NAOTI,NATM,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (PHV_IESTOTAT,(NATM+1)*NNROT*3,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (PHV_N1STOTAT,(NATM+1)*NNROT*3,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (PHV_N2NDOTAT,(NATM+1)*NNROT*3,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
        END IF


        nnrot=0
        do iphot=1,nphoti
          if(nrcph(iphot) > 0) then
            do nrc=1,nrcph(iphot)
              kk=ireacph(iphot,nrc)
              if(iswr(kk) == 7) then
                nNROT=nNROT+1
              endif
            enddo
          endif
        enddo
        IF (MY_PE .NE. 0) call EIRENE_PH_ALLOC_XSECTPH(nnrot)
        IF (NNROT > 0) THEN
          CALL MPI_BCAST (PHV_LGPHOT,(NPHOT+1)*(NNROT+1)*6,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (PHV_NPHOTI,NPHOT,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (PHV_IESTOTPH,(NPHOT+1)*NNROT*3,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (PHV_N1STOTPH,(NPHOT+1)*NNROT*3,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (PHV_N2NDOTPH,(NPHOT+1)*NNROT*3,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
        END IF
        CALL MPI_BCAST (HPCL,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (CLIGHT,1,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      END IF

c     distribute seppis arrays all over the world
!      call eirene_broadcast_tim()
c	
      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)

cOS   now call the octree-builder to build an octree on every node except
c     on the "root" node, where this is already done via timea0 after input
      IF (MY_PE .NE. 0) THEN
        CALL EIRENE_TIMEA0_OC()
      END IF

      RETURN


      CONTAINS

!++++++ This is a new version of SUBROUTINE EIRENE_BROAD_FIT_FORM,
!++++++ where dynamical data structures are proceeded with care
!++++++ IYS 27.02.2015

      SUBROUTINE EIRENE_BROAD_FIT_FORM (RP)

      IMPLICIT NONE
      TYPE(FIT_FORMS), POINTER :: RP
      INTEGER :: IER, ND, ND2

C.....................................................................
cdr broadcast A&M data, general for a process , independent of data structure RP%IFIT
      CALL MPI_BCAST (RP%IFIT,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (RP%JFEX1MN,1,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%JFEX1MX,1,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%JFEX2MN,1,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%JFEX2MX,1,MPI_INTEGER,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%RC1MIN,1,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%RC1MAX,1,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%RC2MIN,1,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%RC2MAX,1,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%FP1L,3,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%FP1R,3,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%FP2B,3,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (RP%FP2T,3,MPI_REAL8,
     .                0,MPI_COMM_WORLD,ier)

C.....................................................................
      IF (RP%IFIT < 0) THEN
C DATA FOR PHOTONIC LINE SHAPE AND LINE TRANSPORT
        IF (MY_PE .NE. 0) THEN
          IF (.NOT.ASSOCIATED(RP%LINE)) ALLOCATE (RP%LINE)  ! IYS
        ENDIF

        CALL MPI_BCAST (RP%LINE%E0,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%E1,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%AIK,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%G1,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%G2,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%C2,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%C3,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%C4,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%C6,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%B12,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%B21,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%C6A,12,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%IGND,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%IRCART,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%IPROFILETYPE,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%IFREMD,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%NRJPRT,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%IMESS,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%IPLSC6,12,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%REACNAME,50,MPI_CHARACTER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%LINE%KENN,24,MPI_CHARACTER,
     .                  0,MPI_COMM_WORLD,ier)

C.....................................................................
      ELSE IF (1<= RP%IFIT.AND.RP%IFIT <= 2) THEN
C  POLYNOMIAL FIT, either 1D  (RP%IFIT=1),
C                  or     2D  (RP%IFIT=2)
        IF (MY_PE == 0) THEN
          ND = UBOUND(RP%POLY%DBLPOL,1)
          ND2 = UBOUND(RP%POLY%DBLPOL,2)
        END IF

        CALL MPI_BCAST (ND,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (ND2,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)

        IF (MY_PE .NE. 0) THEN
          IF (associated(RP%POLY)) THEN ! IYS 27.02.2015
            IF (associated(RP%POLY%DBLPOL)) THEN
              IF (ND.ne.UBOUND(RP%POLY%DBLPOL,1) .and.
     #             ND2.ne.UBOUND(RP%POLY%DBLPOL,2)) THEN
                DEALLOCATE(RP%POLY%DBLPOL)
                NULLIFY(RP%POLY%DBLPOL)
                ALLOCATE (RP%POLY%DBLPOL(ND,ND2))
              ELSE
              ENDIF
            ELSE
              ALLOCATE (RP%POLY%DBLPOL(ND,ND2))
            ENDIF
          ELSE
            ALLOCATE (RP%POLY)
            ALLOCATE (RP%POLY%DBLPOL(ND,ND2))
          END IF
        END IF

        CALL MPI_BCAST (RP%POLY%DBLPOL,ND*ND2,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)

C.....................................................................
      ELSE IF (RP%IFIT == 3) THEN
! 2D TABLES, E.G. ADAS DATA
        IF (MY_PE .NE. 0) THEN
!pb          IF(.NOT. ASSOCIATED(RP%ADAS)) ALLOCATE (RP%ADAS)  ! IYS
!pb  NULLIFY NOT YET ALLOCATED POINTER ARRAYS
          IF(.NOT. ASSOCIATED(RP%ADAS)) THEN
             ALLOCATE (RP%ADAS) ! IYS
             NULLIFY(RP%ADAS%DENS)
             NULLIFY(RP%ADAS%TEMP)
             NULLIFY(RP%ADAS%DDE)
             NULLIFY(RP%ADAS%DTE)
             NULLIFY(RP%ADAS%TAB2D)
          END IF
        END IF

        CALL MPI_BCAST (RP%ADAS%NDENS,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%ADAS%NTEMP,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)

        IF (MY_PE .NE. 0) THEN
          IF (ASSOCIATED(RP%ADAS%DENS)) THEN
            IF (RP%ADAS%NDENS.ne.UBOUND(RP%ADAS%DENS,1)) THEN
               DEALLOCATE (RP%ADAS%DENS)
               NULLIFY (RP%ADAS%DENS)
               ALLOCATE (RP%ADAS%DENS(RP%ADAS%NDENS))
            ENDIF
          ELSE
            ALLOCATE (RP%ADAS%DENS(RP%ADAS%NDENS))
          ENDIF
          IF (ASSOCIATED(RP%ADAS%TEMP)) THEN
            IF (RP%ADAS%NTEMP.ne.UBOUND(RP%ADAS%TEMP,1)) THEN
               DEALLOCATE (RP%ADAS%TEMP)
               NULLIFY (RP%ADAS%TEMP)
               ALLOCATE (RP%ADAS%TEMP(RP%ADAS%NTEMP))
            ENDIF
          ELSE
            ALLOCATE (RP%ADAS%TEMP(RP%ADAS%NTEMP))
          ENDIF
          IF (ASSOCIATED(RP%ADAS%DDE)) THEN
            IF (RP%ADAS%NDENS.ne.UBOUND(RP%ADAS%DDE,1)) THEN
               DEALLOCATE (RP%ADAS%DDE)
               NULLIFY (RP%ADAS%DDE)
               ALLOCATE (RP%ADAS%DDE(RP%ADAS%NDENS))
            ENDIF
          ELSE
            ALLOCATE (RP%ADAS%DDE(RP%ADAS%NDENS))
          ENDIF
          IF (ASSOCIATED(RP%ADAS%DTE)) THEN
            IF (RP%ADAS%NTEMP.ne.UBOUND(RP%ADAS%DTE,1)) THEN
               DEALLOCATE (RP%ADAS%DTE)
               NULLIFY (RP%ADAS%DTE)
               ALLOCATE (RP%ADAS%DTE(RP%ADAS%NTEMP))
            ENDIF
          ELSE
            ALLOCATE (RP%ADAS%DTE(RP%ADAS%NTEMP))
          ENDIF
          IF (ASSOCIATED(RP%ADAS%TAB2D)) THEN
            IF ((RP%ADAS%NTEMP.ne.UBOUND(RP%ADAS%TAB2D,1)) .or.
     #         (RP%ADAS%NDENS.ne.UBOUND(RP%ADAS%TAB2D,2))) THEN
              DEALLOCATE (RP%ADAS%TAB2D)
              NULLIFY (RP%ADAS%TAB2D)
              ALLOCATE (RP%ADAS%TAB2D(RP%ADAS%NTEMP,RP%ADAS%NDENS))
            END IF
          ELSE
            ALLOCATE (RP%ADAS%TAB2D(RP%ADAS%NTEMP,RP%ADAS%NDENS))
          ENDIF
        END IF

        CALL MPI_BCAST (RP%ADAS%DENS,RP%ADAS%NDENS,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%ADAS%TEMP,RP%ADAS%NTEMP,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%ADAS%DDE,RP%ADAS%NDENS,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%ADAS%DTE,RP%ADAS%NTEMP,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%ADAS%TAB2D,RP%ADAS%NTEMP*RP%ADAS%NDENS,
     .                  MPI_REAL8,0,MPI_COMM_WORLD,ier)

C.....................................................................
      ELSE IF (RP%IFIT == 4) THEN
! 1D TABLES. E.G. HYDKIN DATA
        IF (MY_PE .NE. 0) THEN
          IF (.NOT.ASSOCIATED(RP%HYD)) THEN
             ALLOCATE (RP%HYD)
             NULLIFY(RP%HYD%TEMPS)
             NULLIFY(RP%HYD%RATES)
             NULLIFY(RP%HYD%RATIO)
          END IF
        END IF

        CALL MPI_BCAST (RP%HYD%NTEMPS,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%HYD%REACNAME,50,MPI_CHARACTER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%HYD%REAC_STRING,50,MPI_CHARACTER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%HYD%RPRT,100,MPI_CHARACTER,
     .                  0,MPI_COMM_WORLD,ier)

        IF (MY_PE .NE. 0) THEN
          IF (ASSOCIATED(RP%HYD%TEMPS)) THEN
            IF (RP%HYD%NTEMPS.ne.UBOUND(RP%HYD%TEMPS,1)) THEN
               DEALLOCATE (RP%HYD%TEMPS)
               NULLIFY (RP%HYD%TEMPS)
               ALLOCATE (RP%HYD%TEMPS(RP%HYD%NTEMPS))
            ENDIF
          ELSE
            ALLOCATE (RP%HYD%TEMPS(RP%HYD%NTEMPS))
          ENDIF
          IF (ASSOCIATED(RP%HYD%RATES)) THEN
            IF (RP%HYD%NTEMPS.ne.UBOUND(RP%HYD%RATES,1)) THEN
               DEALLOCATE (RP%HYD%RATES)
               NULLIFY (RP%HYD%RATES)
               ALLOCATE (RP%HYD%RATES(RP%HYD%NTEMPS))
            ENDIF
          ELSE
            ALLOCATE (RP%HYD%RATES(RP%HYD%NTEMPS))
          ENDIF
          IF (ASSOCIATED(RP%HYD%RATIO)) THEN
            IF (RP%HYD%NTEMPS.ne.UBOUND(RP%HYD%RATIO,1)) THEN
               DEALLOCATE (RP%HYD%RATIO)
               NULLIFY (RP%HYD%RATIO)
               ALLOCATE (RP%HYD%RATIO(RP%HYD%NTEMPS))
            END IF
          ELSE
            ALLOCATE (RP%HYD%RATIO(RP%HYD%NTEMPS))
          ENDIF
        END IF

        CALL MPI_BCAST (RP%HYD%TEMPS,RP%HYD%NTEMPS,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%HYD%RATES,RP%HYD%NTEMPS,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%HYD%RATIO,RP%HYD%NTEMPS,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
C.....................................................................
      ELSE IF (RP%IFIT == 5 ) THEN
cdr  internal CR Model
        IF (MY_PE .NE. 0) THEN
          IF (.NOT.ASSOCIATED(RP%CRM)) THEN
            ALLOCATE (RP%CRM)
          END IF
        END IF

        CALL MPI_BCAST (RP%CRM%IFLAV,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (RP%CRM%IVARST,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)

C.....................................................................
      ELSE
cdr     INVALID RP%IFIT
      END IF

      RETURN
      END SUBROUTINE EIRENE_BROAD_FIT_FORM



      SUBROUTINE EIRENE_BROAD_EMIS_LINES
      
      INTEGER :: I, J, K, NUM_COMPO, NUM_CONTRIB
      TYPE(TCONTRIB) :: CNT

!     IF (MY_PE /= 0) THEN
        IF (.NOT.ALLOCATED(EMIS_LINES)) THEN
          ALLOCATE (EMIS_LINES(num_LINES))
          EMIS_LINES%LINE_NAME = REPEAT(' ',80)
          EMIS_LINES%NUM_COMPO = 0         
        END IF
!     END IF

      DO I = 1, num_LINES

        CALL MPI_BCAST (EMIS_LINES(I)%LINE_NAME,80,MPI_CHARACTER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (EMIS_LINES(I)%NUM_COMPO,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (EMIS_LINES(I)%IADV_TOTAL,1,MPI_INTEGER,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (EMIS_LINES(I)%EINSTEIN,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (EMIS_LINES(I)%ENERGY,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)
        CALL MPI_BCAST (EMIS_LINES(I)%TRANS_EN,1,MPI_REAL8,
     .                  0,MPI_COMM_WORLD,ier)

        NUM_COMPO = EMIS_LINES(I)%NUM_COMPO

        IF (MY_PE /= 0) THEN
          ALLOCATE (EMIS_LINES(I)%COMPO(NUM_COMPO))
        END IF

        DO J = 1, NUM_COMPO
          CALL MPI_BCAST (EMIS_LINES(I)%COMPO(J)%COMPO_NAME,80,
     .                    MPI_CHARACTER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (EMIS_LINES(I)%COMPO(J)%NUM_CONTRIB,1,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)
          CALL MPI_BCAST (EMIS_LINES(I)%COMPO(J)%IADV,1,
     .                    MPI_INTEGER,0,MPI_COMM_WORLD,ier)

          NUM_CONTRIB = EMIS_LINES(I)%COMPO(J)%NUM_CONTRIB

          IF (MY_PE /= 0) THEN
            ALLOCATE (EMIS_LINES(I)%COMPO(J)%CONTRIB(NUM_CONTRIB))
          END IF

          DO K = 1, NUM_CONTRIB
        
            IF (MY_PE == 0) CNT = EMIS_LINES(I)%COMPO(J)%CONTRIB(K)

            CALL MPI_BCAST (CNT%ISP,3,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%ITP,3,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%IRATIO,1,MPI_INTEGER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%IRC,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%IRC_RAT,2,MPI_INTEGER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%IZ,1,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%IZ_RAT,2,MPI_INTEGER,
     .                      0,MPI_COMM_WORLD,ier)

            CALL MPI_BCAST (CNT%FNAME,8,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%FRATIO,2*8,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%H123,4,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%RAT_H123,2*4,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%ELEMENT,2,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%RAT_ELEMENT,2*2,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%REACTION,9,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%RAT_REACTION,2*9,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%CR,3,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            CALL MPI_BCAST (CNT%RAT_CR,2*3,MPI_CHARACTER,
     .                      0,MPI_COMM_WORLD,ier)
            
            IF (MY_PE /= 0) EMIS_LINES(I)%COMPO(J)%CONTRIB(K) = CNT

          END DO
        END DO

        
      END DO

      RETURN
      END SUBROUTINE EIRENE_BROAD_EMIS_LINES

      END
