C> \brief Broadcasts the strata to process distribution.
C>
C> It broadcasts the distribution of strata to processes as defined in
C> the PEDIST routines.
      SUBROUTINE EIRENE_BROAD_PEDIST(XTIM)

      USE EIRMOD_PRECISION, ONLY: DP
      USE EIRMOD_PARMMOD, ONLY: NSTRA
      USE EIRMOD_COMUSR, ONLY: NPRLL
      USE EIRMOD_CPES, ONLY: NLIDENT, EIRENE_ALLOC_CPES
      USE EIRMOD_MPI
      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: XTIM(0:NSTRA)
      INTEGER :: IER

      CALL EIRENE_ALLOC_CPES
      CALL MPI_BCAST (NLIDENT,1,MPI_LOGICAL,0,MPI_COMM_WORLD,ier)

      SELECT CASE( NPRLL )
        CASE( -1 )
          CALL EIRENE_BROAD_PEDIST_USR( XTIM )
        CASE( 0 )
          CALL EIRENE_BROAD_PEDIST_EMBPARALL
        CASE( 1 )
          CALL EIRENE_BROAD_PEDIST_PROPALLOC( XTIM )
      END SELECT

      CONTAINS

      SUBROUTINE EIRENE_BROAD_PEDIST_EMBPARALL
      USE EIRMOD_CPES, ONLY: NPESTA, NPESTR, NPRS, PROCFORSTRA
      USE EIRMOD_PARMMOD, ONLY: NSTRA
      USE EIRMOD_MPI

      IMPLICIT NONE

      INTEGER :: IER

      CALL MPI_BCAST(PROCFORSTRA, NSTRA * NPRS, MPI_LOGICAL, 0,
     >               MPI_COMM_WORLD, IER)
      CALL MPI_BCAST(NPESTA, NSTRA, MPI_INTEGER, 0, MPI_COMM_WORLD, IER)
      CALL MPI_BCAST(NPESTR, NSTRA, MPI_INTEGER, 0, MPI_COMM_WORLD, IER)

      RETURN
      END SUBROUTINE EIRENE_BROAD_PEDIST_EMBPARALL

      SUBROUTINE EIRENE_BROAD_PEDIST_PROPALLOC(XTIM)
      USE EIRMOD_PARMMOD, ONLY: NSTRA
      USE EIRMOD_COMSOU, ONLY: NPTS
      USE EIRMOD_CPES, ONLY: NPESTA, NPESTR, NPRS,
     >                       PROCFORSTRA
      USE EIRMOD_MPI

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: XTIM(0:NSTRA)
      INTEGER :: IER

      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (NPESTR,NSTRA,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPESTA,NSTRA,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (NPTS,NSTRA,MPI_INTEGER,0,MPI_COMM_WORLD,ier)
      CALL MPI_BCAST (XTIM,NSTRA+1,MPI_REAL8,0,MPI_COMM_WORLD,ier)

      CALL MPI_BCAST (PROCFORSTRA,NSTRA*NPRS,MPI_LOGICAL,0,
     .                MPI_COMM_WORLD,ier)

      CALL MPI_BARRIER(MPI_COMM_WORLD,ier)

      RETURN
      END SUBROUTINE EIRENE_BROAD_PEDIST_PROPALLOC

      END SUBROUTINE EIRENE_BROAD_PEDIST
