C   USER-DEFINED GEOMETRY (GEOMETRY LEVEL: LEVGEO=10)
C   RETURN TIME OF FLIGHT TO NEXT CELL SURFACE
C
C  ALSO IN THIS MODULE:
C   SUBROUTINE NORUSR
C   RETURN SURFACE NORMAL AT A GRID SURFACE NO. IS, AND, IN CASE OF PERIODICITY
C          ALSO PROVIDE NEW POSITION AND VELOCITY AT NEW SURFACE

      SUBROUTINE EIRENE_TIMUSR(N,X,Y,Z,VX,VY,VZ,N1,N2,T,IC,IE,NP,NL)
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      IMPLICIT NONE
      REAL(DP), INTENT(INOUT) :: X,Y,Z,VX,VY,VZ,T
      INTEGER, INTENT(INOUT) :: N, N1, N2, IC, IE, NP
      LOGICAL :: NL

      RETURN
      END SUBROUTINE EIRENE_TIMUSR

      SUBROUTINE EIRENE_NORUSR(is,x,y,z,cx,cy,cz,sc,VX,VY,VZ,NRCELL)
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      IMPLICIT NONE
      REAL(DP), INTENT(INOUT) :: X,Y,Z,VX,VY,VZ,cx,cy,cz,sc
      INTEGER, INTENT(INOUT) :: IS, NRCELL


      RETURN
      END SUBROUTINE EIRENE_NORUSR
