 
 
      FUNCTION EIRENE_FEHVPI3 (IRPI,K)
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR
      USE EIRMOD_CCONA
      USE EIRMOD_COMXS
 
      IMPLICIT NONE
 
      INTEGER, INTENT(IN) :: IRPI, K
      REAL(DP) :: EIRENE_FEHVPI3, EHVPI, EIRENE_FTABPI3,
     .            EIRENE_RATE_COEFF
      INTEGER :: KK
 
      EIRENE_FEHVPI3=0.D0
      KK=NRHVPI(IRPI)
 
      IF (KK == -1) THEN
! TAKE EHEAVY FROM INPUT FILE
         EIRENE_FEHVPI3=EHVPI3(IRPI,1,1)
 
      ELSE IF (KK > 0) THEN
        EHVPI = EIRENE_RATE_COEFF(KK,K,TEINL(K),0._DP,.FALSE.,0)
        EHVPI=EXP(MAX(-100._DP,EHVPI+FACRPI(IRPI,2)))
        EIRENE_FEHVPI3=EHVPI*DEIN(K)/(EIRENE_FTABPI3(IRPI,K)+EPS60)
      END IF
 
      RETURN
      END
