cdr  unfinished routine, not to be used 


      FUNCTION EIRENE_FEPLPH3 (IRPH,K)

      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR
      USE EIRMOD_CCONA
      USE EIRMOD_COMPRT
      USE EIRMOD_COMXS
      USE EIRMOD_PHOTON

      IMPLICIT NONE

      INTEGER, INTENT(IN) :: IRPH, K
      REAL(DP) :: EIRENE_FEPLPH3
      INTEGER :: KK, IPLSTI
      EXTERNAL :: EIRENE_EXIT_OWN

      EIRENE_FEPLPH3=0.D0
      KK=NELRPH(IRPH)
      IPLSTI=MPLSTI(IPLS)
      SELECT CASE (KK)
      CASE (-2)
         EIRENE_FEPLPH3=EPLPH3(IRPH,1,1)
         IF (LEDRIFT) EIRENE_FEPLPH3=EIRENE_FEPLPH3+EDRIFT(IPLS,K)
      CASE (-3)
         EIRENE_FEPLPH3=1.5*TIIN(IPLSTI,K)
         IF (LEDRIFT) EIRENE_FEPLPH3=EIRENE_FEPLPH3+EDRIFT(IPLS,K)
      CASE DEFAULT
        WRITE (iunout,*) ' FEPLPH3 NOT READY '
        WRITE (iunout,*) ' CALCULATION ABANDONED '
        CALL EIRENE_EXIT_OWN(1)
      END SELECT

      RETURN
      END FUNCTION EIRENE_FEPLPH3
