      MODULE EIRMOD_REFUSR
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      PRIVATE

      PUBLIC :: EIRENE_REFUSR, EIRENE_REFUSR_INIT,
     .          EIRENE_SPTUSR, EIRENE_SPTUSR_INIT

      CONTAINS
      
      SUBROUTINE EIRENE_REFUSR_INIT
      IMPLICIT NONE
      RETURN
      END SUBROUTINE EIRENE_REFUSR_INIT

      SUBROUTINE EIRENE_SPTUSR_INIT
      IMPLICIT NONE
      RETURN
      END SUBROUTINE EIRENE_SPTUSR_INIT

      SUBROUTINE EIRENE_SPTUSR
      IMPLICIT NONE
      RETURN
      END SUBROUTINE EIRENE_SPTUSR

      SUBROUTINE EIRENE_REFUSR (XMW,XCW,XMP,XCP,IGASF,IGAST,ZCOS,ZSIN,
     .                          EXPI,RPROB,E0TERM,IRET)
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: XMW,XCW,XMP,XCP,ZCOS,ZSIN,EXPI,RPROB,
     .                        E0TERM
      INTEGER, INTENT(IN) :: IGASF,IGAST
      INTEGER, INTENT(OUT) :: IRET
      IRET = 0
      RETURN
      END SUBROUTINE EIRENE_REFUSR

      END MODULE EIRMOD_REFUSR
