 
      SUBROUTINE EIRENE_UPDATE_SURFACE (ITOLD)

c  SCORE "EMITTED" SURFACE FLUX TALLIES, FOR SURFACE MSURF, OR SURFACE SEGMENT MSURFG.
c  update tallies PRF_A_B(iout,msurf) and ERF_A_B(iout,msurf)
c  A code-letter for incident type of particle: A, M, I, P, PH
c  B code-letter for emitted type of particle :  AT, ML, IO, PL, PHT
c  iout:  species index for emitted particle
 
c     CURRENTLY:  
C       PARTICLE FLUXES (WEIGHT)
C       ENERGY FLUXES   (E0*WEIGHT)

c  input:
c     itold:  TYPE IF INCIDENT SPECIES
c     msurf:  surface index
c     msurfg:  sub-segement of surface MSURF, for spatial resolution on surface
c     ityp :  type of emitted particle
c     ispez  (iatm, imol, iion, ipls, iphot): of emitted particle

 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CESTIM
      USE EIRMOD_COMPRT
      USE EIRMOD_COMUSR
      USE EIRMOD_CSPEZ
      USE EIRMOD_CSDVI
 
      IMPLICIT NONE
 
      INTEGER, INTENT(IN) :: ITOLD
 
      IF (MSURF .LE. 0) RETURN
c  emitted photons ,  currently: only for incident photons
      IF (ITYP.EQ.0) THEN
        LOGPHOT(IPHOT,ISTRA)=.TRUE.
        IF (ITOLD.EQ.0) THEN
          IF (LPRFPHPHT)
     .      PRFPHPHT(IPHOT,MSURF)=PRFPHPHT(IPHOT,MSURF)+WEIGHT
          IF (LERFPHPHT)
     .      ERFPHPHT(IPHOT,MSURF)=ERFPHPHT(IPHOT,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFPHPHT)
     .        PRFPHPHT(IPHOT,MSURFG)=PRFPHPHT(IPHOT,MSURFG)+WEIGHT
            IF (LERFPHPHT)
     .        ERFPHPHT(IPHOT,MSURFG)=ERFPHPHT(IPHOT,MSURFG)
     .                               +E0*WEIGHT
          ENDIF
          IF (LPRFPHPHT .OR. LERFPHPHT) LMETSPW(IPHOT) = .TRUE.
        ENDIF
c  emitted atoms
      ELSEIF (ITYP.EQ.1) THEN
        LOGATM(IATM,ISTRA)=.TRUE.
        IF (ITOLD.EQ.1) THEN
          IF (LPRFAAT) PRFAAT(IATM,MSURF)=PRFAAT(IATM,MSURF)+WEIGHT
          IF (LERFAAT)
     .      ERFAAT(IATM,MSURF)=ERFAAT(IATM,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFAAT)
     .        PRFAAT(IATM,MSURFG)=PRFAAT(IATM,MSURFG)+WEIGHT
            IF (LERFAAT)
     .        ERFAAT(IATM,MSURFG)=ERFAAT(IATM,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFAAT .OR. LERFAAT) LMETSPW(NSPH+IATM) = .TRUE.
        ELSEIF (ITOLD.EQ.2) THEN
          IF (LPRFMAT) PRFMAT(IATM,MSURF)=PRFMAT(IATM,MSURF)+WEIGHT
          IF (LERFMAT)
     .      ERFMAT(IATM,MSURF)=ERFMAT(IATM,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFMAT)
     .        PRFMAT(IATM,MSURFG)=PRFMAT(IATM,MSURFG)+WEIGHT
            IF (LERFMAT)
     .        ERFMAT(IATM,MSURFG)=ERFMAT(IATM,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFMAT .OR. LERFMAT) LMETSPW(NSPH+IATM) = .TRUE.
        ELSEIF (ITOLD.EQ.3) THEN
          IF (LPRFIAT) PRFIAT(IATM,MSURF)=PRFIAT(IATM,MSURF)+WEIGHT
          IF (LERFIAT)
     .      ERFIAT(IATM,MSURF)=ERFIAT(IATM,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFIAT)
     .        PRFIAT(IATM,MSURFG)=PRFIAT(IATM,MSURFG)+WEIGHT
            IF (LERFIAT)
     .        ERFIAT(IATM,MSURFG)=ERFIAT(IATM,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFIAT .OR. LERFIAT) LMETSPW(NSPH+IATM) = .TRUE.
        ELSEIF (ITOLD.EQ.4) THEN
          IF (LPRFPAT)
     .      PRFPAT(IATM,MSURF)=PRFPAT(IATM,MSURF)+WEIGHT
          IF (LERFPAT)
     .      ERFPAT(IATM,MSURF)=ERFPAT(IATM,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFPAT)
     .        PRFPAT(IATM,MSURFG)=PRFPAT(IATM,MSURFG)+WEIGHT
            IF (LERFPAT)
     .        ERFPAT(IATM,MSURFG)=ERFPAT(IATM,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFPAT .OR. LERFPAT) LMETSPW(NSPH+IATM) = .TRUE.
        ENDIF
c  emitted molecules
      ELSEIF (ITYP.EQ.2) THEN
        LOGMOL(IMOL,ISTRA)=.TRUE.
        IF (ITOLD.EQ.1) THEN
          IF (LPRFAML) PRFAML(IMOL,MSURF)=PRFAML(IMOL,MSURF)+WEIGHT
          IF (LERFAML)
     .      ERFAML(IMOL,MSURF)=ERFAML(IMOL,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFAML)
     .        PRFAML(IMOL,MSURFG)=PRFAML(IMOL,MSURFG)+WEIGHT
            IF (LERFAML)
     .        ERFAML(IMOL,MSURFG)=ERFAML(IMOL,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFAML .OR. LERFAML) LMETSPW(NSPA+IMOL) = .TRUE.
        ELSEIF (ITOLD.EQ.2) THEN
          IF (LPRFMML) PRFMML(IMOL,MSURF)=PRFMML(IMOL,MSURF)+WEIGHT
          IF (LERFMML)
     .      ERFMML(IMOL,MSURF)=ERFMML(IMOL,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFMML)
     .        PRFMML(IMOL,MSURFG)=PRFMML(IMOL,MSURFG)+WEIGHT
            IF (LERFMML)
     .        ERFMML(IMOL,MSURFG)=ERFMML(IMOL,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFMML .OR. LERFMML) LMETSPW(NSPA+IMOL) = .TRUE.
        ELSEIF (ITOLD.EQ.3) THEN
          IF (LPRFIML) PRFIML(IMOL,MSURF)=PRFIML(IMOL,MSURF)+WEIGHT
          IF (LERFIML)
     .      ERFIML(IMOL,MSURF)=ERFIML(IMOL,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFIML)
     .        PRFIML(IMOL,MSURFG)=PRFIML(IMOL,MSURFG)+WEIGHT
            IF (LERFIML)
     .        ERFIML(IMOL,MSURFG)=ERFIML(IMOL,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFIML .OR. LERFIML) LMETSPW(NSPA+IMOL) = .TRUE.
        ELSEIF (ITOLD.EQ.4) THEN
          IF (LPRFPML)
     .      PRFPML(IMOL,MSURF)=PRFPML(IMOL,MSURF)+WEIGHT
          IF (LERFPML)
     .      ERFPML(IMOL,MSURF)=ERFPML(IMOL,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFPML)
     .        PRFPML(IMOL,MSURFG)=PRFPML(IMOL,MSURFG)+WEIGHT
            IF (LERFPML)
     .        ERFPML(IMOL,MSURFG)=ERFPML(IMOL,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFPML .OR. LERFPML) LMETSPW(NSPA+IMOL) = .TRUE.
        ENDIF
c  emitted test ions
      ELSEIF (ITYP.EQ.3) THEN
        LOGION(IION,ISTRA)=.TRUE.
        IF (ITOLD.EQ.1) THEN
          IF (LPRFAIO) PRFAIO(IION,MSURF)=PRFAIO(IION,MSURF)+WEIGHT
          IF (LERFAIO)
     .      ERFAIO(IION,MSURF)=ERFAIO(IION,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFAIO)
     .        PRFAIO(IION,MSURFG)=PRFAIO(IION,MSURFG)+WEIGHT
            IF (LERFAIO)
     .        ERFAIO(IION,MSURFG)=ERFAIO(IION,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFAIO .OR. LERFAIO) LMETSPW(NSPAM+IION) = .TRUE.
        ELSEIF (ITOLD.EQ.2) THEN
          IF (LPRFMIO) PRFMIO(IION,MSURF)=PRFMIO(IION,MSURF)+WEIGHT
          IF (LERFMIO)
     .      ERFMIO(IION,MSURF)=ERFMIO(IION,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFMIO)
     .        PRFMIO(IION,MSURFG)=PRFMIO(IION,MSURFG)+WEIGHT
            IF (LERFMIO)
     .        ERFMIO(IION,MSURFG)=ERFMIO(IION,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFMIO .OR. LERFMIO) LMETSPW(NSPAM+IION) = .TRUE.
        ELSEIF (ITOLD.EQ.3) THEN
          IF (LPRFIIO) PRFIIO(IION,MSURF)=PRFIIO(IION,MSURF)+WEIGHT
          IF (LERFIIO)
     .      ERFIIO(IION,MSURF)=ERFIIO(IION,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFIIO)
     .        PRFIIO(IION,MSURFG)=PRFIIO(IION,MSURFG)+WEIGHT
            IF (LERFIIO)
     .        ERFIIO(IION,MSURFG)=ERFIIO(IION,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFIIO .OR. LERFIIO) LMETSPW(NSPAM+IION) = .TRUE.
        ELSEIF (ITOLD.EQ.4) THEN
          IF (LPRFPIO)
     .      PRFPIO(IION,MSURF)=PRFPIO(IION,MSURF)+WEIGHT
          IF (LERFPIO)
     .      ERFPIO(IION,MSURF)=ERFPIO(IION,MSURF)+E0*WEIGHT
          IF (MSURFG.GT.0) THEN
            IF (LPRFPIO)
     .        PRFPIO(IION,MSURFG)=PRFPIO(IION,MSURFG)+WEIGHT
            IF (LERFPIO)
     .        ERFPIO(IION,MSURFG)=ERFPIO(IION,MSURFG)+E0*WEIGHT
          ENDIF
          IF (LPRFPIO .OR. LERFPIO) LMETSPW(NSPAM+IION) = .TRUE.
        ENDIF
c  no tallies for emitted bulk particles
      ENDIF
 
      RETURN
      END SUBROUTINE EIRENE_UPDATE_SURFACE
