      MODULE EIRMOD_UPCUSR

      PUBLIC

      CONTAINS

      
C  user-supplied collision estimator.
C  called from folion, folneut, at a collision event in cell NCELL
C
      SUBROUTINE EIRENE_UPCUSR(WS,IND,KK)
C
C  USER-SUPPLIED COLLISION ESTIMATOR, VOLUME-AVERAGED
C
C  ON INPUT:
C     WS=WEIGHT/SIGTOT=WEIGHT/(VEL*ZMFPI)=WEIGHT/(VEL*SIGMA,MACR.)
C     IND =1  PRE-COLLISION ESTIMATOR,  called prior to call to subr. COLLIDE
C     IND =2  POST-COLLISION ESTIMATOR, called after call to subr. COLLIDE
C
C  via modules:  NCELL, IATM
C
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CESTIM
      USE EIRMOD_COMUSR
      USE EIRMOD_COMPRT
      USE EIRMOD_COMXS
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: WS
      INTEGER, INTENT(IN) :: IND, KK
C
C     WS=WEIGHT/SIGTOT=WEIGHT/(VEL*ZMFPI)=WEIGHT/(VEL*SIGMA,MACR.)
C
C  FOR PARTICLE DENSITY IN CELL NO. NCELL
C     COLV(1,NCELL)=COLV(1,NCELL)+WS
C
      RETURN
      END SUBROUTINE EIRENE_UPCUSR

      END MODULE EIRMOD_UPCUSR
      
