C  USER PROVIDED ROUTINE TO IDENTIFY A GRID CELL NUMBER LEAUSR, GIVEN
C                        A POINT VIA ITS COORDINATES X,Y,Z=A,B,C  

C  DEFAULT:  RETURN LEAUSR=1 
 
      FUNCTION EIRENE_LEAUSR(A,B,C)
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: A, B, C
      INTEGER :: EIRENE_LEAUSR
      EIRENE_LEAUSR=1
      RETURN
      END
