cdr  OCT. 15: EXAMPLE ADDED: PARTICLE DENSITY, SMAPSHOT ESTIMATED
c
      subroutine EIRENE_upnusr
C
C  USER SUPPLIED SNAPSHOT ESTIMATOR, VOLUME AVERAGED
C
C  via modules:  NCELL, ITYP,IATM
C
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CESTIM
      USE EIRMOD_COMPRT
      IMPLICIT NONE

C
C  FOR PARTICLE DENSITY IN CELL NO. NCELL
C     SNAPV(1,NCELL)=SNAPV(1,NCELL)+WEIGHT

C  THIS EXAMPLE: SNAPSHOT ESTIMATOR ONLY FOR ONLY ATOMIC PARTICLES
      IF (ITYP.NE.1) RETURN

C  CHECK STORAGE
      IF (IATM.GT.NSNV) THEN
        RETURN
      ENDIF
C
C  TALLY 1: PARTICLE DENSITY, ATOMIC SPECIES IATM (FOR TESTING/VERIFICAITON)
      SNAPV(IATM,NCELL)=SNAPV(IATM,NCELL)+WEIGHT
C
      return
      end
