      MODULE EIRMOD_PL3D
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      PRIVATE

      PUBLIC :: EIRENE_PL3D, EIRENE_PL3D_REINIT

      CONTAINS
C
C
      SUBROUTINE EIRENE_PL3D(PX,PY,PZ,PP1,PP2)

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: PX, PY, PZ
      REAL(DP), INTENT(OUT) :: PP1, PP2

      PP1=0.d0
      PP2=0.d0

      return
      END SUBROUTINE EIRENE_PL3D

      SUBROUTINE EIRENE_PL3D_REINIT
      IMPLICIT NONE

      return
      end SUBROUTINE EIRENE_PL3D_REINIT

      END MODULE EIRMOD_PL3D
