      MODULE EIRMOD_STCOOR
      USE EIRMOD_PRECISION
      IMPLICIT NONE
      PRIVATE

      PUBLIC :: EIRENE_STCOOR, EIRENE_STCOOR_REINIT

      CONTAINS
C
C
      SUBROUTINE EIRENE_STCOOR (X,Y,IFL)
      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: X, Y
      INTEGER, INTENT(IN) :: IFL

      RETURN
      END SUBROUTINE EIRENE_STCOOR

C     the following ENTRY is for reinitialization of EIRENE

      SUBROUTINE EIRENE_STCOOR_REINIT
      IMPLICIT NONE

      return
      END SUBROUTINE EIRENE_STCOOR_REINIT

      END MODULE EIRMOD_STCOOR
