C
      SUBROUTINE EIRENE_STORE(IFLAG)
 
C  PURPOSE: STORE TRAJECTORIES
C  TO BE WRITTEN
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD, ONLY: IFOFF
      USE EIRMOD_COMPRT, ONLY: IUNOUT
      IMPLICIT NONE
 
      INTEGER :: IFIRST, IFLAG
      DATA IFIRST/0/
 
      IF (IFIRST.EQ.0) THEN
        IFIRST=1
        OPEN (UNIT=16+ifoff,ACCESS='SEQUENTIAL',FORM='UNFORMATTED')
      ENDIF
      GOTO (10,20,30,40,50,60,70,80,90),IFLAG
      WRITE (iunout,*) 'IFLAG OUT OF RANGE IN SUBR. STORE '
      WRITE (iunout,*) 'EXIT CALLED'
      CALL EIRENE_EXIT_OWN(1)
C  LOCATE
10    CONTINUE
20    CONTINUE
C  IONIZATION
30    CONTINUE
40    CONTINUE
50    CONTINUE
C  SURFACE
60    CONTINUE
70    CONTINUE
80    CONTINUE
C  NEW CELL
90    CONTINUE
      RETURN
csw
      entry EIRENE_store_reinit
      close(unit=16+ifoff)
      ifirst=0
      return
csw
      END
