C
C
      SUBROUTINE EIRENE_SIGLOS(INIT,JJJ,ZDS,DUM1,PSIG,DUM2,ARGST)
C  MG 27/8/21 (MG) User routine to test line integral, but writing of
C  output via linint.f as done for sigha.f
C
C  ONLY FOR TESTING LINE INTEGRAL ROUTINES
C  INPUT:
C          IFIRST: FLAG FOR INITIALISATION
C          JJJ:    INDEX OF SEGMENT ALONG CHORD
C          ZDS:    LENGTH OF SEGMENT NO. JJJ
C
C  OUTPUT:
C          PSIG: TOTAL LINE INTEGRAL OF LOS
C          ARGST: CONTRIB. FROM CELL NCELL AND CHORD SEGMENT JJJ
C                 (=ZDS)
C          THE INTEGRANT ARGST IS SUCH THAT INTEGR.(ARGST*DL) = PSIG
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMPRT
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: INIT, JJJ
      REAL(DP), INTENT(IN) :: ZDS,DUM1,DUM2
      REAL(DP), INTENT(IN OUT) :: PSIG(0:), ARGST(0:,:)
      LOGICAL :: LARGST
      SAVE
C
      LARGST = SIZE(ARGST,2) >= NRAD

      IF (INIT.EQ.0) THEN
        PSIG=0.
        IF (LARGST) ARGST=0.
        RETURN
      ENDIF


C  LINE INTEGRAL: CM
C
C
      PSIG(1)=PSIG(1)+ZDS
      ARGST(1,JJJ)=ZDS

      RETURN
      END SUBROUTINE EIRENE_SIGLOS
