C
C
      SUBROUTINE EIRENE_SIGTST(IFIRST,JJJ,ZDS,DUMMY1,PSIG,DUMMY2,ARGST)
C
C  ONLY FOR TESTING LINE INTEGRAL ROUTINES
C  INPUT:
C          IFIRST: FLAG FOR INITIALISATION
C          JJJ:    INDEX OF SEGMENT ALONG CHORD
C          ZDS:    LENGTH OF SEGMENT NO. JJJ
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMPRT
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: IFIRST, JJJ
      REAL(DP), INTENT(IN) :: ZDS, DUMMY1, DUMMY2
      REAL(DP), INTENT(IN OUT) :: PSIG(0:), ARGST(0:,:)
      LOGICAL :: LARGST
      SAVE
C
      LARGST = SIZE(ARGST,2) >= NRAD

      PSIG=0.
      IF (LARGST) ARGST=0.
C
      WRITE (iunout,*) 'FROM SIGTST ',
     .                 JJJ,ZDS,NRCELL,NPCELL,NTCELL,NACELL
      RETURN
      END SUBROUTINE EIRENE_SIGTST
