      SUBROUTINE EIRENE_ALLOC_COUPLE
      USE EIRMOD_PARMMOD
      USE EIRMOD_BRAEIR
      USE EIRMOD_EIRBRA
      USE EIRMOD_CCOUPL
      USE EIRMOD_COMUSR, ONLY : NMODE

      IF (NMODE .NE. 0) CALL EIRENE_ALLOC_CCOUPL(1)
      CALL EIRENE_ALLOC_CCOUPL(2)

      CALL EIRENE_ALLOC_BRAEIR (NCVP,NFCP,NFL)
      CALL EIRENE_ALLOC_EIRBRA (NCVP,NFL,NATM,NMOL,NION,NSTRA)

      END SUBROUTINE EIRENE_ALLOC_COUPLE
