      MODULE EIRMOD_VELOEL
      IMPLICIT NONE
      PRIVATE

      PUBLIC :: EIRENE_VELOEL, EIRENE_VELOEL_REINIT

      INTEGER, SAVE :: IFIRST = 0

      CONTAINS

c         061205:   au_to_cm2 --> ccona
!         100107:   ENTRY VELOEL_REINIT added for reinitialization of EIRENE
CDR  Aug. 2015  : PROGRAMMING AND NOTATION SYNCHRONIZED WITH VELOCX.F
!DR
!DR
CDR  5.8.15 : ARGUMENTS ADDED TO VECUSR
cdr  4.9.15 : npbgkp(ipls,1).ne.0, rather than nchrgp(ipls)=0 to identify bgk collisions
cdr           There may be also neutral atom -test ion  bgk collisions, in which case
cdr           the virtual bgk background species may be an ion ? (not contributing to electron density, however).
cdr           example He  He+  collisions, when both are test species.
cdr           Or, e.g. elastic component in H + p
cdr  Jan. 17: Added option: isotropic in COM frame, iflag=0, when modcol(5,0,..)=0
cdr                         exchange of identity in lab system when modcol(5,0,..)=-1
cdr                         (this was default for bgk collisions so far, with OLD iflag=0)
cdr March 18: Slight changes in notation, to sync with a new proprietary version of this
cdr           routine which carries out cross-section integration directly
cdr           from interaction potentials without intermediate fits. veloel_TEST.ff
C
      SUBROUTINE EIRENE_VELOEL(K,VXO,VYO,VZO,VLO,IOLD,NOLD,VELQ,NFLAG,
     .                         IREL,RMASS)
C
C  THIS SUBROUTINE CARRIES OUT AN ELASTIC COLLISION OF A TEST PARTICLE
C  WITH A BULK PARTICLE.
C  IT RETURNS THE POST-COLLISION VELOCITY VECTOR.
C
C  NFLAG= 1:       SAMPLING FROM MONOENERGETIC DISTRIBUTION
C                  OF ION SPEED IN 3D, X,Y,Z DIRECTION
C                  (I.E., DELTA FUNCTION IN ENERGY SPACE)
C                  E=M/2 V_M^2 =3/2 KT, IN REST FRAME OF IPLS
C                  USE WEIGHT CORRECTION OR REJECTION
C                  to be generalized to E=ESIGCX(IRCX,1)
C  NFLAG= 2:       SAMPLING FROM SHIFTED MAXWELLIAN
C                  "FMAXW" AT TI AND V-DRIFT IN CELL K
C  NFLAG= 3:       SAMPLING FROM SHIFTED MAXWELLIAN + WEIGHT CORRECTION
C                  FACTOR = SIGMA*VREL*FMAXW/<SIGMA*VREL>
C                  OR ALTERNATIVELY: REJECTION
C
C  1ST STEP: FIND COLLISION PARTNER FROM BULK ION SPECIES "IPLS":
C            (VXN,VYN,VZN)
C  2ND STEP: FIND CROSS-SECTION AS FUNCTION OF ELAB (AND
C            CARRY OUT WEIGHT CORRECTION, UNLESS REJECTION HAS BEEN USED
C            IN STEP 1
C  3RD STEP: FIND IMPACT PARAMETER B
C  4TH STEP: FIND NEW VELOCITY VECTOR
C
C
C  K   : CELL INDEX

C  K   : .NE.0 :CELL INDEX FOR LOCAL BULK ION TI AND V_DRIFT
C  note: Ti has already been converted into thermal velocity units: zrg(ipls,k) in [cm/s]

C  K   : .EQ.0 :TX,TY,TZ,V-DRIFT_X,Y,Z ARE NOT FROM LOCAL BULK ION
C               SPECIES IPLS PARAMETERS, BUT EXPLICITLY DEFINED IN THE
C               PARAMETERS DUMT AND DUMV, RESPECTIVELY.
c  note: here dumt must also be in thermal velocity units

C  VXO : X COMPONENT OF SPEED UNIT VECTOR OF TEST PARTICLE BEFORE EVENT
C  VYO : Y COMPONENT OF SPEED UNIT VECTOR OF TEST PARTICLE BEFORE EVENT
C  VZO : Z COMPONENT OF SPEED UNIT VECTOR OF TEST PARTICLE BEFORE EVENT
C  VLO : VELOCITY OF TEST PARTICLE BEFORE EVENT
C  IOLD: SPECIES INDEX OF THE TEST PARTICLE BEFORE THE EVENT
C  NOLD: DITTO, IN MODCOL ARRAY
C  IPLS: SPECIES INDEX FOR THE THERMAL PLASMA ION VELOCITY
C        AND FOR THE PLASMA DRIFT VELOCITY TO BE USED AS
C        SHIFT VECTOR (IPLS IN COMMON COMUSR)
C  IREL: LABEL FOR EL-REACTION, E.G., FOR SIGVEL(IREL)
C        NOT NEEDED FOR NFLAG=2, THEN SET E.G.: IREL=1
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR
      USE EIRMOD_CCONA
      USE EIRMOD_CLOGAU
      USE EIRMOD_CRAND
      USE EIRMOD_CINIT
      USE EIRMOD_CZT1
      USE EIRMOD_CTRCEI
      USE EIRMOD_COMPRT
      USE EIRMOD_COMXS
      USE EIRMOD_CLAST
      USE EIRMOD_RANF, ONLY: RANF_EIRENE

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: RMASS
      REAL(DP), INTENT(IN) :: VXO, VYO, VZO, VLO
      REAL(DP), INTENT(OUT) :: VELQ
      INTEGER, INTENT(IN) :: K, IOLD, NOLD, NFLAG, IREL

      REAL(DP) :: TEST, VRELX,
     .          VXN, VYN, VZN, VXI, VYI, VZI, VRELQ, VN, VREL,
     .          RLMS, RMSI, RMN, RMI, VRELY, EPS, CPH, CHI,
     .          EIRENE_RSTERN, RESULT, SPH, VRSX, VRSY, VRSZ, CEPS,
     .          SEPS, RS,
     .          VSX, VSY, VRYZ, VRELZ, VRQYZ, VSZ, PH, CCHI,
     .          BMAX, ER, ELMIN, ELMAX, B,
     .          VXDR, VYDR, VZDR,
     .          ZARGX, ZARGY, ZARGZ,
     .          VX, VY, VZ, ELAB,
     .          VR, CEL, EIRENE_CROSS, VRQ
ctk      REAL(DP), EXTERNAL :: RANF_EIRENE

      REAL(DP) :: P(9)
      INTEGER :: IFLAG, IRL, IREAC, JM, J, ICOUNT
!  PARAMETERS P_A_B FOR INTERACTION POTENTIALS for A on B collisions
!  ARE NOW READ FROM FILE AMJUEL,
!  NOT HARD-WIRED IN THIS ROUTINE OR (EVEN OLDER VERSIONS)
!  IN FUNTIONS FI, FIVEC
!     DATA P_HE_HE/2.55,2.35,0.90,1.9842,1.3990 ,2.6345  ,0.,-1.9125,0./
!     DATA P_H2_H /2.70,3.00,1.00,2.8355,2.18038,3.490687,0.,-2.025 ,0./
!     DATA P_HE_H /2.00,2.20,0.85,1.4556,0.99699,1.99515 ,0.,-1.5   ,0./
!     DATA P_NE_H /2.28,2.68,0.85,1.8709,1.3870 ,2.4402  ,0.,-1.71  ,0./
!     DATA P_AR_H /4.04,2.50,0.86,2.4756,1.7892 ,3.2737  ,0.,-3.03  ,0./
!     DATA P_KR_H /4.45,2.50,0.80,2.7779,2.0077 ,3.7406  ,0.,-3.3375,0./
!     DATA P_XE_H /6.75,3.80,1.08,3.2882,2.6884 ,3.8436  ,0.,-5.0625,0./
c  special relations for MORSE-Potential functions:
c                iflag=2, projectile A on target B
c                these parameters P(5), P(6), P(8) are also now
c                read from file AMJUEL rather than initialising them here
c       P_A_B(5)=P(4)*(1.-LOG(2.)/P(2))         (=R0, ROOT OF V)
c       P_A_B(6)=P(4)*(1.+LOG(2.)/P(2)/P(3))    (=RW, INFLECTION OF V)
c       P_A_B(8)=-3.*P(1)/4.                    (=V(RW) )
      SAVE
C
c initialize arrays for "on the fly" rejection efficiency estimates
C IFLAG=1 AND IFLAG=3 OPTIONS
      IF (IFIRST.EQ.0) THEN
        IFIRST=1
        DO IRL=1,NRELI
          IFLREL(IRL)=0
          NEMEAN(IRL)=0
          XEMEAN(IRL)=0.D0
        ENDDO
      ENDIF
C
      IF (IFLREL(IREL).EQ.0.AND.NFLAG.NE.2) THEN
        IFLREL(IREL)=-1
C  PREPARE REJECTION SAMPLING OF INCIDENT ION VELOCITY
C  IS CROSS-SECTION AVAILABLE?
        IREAC=MODCOL(5,1,IREL)
        IF (IREAC.EQ.0) GOTO 1
C CURRENTLY: HARD-WIRED SEARCH RANGE
        elmin=log(0.01_dp)
        elmax=log(1.e3_dp)
        SGEVMX(IREL)=-1.D60
        JM=1
        do j=1,1000
c  elab:  here ln(E), with E from 0.01 to 1e3 eV
          elab=elmin+(j-1)/999._dp*(elmax-elmin)

c  find cross-section at ENERGY ELAB from a fit or table.
          CEL=EIRENE_CROSS(ELAB,IREAC,IREL,FACREL(IREL,1),'VELOEL 1')
c
          vrq=exp(elab-defel(IREL))
          vr=sqrt(vrq)
          if (cel*vr.gt.SGEVMX(IREL)) then
            JM=J
            SGEVMX(IREL)=cel*vr
          endif
        enddo

        CALL EIRENE_LEER(1)
        WRITE (iunout,*) 'FIRST CALL TO VELOEL FOR IREL= ',IREL
        WRITE (iunout,*) 'PREPARE REJECTION TECHNIQUE '
        WRITE (iunout,*) 'FIND MAX. "SGCVMX" OF SIGMA(VEL) * VEL '
        CALL EIRENE_MASJ1R('JM, SGEVMX      ',JM, SGEVMX(IREL))
        IF (JM.NE.1.AND.JM.NE.1000) THEN
          elab=elmin+(JM-1)/999.*(elmax-elmin)
          ELAB=EXP(ELAB)
          WRITE (iunout,*) 'TRUE MAXIMUM FOUND AT ELAB(EV) = ',ELAB
          IFLREL(IREL)=1
        ELSE
          WRITE (iunout,*) 'NO TRUE MAXIMUM FOUND, USE WEIGHTING '
        ENDIF
        CALL EIRENE_LEER(1)
      ENDIF
    1 CONTINUE

c  preparations for process IREL done. Start sampling procedure here.
C
C  INITIALIZE COUNTER FOR REJECTION SAMPLING OF INCIDENT BULK PARTICLE
C
      ICOUNT=1
C
C  NEXT: STEP 1
C
C    set parameters for random sampling in cell icell=K
C
      IF (K.GT.0.AND.K.LE.NRAD) THEN  ! K is the grid cell number. Use local bulk medium parameters
c  scaled 1d temperatures, per degree of freedom
        ZARGX=ZRG(IPLS,K)
        ZARGY=ZRG(IPLS,K)
        ZARGZ=ZRG(IPLS,K)
c  drift velocity, cm/s
        IF (NLDRFT) THEN
          IF (INDPRO(4) == 8) THEN
            CALL EIRENE_VECUSR (2,K,X0,Y0,Z0,VXDR,VYDR,VZDR,IPLS,
     .                          .TRUE.)
          ELSE
            VXDR=VXIN(IPLS,K)
            VYDR=VYIN(IPLS,K)
            VZDR=VZIN(IPLS,K)
          END IF
        ELSE
          VXDR=0.D0
          VYDR=0.D0
          VZDR=0.D0
        ENDIF
      ELSE
        GOTO 999
      ENDIF
C
C
C  SAVE VELOCITY VECTOR (CM/S) OF INCIDENT TEST PARTICLE
      VX=VXO*VLO
      VY=VYO*VLO
      VZ=VZO*VLO
C

c   start random sampling here

  123 CONTINUE
      IF (INIV2.LE.0) CALL EIRENE_FGAUSS
C
C  SAMPLE FROM 3D NORMALIZED MAXWELLIAN (m=0;s=1)
      VXN=FG1(INIV2)
      VYN=FG2(INIV2)
      VZN=FG3(INIV2)
      INIV2=INIV2-1
C
      IF (NFLAG.EQ.1) THEN
C  DRIFTING, MONO-ENERGETIC ISOTROPIC DISTRIBUTION
C  ZT1 CORRESPONDS TO MEAN SQUARE VELOCITY AT TIIN(IPLS,K)
        VEL=SQRT(ZT1(IPLS,K))
        VN=VEL/SQRT(VXN*VXN+VYN*VYN+VZN*VZN)
        VXN=VXN*VN+VXDR
        VYN=VYN*VN+VYDR
        VZN=VZN*VN+VZDR
C  ALL OTHER CASES: MAXWELLIAN AT LOCAL TEMPERATURE TIIN AND DRIFT VDR
      ELSE
        VXN=VXN*ZARGX+VXDR
        VYN=VYN*ZARGY+VYDR
        VZN=VZN*ZARGZ+VZDR
      ENDIF
C
C  DRIFTING MAXWELLIAN DISTRIBUTION (FOR MAXWELL-1/r^4-POTENTIAL: SIGMA*V = CONST.)
C
      IF (NFLAG.EQ.2) THEN
C
        VXI=VXN   ! INCIDENT ION VELOCITY; CM/S.
        VYI=VYN
        VZI=VZN

C   NOTHING MORE TO BE DONE

C
      ELSE  !   NFLAG.NE.2, ALL OTHER OPTIONS
C
C   ALL OTHER DISTRIBUTIONS
C
C   WEIGHT CORRECTION DUE TO ENERGY DEPENDENCE IN CROSS-SECTION
C   OR: REJECTION     DUE TO ENERGY DEPENDENCE IN CROSS-SECTION
C   PRESENT VERSION: REJECTION
        VRELQ=MAX((VXN-VX)**2+(VYN-VY)**2+(VZN-VZ)**2,EPS30)
        VREL=SQRT(VRELQ)
        ELAB=LOG(VRELQ)+DEFEL(IREL)
        IREAC=MODCOL(5,1,IREL)
        CEL=EIRENE_CROSS(ELAB,IREAC,IREL,FACREL(IREL,1),'VELOEL 2')
C
c.............................................................
cdr  test output only
c       elb=exp(elab)
c       if (elb.le.0.01) then
c         write (iunout,*) 'elb veloel ',elab,elb
c       endif
cdr
c.....................................................................

C
C       IF (NLREJC) THEN   !  REJECTION IS NOW DEFAULT OPTION
C
        IF (IFLREL(IREL).GT.0) THEN
          TEST=RANF_EIRENE()*SGEVMX(IREL)
          IF (TEST.GT.CEL*VREL) THEN
C  REJECT
            ICOUNT=ICOUNT+1
            IF (ICOUNT.LT.500) GOTO 123  ! fetch a new bulk ion velocity
c  rejection loop failed, too many attempts.
            WRITE (iunout,*)
     .        'ICOUNT TOO LARGE ( > 500) IN VELOEL. ACCEPT SAMPLE '
            WRITE (iunout,*) 'NPANU, IREAC, IREL, ELAB ',
     .                        NPANU, IREAC, IREL, ELAB
          ELSE
C  ACCEPT
            XEMEAN(IREL)=XEMEAN(IREL)+ICOUNT
            NEMEAN(IREL)=NEMEAN(IREL)+1
          ENDIF
C       ELSEIF (NLWEIGHT) THEN

        ELSE
C  FOR SOME REASON SGEVMX COULD NOT BE FOUND, or rejection is too inefficient.
C  SO USE WEIGHTING RATHER THAN REJECTION
          WEIGHT=WEIGHT*CEL*VREL*DIIN(IPLS,K)/SIGVEL(IREL)
        ENDIF
C
        VXI=VXN
        VYI=VYN
        VZI=VZN

C
      ENDIF
C
C  STEP 1 FINISHED, INCIDENT BULK ION (IPLS) VELOCITY IS SET: VXI,VYI,VZI
C
C  FIND TYPE OF COLLISION: IFLAG
C    IFLAG=-1       :  NOTHING TO BE DONE, POST-COLLISION VELOCITY IS ALREADY SAMPLED
C                      FROM MAXWELLIAN
C                      E.G. (relaxation)-BGK APPROXIMATION.
C    IFLAG=0        :  ISOTROPIC, IN CENTER OF MASS
C    IFLAG=IFTFLG>0 :  FIT FORM OF INTERACTION POTENTIAL (ELASTIC COLLISION IREL)
C
C

      IF (NPBGKP(IPLS,1).NE.0.OR.MODCOL(5,0,IREL).EQ.-1) THEN

C  ELASTIC TEST PARTICLE COLLISION IN BGK APPROXIMATION (E.G.: NEUTRAL-NEUTRAL)
C  ENFORCE: EXCHANGE OF IDENTITY COLLISION IN LAB FRAME
C  (AS IT IS ALSO DEFAULT FOR CX COLLISIONS).
C  FOR EQUAL MASSES OF BOTH COLLISION PARTNERS THIS CORRESPONDS
C  TO SCATTERING ANGLE = PI IN COM FRAME
        IFLAG=-1

      ELSEIF (MODCOL(5,0,IREL).EQ.0) THEN
C  NEITHER BGK-TYPE, NOR INTERACTION POTENTIAL PARAMETERS ARE GIVEN
C  USE ISOTROPIC SCATTERING IN CENTER OF MASS FRAME
        IFLAG= 0
C  SOME STUFF HERE FOR COM ISOTROPIC COLLISIONS.....

      ELSEIF (MODCOL(5,0,IREL).GT.0) THEN
C  INTERACTION POTENTIAL IS GIVEN, get fit coefficients of interaction potential
        IREAC=MODCOL(5,0,IREL)
        IFLAG=IFTFLG(IREAC,0)   !cdr  is iftflg correctly set for repulsive potential?
cdr                                check slreac. There default is set to iftflg=2 (Morse)
CDR REACDAT should not be used during trajectory generation, see comments in xstel.f
c   to be done.
        P(1:9)=REACDAT(IREAC)%POT%POLY%DBLPOL(1:9,1)
      ENDIF
C

C
C  NEXT: STEP 2, FIND PRE-COLLISION DATA AND, IF NEEDED, ALSO THE TOTAL CROSS-SECTION
C                IN CASE IFLAG=-1 (RELAXATION COLLISION), NOTHING OF ALL THAT IS NEEDED.
C
      IF (IFLAG.NE.-1) THEN
        RMN=RMASS
        RMI=RMASSP(IPLS)
        RMSI=1./(RMN+RMI)
C  REDUCED MASS
        RLMS=RMN*RMI*RMSI
C  RELATIVE VELOCITY AND RELATED DATA
        VRELX=VX-VXI
        VRELY=VY-VYI
        VRELZ=VZ-VZI
        VRQYZ=         VRELY**2+VRELZ**2
        VRELQ=VRELX**2+VRQYZ
        ER=RLMS*VRELQ*CVELI2
c
        VREL=SQRT(VRELQ)
        VRYZ=SQRT(VRQYZ+EPS60)
C  IMPACT PARAMETER --> SCATTERING ANGLE --> NEW VELOCITY
C  CENTER OF MASS VELOCITY
        VSX=(RMI*VXI+RMN*VX)*RMSI
        VSY=(RMI*VYI+RMN*VY)*RMSI
        VSZ=(RMI*VZI+RMN*VZ)*RMSI
C
C  THAT IS ALL WE NEED FOR ISOTROPIC SCATTERING IN COM SYSTEM
        IF (IFLAG.GT.0) THEN
C
C  TOTAL CROSS-SECTION (ONLY IF NOT ALREADY COMPUTED EARLIER AT THIS CALL)
C  FOR RANDOM SAMPLING OF IMPACT PARAMETER
          IF (NFLAG.NE.3) THEN
C  IN PREVIOUS CALL TO CROSS WE HAD ALREADY SAME PARAMETER VRELQ=|VI-V0|**2
            ELAB=LOG(VRELQ)+DEFEL(IREL)
            IREAC=MODCOL(5,1,IREL)
            IF (IREAC.EQ.0) GOTO 995
            CEL=EIRENE_CROSS(ELAB,IREAC,IREL,FACREL(IREL,1),'VELOEL 3')
          ENDIF
C
C  STEP 2 FINISHED, CROSS-SECTION CEL IS FOUND

C  NEXT: STEP 3 ,  FIND IMPACT PARAMETER B (--> SCATTERING ANGLE --> NEW VELOCITY)

          BMAX=SQRT(CEL*PIAI)/0.52917E-8
          B= SQRT(RANF_EIRENE( ))*BMAX
        END IF

      ENDIF
C
C  STEP 3 FINISHED, COLLISION DATA IN CENTER OF MASS FRAME ARE SET
C         IN CASE IFLAG.GT.0: ALSO IMPACT PARAMETER IS FOUND , IN UNITS: BOHR RADIA
C  NEXT: STEP 4
C
      IF (IFLAG.EQ.-1) THEN
C
C  THIS PART: ONLY (BGK-TYPE) RELAXATION TO A MAXWELLIAN, I.E., POST-COLLISION
C             TEST PARTICLE IS SAMPLED FROM (WEIGHTED OR UNWEIGHTED)
C             BULK POPULATION (E.G.: EL. BGK COLLISION; EXCHANGE OF IDENTITY)
C
        VELQ=VXI*VXI+VYI*VYI+VZI*VZI
        VEL=SQRT(VELQ)
        VN=1./VEL
        VELX=VXI*VN
        VELY=VYI*VN
        VELZ=VZI*VN
C
        GOTO 1000

      ELSEIF (IFLAG.EQ.0) THEN

C   ISOTROPIC SCATTERING ANGLE PH IN CENTER OF MASS FRAME
        CPH=1.0-2.0*RANF_EIRENE( )  ! [-1 1]
        SPH=DSQRT(1.0-CPH*CPH)      ! [ 0 1]
C
      ELSEIF (IFLAG.GT.0) THEN
C
C  THIS PART: FIND DEFLECTION ANGLE
C             BINARY COLLISION KINETICS
C
C  COLLISION PARAMETERS IFLAG, ER AND B ARE DEFINED NOW.
C
C  FIND DISTANCE OF CLOSEST APPROACH: RSTERN
C
        RS=EIRENE_RSTERN(ER,B,IFLAG,P)
C
C  SCATTERING INTEGRAL TO FIND DEFLECTION ANGLE CHI
C
        CALL EIRENE_GAUMEH (RS,ER,B,IFLAG,P,10,1,RESULT)
        CHI=PIA-2.*B/RS*RESULT
        CCHI=COS(CHI)
C
C  CONVERT FROM DEFLECTION ANGLE CHI TO OBSERVABLE SCATTERING ANGLE PH, [0,...,PI]
        PH=ACOS(CCHI)
        CPH=COS(PH)
        SPH=SQRT(1.0-CPH*CPH)
      ENDIF

C  SCATTERING ANGLE PH , COS(PH)=CPH AND SIN(PH)=SPH ARE SET
C
C  POLAR ANGLE
      EPS=PI2A*RANF_EIRENE( )
C
C  CONVERT POST-COLLISON VELOCITY BACK INTO LAB FRAME
C
      CEPS=COS(EPS)
      SEPS=SIN(EPS)
      VRSX=VRELX*CPH+SPH*SEPS*VRYZ
      VRSY=VRELY*CPH+SPH*(VREL*VRELZ*CEPS-VRELX*VRELY*SEPS)/VRYZ
      VRSZ=VRELZ*CPH-SPH*(VREL*VRELY*CEPS+VRELX*VRELZ*SEPS)/VRYZ
C
      VELX=VSX+RLMS/RMN*VRSX
      VELY=VSY+RLMS/RMN*VRSY
      VELZ=VSZ+RLMS/RMN*VRSZ
      VELQ=VELX*VELX+VELY*VELY+VELZ*VELZ
      VEL=SQRT(VELQ)
      VELX=VELX/VEL
      VELY=VELY/VEL
      VELZ=VELZ/VEL

C
C  STEP 4 FINISHED, POST-COLLISION VELOCITY IS SET IN LAB FRAME
C  NEXT: RETURN
C
 1000 CONTINUE
      RETURN
C
  995 CONTINUE
      WRITE (iunout,*) 'ERROR IN VELOEL, NO ELASTIC COLLISION DATA'
      WRITE (iunout,*) 'AVAILABLE '
      WRITE (iunout,*) 'ITYP,IATM,IMOL,IION,IPLS ',
     .                  ITYP,IATM,IMOL,IION,IPLS
      CALL EIRENE_EXIT_OWN(1)
  999 CONTINUE
      WRITE (iunout,*)
     .  'PARAMETER ERROR IN SUBR. VELOCX. EXIT CALLED'
      CALL EIRENE_EXIT_OWN(1)
      END SUBROUTINE EIRENE_VELOEL

C  the following SUBROUTINE is for reinitialization of EIRENE
      SUBROUTINE EIRENE_VELOEL_REINIT
      IMPLICIT NONE
      IFIRST = 0
      return
      END SUBROUTINE EIRENE_VELOEL_REINIT

      END MODULE EIRMOD_VELOEL
