#!/usr/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Read eirene version from version.txt file
eirene_version=$(head -n 1 version.txt)

echo "Running pre-commit hook for EIRENE version" $EIRENE_VERSION

# Set the version text in modules/eirmod_parmmod.f90 to the value in version.txt
src_file="src/modules/eirmod_parmmod.f"
src_new="EIRENE_VERSION_STRING='$eirene_version'"
src_old=$(grep "EIRENE_VERSION_STRING" $src_file | sed 's/[[:blank:]]*$//; s/.*[[:blank:]]//')
if [ "$src_old" != "$src_new" ]; then
    echo "Updating source $src_old to $src_new"
    replace=$(sed -i "s/$src_old/$src_new/" $src_file)
fi

# Set the version text in EPL.md to the value in version.txt
epl_file="EPL.md"
epl_new="Version: $eirene_version"
epl_old=$(grep "Version:" $epl_file )
if [ "$epl_old" != "$epl_new" ]; then
    echo "Updating license $epl_old to $epl_new"
    replace=$(sed -i "s/$epl_old/$epl_new/" $epl_file)
fi

# Set the version text in eirene.txt to the value in version.txt
man_file="Manual/eirene.tex"
man_new="$eirene_version"
man_old=$(awk '/Manual version/{print $4}' $man_file )
man_old=${man_old::-2}
if [ "$man_old" != "$man_new" ]; then
    echo "Updating manual ${man_old/M/} to $man_new"
    replace=$(sed -i "s/$man_old/$man_new/" $man_file)
fi


if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
