      SUBROUTINE EIRENE_ALLOC_COUPLE
      USE EIRMOD_PARMMOD
      USE EIRMOD_BRAEIR
      USE EIRMOD_EIRBRA
      USE EIRMOD_CCOUPL
      USE EIRMOD_COMUSR, ONLY : NMODE

      IF (NMODE .NE. 0) CALL EIRENE_ALLOC_CCOUPL(1)
      CALL EIRENE_ALLOC_CCOUPL(2)

      CALL EIRENE_ALLOC_BRAEIR (NDX,NDY,NFL,IFOFF)
      CALL EIRENE_ALLOC_EIRBRA (NDX,NDY,NFL,NSTRA,IFOFF)

      END SUBROUTINE EIRENE_ALLOC_COUPLE
