      MODULE EIRMOD_CTRCEI
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
 
      IMPLICIT NONE
 
      PRIVATE
 
      PUBLIC :: EIRENE_ALLOC_CTRCEI, EIRENE_DEALLOC_CTRCEI, 
     P          EIRENE_INIT_CTRCEI
 
      LOGICAL, PUBLIC, TARGET, ALLOCATABLE, SAVE :: LTRCEI(:)
 
      LOGICAL, PUBLIC, POINTER, SAVE ::
     L TRCPLT, TRCHST, TRCNAL, TRCMOD, TRCSIG,
     L TRCGRD, TRCSUR, TRCREF, TRCFLE, TRCAMD,
     L TRCINT, TRCLST, TRCSOU, TRCREC, TRCTIM,
     L TRCBLA, TRCBLP, TRCBLE, TRCBLM, TRCBLI,
     L TRCBLPH, TRCTAL

CVK TRACING FOR DEBUGGING VIA WRITE(0,...
      INTEGER,PUBLIC,PARAMETER :: LDBGTRC=9
      LOGICAL, PUBLIC, TARGET, SAVE :: TRCDBG(LDBGTRC)
      LOGICAL, PUBLIC, POINTER, SAVE ::
     L                         TRCDBG2,  !DEEPER LEVEL OF DEBUGGING
     L                         TRCDBGE,  !TRACING OF EIRENE
     L                         TRCDBGM,  !... MCARLO
     L                         TRCDBGF,  !... FOLNEUT
     L                         TRCDBGL,  !... LOCATE
     L
     L                         TRCDBGS,  !... SURFACE INTERACTION ROUTINES
     L                         TRCDBGG,  !... GEOMETRY ROUTINES
     L                         TRCDBGMPI,!... MPI ROUTINES
     L                         TRCDBGC   !... COUPLING ROUTINES
CVK END
 
      LOGICAL, PUBLIC, ALLOCATABLE, SAVE :: TRCSRC(:)
 
!pb      INTEGER, PUBLIC, PARAMETER :: NSPEZV_DIM=100
 
      INTEGER, PUBLIC, TARGET, ALLOCATABLE, SAVE :: ITRCEI(:)
 
      INTEGER, PUBLIC, POINTER, SAVE ::
     I NPRTLV(:), NPRTLS(:), NPRSRF(:),
     I NVOLPR,    NFLAGV(:), NTLVFL(:),
     I NSURPR,    NFLAGS(:), NTLSFL(:),
     I I1TRC,     I2TRC,     NSPCPR
 
      INTEGER, PUBLIC, ALLOCATABLE, SAVE ::
     I NSPEZV(:,:), NSPEZS(:,:)
 
      INTEGER, PUBLIC, SAVE :: MCTRC, LCTRC
 
      CONTAINS
 
 
      SUBROUTINE EIRENE_ALLOC_CTRCEI
 
      IF (ALLOCATED(LTRCEI)) RETURN
 
!pb      MCTRC=5+300+4*NLIMPS
      MCTRC=5+3*NVLPR+4*NSRPR
      LCTRC=22
 
      ALLOCATE (LTRCEI(LCTRC))
      ALLOCATE (ITRCEI(MCTRC))
      ALLOCATE (TRCSRC(0:NSTRA))
!pb      ALLOCATE (NSPEZV(NSPEZV_DIM,2))
      ALLOCATE (NSPEZV(NVLPR,2))
!pb      ALLOCATE (NSPEZS(NLIMPS,2))
      ALLOCATE (NSPEZS(NSRPR,2))
 
      WRITE (55+IFOFF,'(A,T25,I15)')
     .       ' CTRCEI ',(LCTRC+(NSTRA+1))*4
      WRITE (55+IFOFF,'(A,T25,I15)')
     .       ' CTRCEI ',(MCTRC+2*(NVLPR+NSRPR))*4
 
      TRCPLT => LTRCEI( 1)
      TRCHST => LTRCEI( 2)
      TRCNAL => LTRCEI( 3)
      TRCMOD => LTRCEI( 4)
      TRCSIG => LTRCEI( 5)
      TRCGRD => LTRCEI( 6)
      TRCSUR => LTRCEI( 7)
      TRCREF => LTRCEI( 8)
      TRCFLE => LTRCEI( 9)
      TRCAMD => LTRCEI(10)
      TRCINT => LTRCEI(11)
      TRCLST => LTRCEI(12)
      TRCSOU => LTRCEI(13)
      TRCREC => LTRCEI(14)
      TRCTIM => LTRCEI(15)
      TRCBLA => LTRCEI(16)
      TRCBLP => LTRCEI(17)
      TRCBLE => LTRCEI(18)
      TRCBLM => LTRCEI(19)
      TRCBLI => LTRCEI(20)
      TRCBLPH=> LTRCEI(21)
      TRCTAL => LTRCEI(22)

      TRCDBG2  => TRCDBG(1)
      TRCDBGE  => TRCDBG(2)
      TRCDBGM  => TRCDBG(3)
      TRCDBGF  => TRCDBG(4)
      TRCDBGL  => TRCDBG(5)
      TRCDBGS  => TRCDBG(6)
      TRCDBGG  => TRCDBG(7)
      TRCDBGMPI=> TRCDBG(8)
      TRCDBGC  => TRCDBG(9)
 
!      NPRTLV => ITRCEI(  1 : 100)
!      NFLAGV => ITRCEI(101 : 200)
!      NTLVFL => ITRCEI(201 : 300)
!      NPRTLS => ITRCEI(301        : 300+  NLIMPS)
!      NPRSRF => ITRCEI(301+  NLIMPS : 300+2*NLIMPS)
!      NFLAGS => ITRCEI(301+2*NLIMPS : 300+3*NLIMPS)
!      NTLSFL => ITRCEI(301+3*NLIMPS : 300+4*NLIMPS)
!      NVOLPR => ITRCEI(301+4*NLIMPS)
!      NSURPR => ITRCEI(302+4*NLIMPS)
!      I1TRC  => ITRCEI(303+4*NLIMPS)
!      I2TRC  => ITRCEI(304+4*NLIMPS)
!      NSPCPR => ITRCEI(305+4*NLIMPS)
 
      NPRTLV => ITRCEI(1+0*NVLPR : 1*NVLPR)
      NFLAGV => ITRCEI(1+1*NVLPR : 2*NVLPR)
      NTLVFL => ITRCEI(1+2*NVLPR : 3*NVLPR)
      NPRTLS => ITRCEI(1+3*NVLPR : 3*NVLPR + 1*NSRPR)
      NPRSRF => ITRCEI(1+3*NVLPR + 1*NSRPR : 3*NVLPR + 2*NSRPR)
      NFLAGS => ITRCEI(1+3*NVLPR + 2*NSRPR : 3*NVLPR + 3*NSRPR)
      NTLSFL => ITRCEI(1+3*NVLPR + 3*NSRPR : 3*NVLPR + 4*NSRPR)
      NVOLPR => ITRCEI(1+3*NVLPR + 4*NSRPR)
      NSURPR => ITRCEI(2+3*NVLPR + 4*NSRPR)
      I1TRC  => ITRCEI(3+3*NVLPR + 4*NSRPR)
      I2TRC  => ITRCEI(4+3*NVLPR + 4*NSRPR)
      NSPCPR => ITRCEI(5+3*NVLPR + 4*NSRPR)
 
      CALL EIRENE_INIT_CTRCEI
 
      RETURN
      END SUBROUTINE EIRENE_ALLOC_CTRCEI
 
 
      SUBROUTINE EIRENE_DEALLOC_CTRCEI
 
      IF (.NOT.ALLOCATED(LTRCEI)) RETURN
 
      DEALLOCATE (LTRCEI)
      DEALLOCATE (ITRCEI)
      DEALLOCATE (TRCSRC)
      DEALLOCATE (NSPEZV)
      DEALLOCATE (NSPEZS)
 
      RETURN
      END SUBROUTINE EIRENE_DEALLOC_CTRCEI
 
 
      SUBROUTINE EIRENE_INIT_CTRCEI
 
      LTRCEI = .FALSE.
      ITRCEI = 0
      TRCSRC = .FALSE.
      NSPEZV = 0
      NSPEZS = 0
      NFLAGV = 1
      TRCDBG=.FALSE. !VK
 
      RETURN
      END SUBROUTINE EIRENE_INIT_CTRCEI
 
      END MODULE EIRMOD_CTRCEI
