      MODULE EIRMOD_COMUSR
 
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
 
      IMPLICIT NONE
 
      PRIVATE
 
      PUBLIC :: EIRENE_ALLOC_COMUSR, EIRENE_DEALLOC_COMUSR, 
     P          EIRENE_INIT_COMUSR, EIRENE_ALLOC_CORNERS
 
      INTEGER, PUBLIC, SAVE ::
     P NPLPR1, NPLPRM, NSFPRM, NPLPR2,
     P NUSR,   MUSR,   LUSR
 
      REAL(DP), ALLOCATABLE, PUBLIC, SAVE ::
C  NPLPRM, REAL. THE FIRST NPLPR1 DATA ARE SET IN SUBROUTINE PLASMA
     R        TEIN(:),   TIIN(:,:),   DEIN(:),   DIIN(:,:),
     R        VXIN(:,:), VYIN(:,:),   VZIN(:,:),
     R        BXIN(:),   BYIN(:),     BZIN(:),   BFIN(:),
     R        ADIN(:,:), EDRIFT(:,:), VOL(:),    WGHT(:,:),
     R        BXPERP(:), BYPERP(:),
     R        EXIN(:),   EYIN(:),     EZIN(:),   EFIN(:),
C  NSFPRM
     R        FLXOUT(:), SAREA(:),
C  NPLPR2, REAL
     R        TEINL(:),  TIINL(:,:),  DEINL(:),  DIINL(:,:), BVIN(:,:),
     R        PARMOM(:,:),
     R        RMASSI(:), RMASSA(:),   RMASSM(:), RMASSP(:),
     R        DIOD(:),   DATD(:),     DMLD(:),   DPLD(:),    DPHD(:),
     R        DION(:),   DATM(:),     DMOL(:),   DPLS(:),    DPHOT(:)

C     PLASMA PROFILES ON CELL VERTICES   
      REAL(DP), PUBLIC, TARGET, ALLOCATABLE, SAVE ::
     R        CORNER_PROFILES(:,:)

      REAL(DP), POINTER, PUBLIC, SAVE ::    
     .        TEINCORNER(:),   TIINCORNER(:,:), DEINCORNER(:),
     .        DIINCORNER(:,:), 
     .        VXINCORNER(:,:), VYINCORNER(:,:), VZINCORNER(:,:), 
     .        BXINCORNER(:),   BYINCORNER(:),   BZINCORNER(:),
     .        BFINCORNER(:),   BVINCORNER(:,:),
     .        EXCORNER(:),     EYCORNER(:),     EZCORNER(:),
     .        EFCORNER(:)
 
      REAL(DP), PUBLIC, SAVE :: TVAC, DVAC, VVAC, ALLOC
 
      REAL(DP), PUBLIC, ALLOCATABLE, SAVE ::
     R TEDTEDX(:), TEDTEDY(:), TEDTEDZ(:)
 
      CHARACTER(8), ALLOCATABLE, PUBLIC, SAVE :: TEXTS(:)
 
C  MUSR, INTEGER
      INTEGER, PUBLIC, SAVE ::
     I         NSPH  , NPHOTI, NPHOTIM, NPHOTI_IN,
     I         NSPA  , NATMI,  NATMIM,  NATMI_IN,
     I         NSPAM , NMOLI,  NMOLIM,  NMOLI_IN,
     I         NSPAMI, NIONI,  NIONIM,  NIONI_IN,
     I         NSPTOT, NPLSI,  NPLSIM,  NPLSI_IN,
     I         NSNVI,  NCPVI,  NADVI,   NBGVI,
     I         NALVI,  NCLVI,  NADSI,   NALSI, NAINI, NBITS
      INTEGER, ALLOCATABLE, PUBLIC, SAVE ::
     I         NMASSA(:), NCHARA(:), NFOLA(:),  NGENA(:),
     I         NMASSM(:), NCHARM(:), NFOLM(:),  NGENM(:),
     I         NMASSI(:), NCHARI(:), NCHRGI(:), NFOLI(:), NGENI(:),
     I         NMASSP(:), NCHARP(:), NCHRGP(:),
     I         NFOLPH(:), NGENPH(:),
     I         NPRT(:),   ISPEZ(:,:,:,:,:,:),     ISPEZI(:,:),
     I         MPLSTI(:), MPLSV(:)
      INTEGER, ALLOCATABLE, PUBLIC, SAVE ::
     I         ISPZ_BACK(:,:)
 
C  LUSR, LOGICAL
      LOGICAL, ALLOCATABLE, PUBLIC, SAVE ::
     L         LGVAC(:,:), LGDFT(:)

      LOGICAL, PUBLIC, TARGET, ALLOCATABLE, SAVE ::
     L         LSMOPRO(:)

      LOGICAL, PUBLIC, POINTER, SAVE ::
     L         LTESMO, LTISMO, LDESMO, LDISMO,
     L         LVSMO,  LBSMO, LESMO

 
C FROM HERE ON: NO EQUIVALENCE
      INTEGER, ALLOCATABLE, PUBLIC, SAVE ::
     I         IADVE(:),  IADVS(:), IADVT(:),  IADRC(:),
     I         ICLVE(:),  ICLVS(:), ICLVT(:),  ICLRC(:),
     I         ISNVE(:),  ISNVS(:), ISNVT(:),  ISNRC(:),
     I         ICPVE(:),  ICPVS(:), ICPVT(:),  ICPRC(:),
     I         IBGVE(:),  IBGVS(:), IBGVT(:),  IBGRC(:),
     I         IADSE(:),  IADSS(:), IADST(:),  IADSC(:),
     I         NFRSTP(:), NADDP(:), NSPAN(:),  NSPEN(:)
 
      INTEGER, PUBLIC, SAVE ::
     I         NMACH, NMODE,  NTCPU,
     I         NFILE, NFILEN, NFILEM, NFILEL, NFILEK, NFILEJ,
     I         NITER, IITER,  NTIME,  ITIMV
 
      TYPE(SPECT_ARRAY), PUBLIC, ALLOCATABLE, SAVE :: BACK_SPEC(:)
      LOGICAL, PUBLIC, ALLOCATABLE, SAVE :: LSPCCLL(:)
 
 
      CONTAINS
 
 
      SUBROUTINE EIRENE_ALLOC_COMUSR (ICAL)
 
      INTEGER, INTENT(IN) :: ICAL
 

      IF (.NOT.ALLOCATED(LSMOPRO))  ALLOCATE (LSMOPRO(12))

      IF (ICAL == 1) THEN
 
        IF (ALLOCATED(TEIN)) RETURN
 
        NPLPR1=(12+1*NPLS+NPLSTI+3*NPLSV)*NRAD
        NPLPRM=NPLPR1+(NAIN+1+1*NPLS+NSPZMC)*NRAD
        NPLPR2=(2+3*NPLS+NPLSTI)*NRAD+
     .          3*(NATM+NMOL+NION+NPLS)+4+NSPZ+2*NPHOT
        NUSR=NPLPRM+NPLPR2
        MUSR=4*NATM+4*NMOL+5*NION+3*NPLS+30+NSPZ+
     .       6*(1+NPHOTP)*(1+NATMP)*(1+NMOLP)*(1+NIONP)*(1+NPLSP)+NSPZ*6
     .       +2*NPLSI+NSPZ*NPLS
        LUSR=NRAD*(NPLS+2)+NRAD
C
        ALLOCATE (TEIN(NRAD))
        ALLOCATE (TIIN(NPLSTI,NRAD))
        ALLOCATE (DEIN(NRAD))
        ALLOCATE (DIIN(NPLS,NRAD))
        ALLOCATE (VXIN(NPLSV,NRAD))
        ALLOCATE (VYIN(NPLSV,NRAD))
        ALLOCATE (VZIN(NPLSV,NRAD))
        ALLOCATE (BXIN(NRAD))
        ALLOCATE (BYIN(NRAD))
        ALLOCATE (BZIN(NRAD))
        ALLOCATE (BFIN(NRAD))
        ALLOCATE (VOL(NRAD))
        ALLOCATE (WGHT(NSPZMC,NRAD))
        ALLOCATE (BXPERP(NRAD))
        ALLOCATE (BYPERP(NRAD))
        ALLOCATE (EXIN(NRAD))
        ALLOCATE (EYIN(NRAD))
        ALLOCATE (EZIN(NRAD))
        ALLOCATE (EFIN(NRAD))
        ALLOCATE (TEINL(NRAD))
        ALLOCATE (TIINL(NPLSTI,NRAD))
        ALLOCATE (BVIN(NPLSV,NRAD))
        ALLOCATE (PARMOM(NPLS,NRAD))
        ALLOCATE (EDRIFT(NPLS,NRAD))
        ALLOCATE (DEINL(NRAD))
        ALLOCATE (DIINL(NPLS,NRAD))
        ALLOCATE (RMASSI(NION))
        ALLOCATE (RMASSA(NATM))
        ALLOCATE (RMASSM(NMOL))
        ALLOCATE (RMASSP(NPLS))
        ALLOCATE (DIOD(NION))
        ALLOCATE (DATD(NATM))
        ALLOCATE (DMLD(NMOL))
        ALLOCATE (DPLD(NPLS))
        ALLOCATE (DPHD(NPHOT))
        ALLOCATE (DION(NION))
        ALLOCATE (DATM(NATM))
        ALLOCATE (DMOL(NMOL))
        ALLOCATE (DPLS(NPLS))
        ALLOCATE (DPHOT(NPHOT))
 
        ALLOCATE (TEDTEDX(NRTAL))
        ALLOCATE (TEDTEDY(NRTAL))
        ALLOCATE (TEDTEDZ(NRTAL))
 
        ALLOCATE (TEXTS(NSPZ))
        ALLOCATE (NMASSA(NATM))
        ALLOCATE (NCHARA(NATM))
        ALLOCATE (NFOLA(NATM))
        ALLOCATE (NGENA(NATM))
        ALLOCATE (NMASSM(NMOL))
        ALLOCATE (NCHARM(NMOL))
        ALLOCATE (NFOLM(NMOL))
        ALLOCATE (NGENM(NMOL))
        ALLOCATE (NMASSP(NPLS))
        ALLOCATE (NCHARP(NPLS))
        ALLOCATE (NCHRGP(NPLS))
        ALLOCATE (NMASSI(NION))
        ALLOCATE (NCHARI(NION))
        ALLOCATE (NCHRGI(NION))
        ALLOCATE (NFOLI(NION))
        ALLOCATE (NGENI(NION))
        ALLOCATE (NFOLPH(NPHOT))
        ALLOCATE (NGENPH(NPHOT))
        ALLOCATE (NPRT(NSPZ))
        ALLOCATE (ISPEZ(-1:4,0:NPHOTP,0:NATMP,0:NMOLP,0:NIONP,0:NPLSP))
        ALLOCATE (ISPEZI(NSPZ,-1:4))
        ALLOCATE (MPLSTI(NPLS))
        ALLOCATE (MPLSV(NPLS))
        ALLOCATE (ISPZ_BACK(NSPZ,NPLS))
        ALLOCATE (IADVE(NADV))
        ALLOCATE (IADVS(NADV))
        ALLOCATE (IADVT(NADV))
        ALLOCATE (IADRC(NADV))
        ALLOCATE (ICLVE(NCLV))
        ALLOCATE (ICLVS(NCLV))
        ALLOCATE (ICLVT(NCLV))
        ALLOCATE (ICLRC(NCLV))
        ALLOCATE (ISNVE(NSNV))
        ALLOCATE (ISNVS(NSNV))
        ALLOCATE (ISNVT(NSNV))
        ALLOCATE (ISNRC(NSNV))
        ALLOCATE (IADSE(NADS))
        ALLOCATE (IADSS(NADS))
        ALLOCATE (IADST(NADS))
        ALLOCATE (IADSC(NADS))
        ALLOCATE (NFRSTP(NTALI))
        ALLOCATE (NADDP(NTALI))
        ALLOCATE (NSPAN(NTALV))
        ALLOCATE (NSPEN(NTALV))
        ALLOCATE (LGVAC(NRAD,0:NPLS+1))
        ALLOCATE (LGDFT(NRAD))
        ALLOCATE (LSPCCLL(NRAD))
 
        WRITE (55+IFOFF,'(A,T25,I15)')
     .        ' COMUSR(1) ',NUSR*8 + MUSR*4 + (LUSR+12)*4 + 3*NRTAL*8
 
      ELSE IF (ICAL == 2) THEN
 
        IF (ALLOCATED(ADIN)) RETURN
 
        NPLPR1=(12+1*NPLS+NPLSTI+3*NPLSV)*NRAD
        NPLPRM=NPLPR1+(NAIN+1+1*NPLS+NSPZMC)*NRAD
        ALLOCATE (ADIN(NAIN,NRAD))
        ALLOCATE (ICPVE(NCPV))
        ALLOCATE (ICPVS(NCPV))
        ALLOCATE (ICPVT(NCPV))
        ALLOCATE (ICPRC(NCPV))
        ALLOCATE (IBGVE(NBGV))
        ALLOCATE (IBGVS(NBGV))
        ALLOCATE (IBGVT(NBGV))
        ALLOCATE (IBGRC(NBGV))

      ELSE IF (ICAL == 3) THEN
 
        IF (ALLOCATED(FLXOUT)) RETURN
 
        NSFPRM=2*NLMPGS
        ALLOCATE (FLXOUT(NLMPGS))
        ALLOCATE (SAREA(NLMPGS))
 
        WRITE (55+IFOFF,'(A,T25,I15)')
     .         ' COMUSR(3) ',NSFPRM*8
 
      END IF
 
      CALL EIRENE_INIT_COMUSR(ICAL)
 
      RETURN
      END SUBROUTINE EIRENE_ALLOC_COMUSR


 
      SUBROUTINE EIRENE_ALLOC_CORNERS(IUNOUT) 

      INTEGER, INTENT(IN) :: IUNOUT
      INTEGER :: N1DIM(12)
      INTEGER :: NTOT, ICO
      

      IF (ALLOCATED(CORNER_PROFILES)) RETURN

      N1DIM = 0
      NTOT = 0

      IF (LTESMO) NTOT = NTOT + 1
      IF (LTISMO) NTOT = NTOT + NPLSTI
      IF (LDISMO) NTOT = NTOT + NPLS + 1
      IF (LVSMO)  NTOT = NTOT + 4*NPLSV 
      IF (LBSMO)  NTOT = NTOT + 4
      IF (LESMO)  NTOT = NTOT + 4
      
      IF (NTOT > 0) THEN
        ALLOCATE (CORNER_PROFILES(NCORNER,NTOT))
      ELSE
        ALLOCATE (CORNER_PROFILES(1,1))
      END IF

      ICO = 0

      IF (LTESMO) THEN
        TEINCORNER => CORNER_PROFILES(:,ICO+1)
        ICO = ICO + 1
      ELSE
        NULLIFY(TEINCORNER)
      END IF

      IF (LTISMO) THEN
        TIINCORNER => CORNER_PROFILES(:,ICO+1 : ICO+NPLSTI )
        ICO = ICO + NPLSTI
      ELSE
        NULLIFY(TIINCORNER)
      END IF

      IF (LDISMO) THEN
        DEINCORNER => CORNER_PROFILES(:,ICO+1)
        DIINCORNER => CORNER_PROFILES(:,ICO+2 : ICO+NPLS+1 )
        ICO = ICO + NPLS + 1
      ELSE
        NULLIFY(DEINCORNER)
        NULLIFY(DIINCORNER)
      END IF

      IF (LVSMO) THEN
        VXINCORNER => CORNER_PROFILES(:,ICO+1 : ICO+NPLSV )
        VYINCORNER => CORNER_PROFILES(:,ICO+1+1*NPLSV : ICO+2*NPLSV )
        VZINCORNER => CORNER_PROFILES(:,ICO+1+2*NPLSV : ICO+3*NPLSV )
        BVINCORNER => CORNER_PROFILES(:,ICO+1+3*NPLSV : ICO+4*NPLSV )
        ICO = ICO + 4*NPLSV
      ELSE
        NULLIFY(VXINCORNER)
        NULLIFY(VYINCORNER)
        NULLIFY(VZINCORNER)
        NULLIFY(BVINCORNER)
      END IF

      IF (LBSMO) THEN
        BXINCORNER => CORNER_PROFILES(:,ICO+1)
        BYINCORNER => CORNER_PROFILES(:,ICO+2)
        BZINCORNER => CORNER_PROFILES(:,ICO+3)
        BFINCORNER => CORNER_PROFILES(:,ICO+4)
        ICO = ICO + 4
      ELSE
        NULLIFY(BXINCORNER)
        NULLIFY(BYINCORNER)
        NULLIFY(BZINCORNER)
        NULLIFY(BFINCORNER)
      END IF

      IF (LESMO) THEN
        EXCORNER => CORNER_PROFILES(:,ICO+1)
        EYCORNER => CORNER_PROFILES(:,ICO+2)
        EZCORNER => CORNER_PROFILES(:,ICO+3)
        EFCORNER => CORNER_PROFILES(:,ICO+4)
        ICO = ICO + 4
      ELSE
        NULLIFY(EXCORNER)
        NULLIFY(EYCORNER)
        NULLIFY(EZCORNER)
        NULLIFY(EFCORNER)
      END IF

      IF (ICO /= NTOT) THEN
        WRITE (IUNOUT,*) ' ERROR IN EIRENE_ALLOC_CORNERS '
        WRITE (IUNOUT,*) ' NTOT = ',NTOT,' /= ICO = ',ICO
        CALL EIRENE_EXIT_OWN(1)
      END IF

      CORNER_PROFILES = 0._DP        

      END SUBROUTINE EIRENE_ALLOC_CORNERS
 


      SUBROUTINE EIRENE_DEALLOC_COMUSR
C
      IF (.NOT.ALLOCATED(TEIN)) RETURN
 
      DEALLOCATE (TEIN)
      DEALLOCATE (TIIN)
      DEALLOCATE (DEIN)
      DEALLOCATE (DIIN)
      DEALLOCATE (VXIN)
      DEALLOCATE (VYIN)
      DEALLOCATE (VZIN)
      DEALLOCATE (BXIN)
      DEALLOCATE (BYIN)
      DEALLOCATE (BZIN)
      DEALLOCATE (BFIN)
      DEALLOCATE (ADIN)
      DEALLOCATE (VOL)
      DEALLOCATE (WGHT)
      DEALLOCATE (BXPERP)
      DEALLOCATE (BYPERP)
      DEALLOCATE (EXIN)
      DEALLOCATE (EYIN)
      DEALLOCATE (EZIN)
      DEALLOCATE (EFIN)
      DEALLOCATE (FLXOUT)
      DEALLOCATE (SAREA)
      DEALLOCATE (TEINL)
      DEALLOCATE (TIINL)
      DEALLOCATE (BVIN)
      DEALLOCATE (PARMOM)
      DEALLOCATE (EDRIFT)
      DEALLOCATE (DEINL)
      DEALLOCATE (DIINL)
      DEALLOCATE (RMASSI)
      DEALLOCATE (RMASSA)
      DEALLOCATE (RMASSM)
      DEALLOCATE (RMASSP)
      DEALLOCATE (DIOD)
      DEALLOCATE (DATD)
      DEALLOCATE (DMLD)
      DEALLOCATE (DPLD)
      DEALLOCATE (DPHD)
      DEALLOCATE (DION)
      DEALLOCATE (DATM)
      DEALLOCATE (DMOL)
      DEALLOCATE (DPLS)
      DEALLOCATE (DPHOT)
 
      DEALLOCATE (TEDTEDX)
      DEALLOCATE (TEDTEDY)
      DEALLOCATE (TEDTEDZ)
 
      DEALLOCATE (TEXTS)
      DEALLOCATE (NMASSA)
      DEALLOCATE (NCHARA)
      DEALLOCATE (NFOLA)
      DEALLOCATE (NGENA)
      DEALLOCATE (NMASSM)
      DEALLOCATE (NCHARM)
      DEALLOCATE (NFOLM)
      DEALLOCATE (NGENM)
      DEALLOCATE (NMASSP)
      DEALLOCATE (NCHARP)
      DEALLOCATE (NCHRGP)
      DEALLOCATE (NMASSI)
      DEALLOCATE (NCHARI)
      DEALLOCATE (NCHRGI)
      DEALLOCATE (NFOLI)
      DEALLOCATE (NGENI)
      DEALLOCATE (NFOLPH)
      DEALLOCATE (NGENPH)
      DEALLOCATE (NPRT)
      DEALLOCATE (ISPEZ)
      DEALLOCATE (ISPEZI)
      DEALLOCATE (MPLSTI)
      DEALLOCATE (MPLSV)
      DEALLOCATE (ISPZ_BACK)
      DEALLOCATE (IADVE)
      DEALLOCATE (IADVS)
      DEALLOCATE (IADVT)
      DEALLOCATE (IADRC)
      DEALLOCATE (ICLVE)
      DEALLOCATE (ICLVS)
      DEALLOCATE (ICLVT)
      DEALLOCATE (ICLRC)
      DEALLOCATE (ISNVE)
      DEALLOCATE (ISNVS)
      DEALLOCATE (ISNVT)
      DEALLOCATE (ISNRC)
      DEALLOCATE (ICPVE)
      DEALLOCATE (ICPVS)
      DEALLOCATE (ICPVT)
      DEALLOCATE (ICPRC)
      DEALLOCATE (IBGVE)
      DEALLOCATE (IBGVS)
      DEALLOCATE (IBGVT)
      DEALLOCATE (IBGRC)
      DEALLOCATE (IADSE)
      DEALLOCATE (IADSS)
      DEALLOCATE (IADST)
      DEALLOCATE (IADSC)
      DEALLOCATE (NFRSTP)
      DEALLOCATE (NADDP)
      DEALLOCATE (NSPAN)
      DEALLOCATE (NSPEN)
      DEALLOCATE (LGVAC)
      DEALLOCATE (LGDFT)
      DEALLOCATE (LSPCCLL)
      DEALLOCATE (LSMOPRO)
 
!pb      IF (NBACK_SPEC > 0) DEALLOCATE (BACK_SPEC)
      IF (ALLOCATED(BACK_SPEC)) DEALLOCATE (BACK_SPEC)

      IF (ALLOCATED(CORNER_PROFILES)) DEALLOCATE (CORNER_PROFILES)

      RETURN
      END SUBROUTINE EIRENE_DEALLOC_COMUSR
 
 
      SUBROUTINE EIRENE_INIT_COMUSR(ICAL)
 
      INTEGER, INTENT(IN) :: ICAL
      INTEGER, SAVE :: IFIRST=0

      IF (IFIRST == 0) THEN
        LSMOPRO = .FALSE.

        LTESMO => LSMOPRO(1) 
        LTISMO => LSMOPRO(2) 
        LDISMO => LSMOPRO(3)
        LVSMO  => LSMOPRO(4)  
        LBSMO  => LSMOPRO(5) 
        LESMO  => LSMOPRO(6)

        IFIRST = 1
      ENDIF
 
      IF (ICAL == 1) THEN
 
        TEIN   = 0._DP
        TIIN   = 0._DP
        DEIN   = 0._DP
        DIIN   = 0._DP
        VXIN   = 0._DP
        VYIN   = 0._DP
        VZIN   = 0._DP
        BXIN   = 0._DP
        BYIN   = 0._DP
        BZIN   = 0._DP
        BFIN   = 0._DP
        VOL    = 0._DP
        WGHT   = 1._DP
        BXPERP = 0._DP
        BYPERP = 0._DP
        EXIN   = 0._DP
        EYIN   = 0._DP
        EZIN   = 0._DP
        EFIN   = 0._DP
        TEINL  = 0._DP
        TIINL  = 0._DP
        BVIN   = 0._DP
        PARMOM = 0._DP
        EDRIFT = 0._DP
        DEINL  = 0._DP
        DIINL  = 0._DP
        RMASSI = 0._DP
        RMASSA = 0._DP
        RMASSM = 0._DP
        RMASSP = 0._DP
        DIOD   = 0._DP
        DATD   = 0._DP
        DMLD   = 0._DP
        DPLD   = 0._DP
        DPHD   = 0._DP
        DION   = 0._DP
        DATM   = 0._DP
        DMOL   = 0._DP
        DPLS   = 0._DP
        DPHOT  = 0._DP
 
        TEDTEDX = 0._DP
        TEDTEDY = 0._DP
        TEDTEDZ = 0._DP
 
        TEXTS  = ' '
        NMASSA = 0
        NCHARA = 0
        NFOLA  = 0
        NGENA  = 0
        NMASSM = 0
        NCHARM = 0
        NFOLM  = 0
        NGENM  = 0
        NMASSP = 0
        NCHARP = 0
        NCHRGP = 0
        NMASSI = 0
        NCHARI = 0
        NCHRGI = 0
        NFOLI  = 0
        NGENI  = 0
        NFOLPH = 0
        NGENPH = 0
        NPRT   = 0
        ISPEZ  = 0
        ISPEZI = 0
        MPLSTI = 0
        MPLSV  = 0
        ISPZ_BACK = 0
        IADVE  = 0
        IADVS  = 0
        IADVT  = 0
        IADRC  = 0
        ICLVE  = 0
        ICLVS  = 0
        ICLVT  = 0
        ICLRC  = 0
        ISNVE  = 0
        ISNVS  = 0
        ISNVT  = 0
        ISNRC  = 0
        IADSE  = 0
        IADSS  = 0
        IADST  = 0
        IADSC  = 0
        NFRSTP = 0
        NADDP  = 0
        NSPAN  = 0
        NSPEN  = 0
        LGVAC  = .FALSE.
        LGDFT  = .FALSE.
        LSPCCLL = .FALSE.
 
      ELSE IF (ICAL == 2) THEN
 
        ADIN   = 0._DP
        ICPVE  = 0
        ICPVS  = 0
        ICPVT  = 0
        ICPRC  = 0
        IBGVE  = 0
        IBGVS  = 0
        IBGVT  = 0
        IBGRC  = 0
 
      ELSE IF (ICAL == 3) THEN
 
        FLXOUT = 0._DP
        SAREA  = 666._DP
 
      END IF
 
      RETURN
      END SUBROUTINE EIRENE_INIT_COMUSR
 
      END MODULE EIRMOD_COMUSR
