C
C
C
      SUBROUTINE EIRENE_GEOUSR
C
C   PREPARE DATA FOR LIMITER-SURFACES
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMPRT

      IMPLICIT NONE

      CHARACTER(80) :: ZEILE
      integer, save :: ifirst=0

      if (ifirst /= 0) return
      ifirst=1

      READ (IUNIN,'(A80)') ZEILE
      READ (IUNIN,'(A80)') ZEILE

      CALL EIRENE_UPPERCASE(ZEILE)
      
      IF (INDEX(ZEILE,'GENERAL') /= 0) THEN
        CALL EIRENE_GEOUSR_GENERAL
      ELSE
        BACKSPACE(IUNIN)
        CALL EIRENE_GEOUSR_BIASED
      END IF
 
      RETURN
      END
