 
 
      SUBROUTINE EIRENE_PLAUSR
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR
      USE EIRMOD_CSTEP
      USE EIRMOD_CGRID
      USE EIRMOD_CINIT
      USE EIRMOD_COMSOU
      IMPLICIT NONE
      REAL(DP) :: FACTOR, STEP
      INTEGER :: IG, IR, IT, IN, IP, IPLS, NRWL
      REAL(DP) :: XMACH
 
 
      RETURN
      END
