      SUBROUTINE EIRENE_FIND_PARAM(STANDARD_INPUT)
C
C   SET DIMENSIONS (PARAMETERS) FOR ALLOCATABLE ARRAYS (TALLIES, GRIDS, ETC..) AND SET SOME FURTHER DEFAULT VALUES
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CLOGAU, ONLY: EIRENE_ALLOC_CLOGAU
      USE EIRMOD_COMPRT, ONLY: IUNIN, IUNOUT
      USE EIRMOD_CPES, ONLY: NPRS
 
      IMPLICIT NONE
      INTEGER, INTENT(IN) :: STANDARD_INPUT
      INTEGER :: IUNIN_OLD
      character(80) :: ZEILE
      LOGICAL :: UEX
C
C  UNIT NUMBER FOR INPUT FILE: MUST BE DIFFERENT FROM: 5,8,10,11,12
C  13,14, AND 15
C    
      IF (STANDARD_INPUT.EQ.0) THEN  !XPB CALL FROM EIRENE_MAIN
        IF (NPRS.GT.1) THEN
          IUNIN=1+IFOFF !VK SWITCHING TO READING FROM FORT.1
        ELSE
          INQUIRE(UNIT=1+IFOFF,EXIST=UEX)
          IF (UEX) THEN
            IUNIN=1+IFOFF
          ELSE
            IUNIN=5 !VK "NORMAL" READING
          ENDIF
        END IF
      ELSE
        IUNIN=STANDARD_INPUT !VK !XPB PASSED AS ARGUMENT SO B2PLOT AND B2MDS CAN WORK
      ENDIF
      IF (IUNIN.EQ.5.OR.IUNIN.EQ.8.OR.IUNIN.EQ.10.OR.
     .    IUNIN.EQ.11.OR.IUNIN.EQ.12.OR.IUNIN.EQ.13.OR.
     .    IUNIN.EQ.14.OR.IUNIN.EQ.15) THEN
        WRITE (IUNOUT,*) 'INVALID INPUT STREAM IUNIN: ',IUNIN
        WRITE (IUNOUT,*) 'ERROR EXIT FROM FIND_PARAM.F      '
        CALL EIRENE_EXIT_OWN(1)
      ENDIF  

      IF (IUNIN.NE.5) THEN
        INQUIRE(UNIT=IUNIN,OPENED=UEX)
        IF (UEX) THEN
          REWIND IUNIN
        ELSE
          OPEN(UNIT=IUNIN,ACCESS='SEQUENTIAL',FORM='FORMATTED',
     .         ERR=7999)
        ENDIF
      ENDIF
C
      CALL EIRENE_ALLOC_CLOGAU
      IUNIN_OLD = IUNIN
      CALL EIRENE_DEFAULTS_USR
CNH   24.08.2020
C     Add IFOFF again if IUNIN is adapted in EIRENE_DEFAULTS_USR.
      IF (IUNIN.NE.IUNIN_OLD) THEN
        IUNIN = IUNIN + IFOFF
      ENDIF
 
      REWIND IUNIN

      READ (IUNIN,'(A80)') ZEILE
      
      REWIND IUNIN

      IF (ZEILE(1:1) == '*') THEN
        CALL EIRENE_FIND_PARAM_FIXFORM
      ELSE IF (ZEILE(1:1) == '{') THEN
        close (unit=iunin)
        CALL EIRENE_FIND_PARAM_JSON
      ELSE
        WRITE (IUNOUT,'(A,I0,A)')
     .    ' EIRENE INPUT FORT.',iunin,' HAS WRONG FORMAT'
        CALL EIRENE_EXIT_OWN(1)
      END IF

      RETURN

 7999 WRITE (IUNOUT,*) 'Could not open input file!'
      CALL EIRENE_EXIT_OWN(1)
      RETURN
      
      end subroutine eirene_find_param
