      subroutine eirene_find_param

      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CLOGAU, ONLY: EIRENE_ALLOC_CLOGAU
      USE EIRMOD_COMPRT, ONLY: IUNIN, IUNOUT
 
      IMPLICIT NONE
      character(80) :: ZEILE
C
C  UNIT NUMBER FOR INPUT FILE: MUST BE DIFFERENT FROM: 5,8,10,11,12
C  13,14, AND 15
C    
      IF (IUNIN.EQ.5.OR.IUNIN.EQ.8.OR.IUNIN.EQ.10.OR.
     .    IUNIN.EQ.11.OR.IUNIN.EQ.12.OR.IUNIN.EQ.13.OR.
     .    IUNIN.EQ.14.OR.IUNIN.EQ.15) THEN
        WRITE (IUNOUT,*) 'INVALID INPUT STREAM IUNIN: ',IUNIN
        WRITE (IUNOUT,*) 'ERROR EXIT FROM FIND_PARAM.F      '
        CALL EIRENE_EXIT_OWN(1)
      ENDIF  

      CALL EIRENE_ALLOC_CLOGAU
      CALL EIRENE_DEFAULTS_USR
 
      REWIND IUNIN

      READ (IUNIN,'(A80)') ZEILE
      
      REWIND IUNIN

      IF (ZEILE(1:1) == '*') THEN
        CALL EIRENE_FIND_PARAM_FIXFORM
      ELSE IF (ZEILE(1:1) == '{') THEN
        close (unit=iunin)
        CALL EIRENE_FIND_PARAM_JSON
      ELSE
        WRITE (IUNOUT,'(A,I0,A)')
     .    ' EIRENE INPUT FORT.',iunin,' HAS WRONG FORMAT'
        CALL EIRENE_EXIT_OWN(1)
      END IF

      RETURN
      
      end subroutine eirene_find_param
