
      SUBROUTINE EIRENE_PREP_PLOTTING
      USE EIRMOD_CPLOT
      USE EIRMOD_CGRID
      USE EIRMOD_CLOGAU
      USE EIRMOD_CTRCEI
      USE EIRMOD_CPL3D
      USE EIRMOD_CGRPTL
      USE EIRMOD_CADGEO
      USE EIRMOD_CLGIN
      IMPLICIT NONE
C     
C  PLOTTING AND TEXT
C
      IF (NPLOTR.LE.0) NPLOTR=NR1ST
      IF (NPLOTP.LE.0) NPLOTP=NP2ND
      IF (NPLOTT.LE.0) NPLOTT=NT3RD
      NPLOTR=MIN0(NPLOTR,NR1ST)
      if (nltri.or.nltet) NPLOTR=MIN0(NPLOTR,NR1ST-1)
      NPLINR=MAX0(NPLINR,1)
      NPLDLR=MAX0(NPLDLR,1)
      NPLOTP=MIN0(NPLOTP,NP2ND)
      NPLINP=MAX0(NPLINP,1)
      NPLDLP=MAX0(NPLDLP,1)
      NPLOTT=MIN0(NPLOTT,NT3RD)
      NPLINT=MAX0(NPLINT,1)
      NPLDLT=MAX0(NPLDLT,1)
      PL1ST=PL1ST.AND.NR1ST.GT.1
      PL2ND=PL2ND.AND.NP2ND.GT.1
      PL3RD=PL3RD.AND.NT3RD.GT.1
      PLADD=PLADD.AND.NLIMI.GT.0
      NLPL2D=(PL1ST.OR.PL2ND.OR.PL3RD.OR.PLADD).AND.
     .       (PLCUT(1).OR.PLCUT(2).OR.PLCUT(3))
      NLPL3D=PL3A(1).OR.PL3A(2).OR.PL3A(3).OR.PL3A(4).OR.PL3A(5).OR.
     .       PL3S(1).OR.PL3S(2).OR.PL3S(3)
      PLHST=PLHST.AND.(NLPL2D.OR.NLPL3D)
      PLCHOR=PLCHOR.AND.NVOLPL.EQ.0
      TRCSUR=TRCSUR.AND.(NLIMI.GT.0.OR.NSTSI.GT.0)
      LPRADR=.FALSE.
      LPPOLR=.FALSE.
      LPTORR=.FALSE.

      IF ((NVOLPL > 0) .AND.
     .    (ANY(PLTL2D(1:NVOLPL)) .OR.
     .    (ANY(PLTL3D(1:NVOLPL)).AND.LEVGEO<=3))) 
     .  CALL EIRENE_ALLOC_CGRPTL

      RETURN
      END SUBROUTINE EIRENE_PREP_PLOTTING
