
      SUBROUTINE EIRENE_PREP_STRATA

      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMSOU
      USE EIRMOD_CINIT
      USE EIRMOD_CCONA
      USE EIRMOD_COMPRT, ONLY : IUNOUT

      IMPLICIT NONE

      INTEGER :: ISTRA, ISTRAI
      REAL(DP) :: THMAX, RP1

      NLSYMT(0)=.TRUE.
      NLSYMP(0)=.TRUE.
      DO ISTRAI=1,NSTRAI
        ISTRA=ISTRAI
        IF (INDSRC(ISTRA).EQ.6) CYCLE

        IF (.NOT.NLSRF(ISTRA))
     .    THMAX=MAX(0._DP,MIN(PIA,SORMAX(ISTRA)*DEGRAD))
        IF (NLSRF(ISTRA))
     .    THMAX=MAX(0._DP,MIN(PIHA,SORMAX(ISTRA)*DEGRAD))
        IF (NAMODS(ISTRA).EQ.1) THEN
          RP1=SORCOS(ISTRA)+1.
          SORCOS(ISTRA)=1./RP1
!pb          IF (ABS(COS(THMAX)).LE.EPS10) THEN
          IF (ABS(COS(THMAX)).LE.EPS5) THEN
            SORMAX(ISTRA)=1.
          ELSE
            SORMAX(ISTRA)=1.-COS(THMAX)**RP1
          ENDIF
        ELSEIF (NAMODS(ISTRA).EQ.2) THEN
          SORCOS(ISTRA)=SORCOS(ISTRA)*DEGRAD
          SORMAX(ISTRA)=THMAX
        ELSE
          WRITE (iunout,*) 'INPUT ERROR: ISTRA,NAMODS(ISTRA)='
          WRITE (iunout,*) '             ',ISTRA,NAMODS(ISTRA)
          CALL EIRENE_EXIT_OWN(1)
        ENDIF
        NLSYMT(0)=NLSYMT(0).AND.NLSYMT(ISTRA)
        NLSYMP(0)=NLSYMP(0).AND.NLSYMP(ISTRA)
      END DO

      RETURN
      END SUBROUTINE EIRENE_PREP_STRATA
