CDR  june 17: COMMENTS, MINOR NOTATIONAL CHANGES
C
C
C
      SUBROUTINE EIRENE_PROFE(PRO,PRO0,RIN0,A1,E,SEP,PROVAC)
C
C  EXPONENTIAL PROFILE, PLUS CONTINUATION EXPONENTIAL DECAY BEYOND "SEP"
C  
C  PRO(X) =  PRO0   *EXP(-(X-RIN0)/A1)  FOR RINP0 <= X <= SEP
C  PRO(X) =  PROSEP *EXP(-(X-SEP)/A1)   FOR SEP   <= X <= RAA  
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CCONA
      USE EIRMOD_CGRID
      USE EIRMOD_COMPRT, ONLY: IUNOUT
 
      IMPLICIT NONE
 
      REAL(DP), INTENT(IN) :: PRO0, RIN0, A1, E, SEP, PROVAC
      REAL(DP), INTENT(OUT) :: PRO(*)
      REAL(DP) :: EP1R, ELLR, YR, EIRENE_AREAA, ARCA, RHO0, ZR,
     .            AR, DIST, PROSEP, RHOSEP
      INTEGER :: J, JM1, EIRENE_LEARCA, NLOCAL
 
      RHOSEP=SEP
      RHO0=RIN0
      IF (LEVGEO.LE.2) THEN
        IF (RRA.GT.RAA) THEN
          NLOCAL=NR1STM
          PRO(NR1STM)=PROVAC
        ELSE
          NLOCAL=NR1ST
        ENDIF
C
C FIND modified RADIAL SURFACE LABELING CO-ORDINATES RHO      AT "SEP"  :RHOSEP 
C                                                         AND AT "RIN0" :RHO0
C
        IF (LEVGEO.EQ.2) THEN
          JM1=EIRENE_LEARCA(RHOSEP,RSURF,1,NLOCAL,1,'PROFE       ')
          AR=EIRENE_AREAA (RHOSEP,JM1,ARCA,YR,EP1R,ELLR)
          RHOSEP=SQRT(AR*PIAI)
          JM1=EIRENE_LEARCA(RHO0,RSURF,1,NLOCAL,1,'PROFE       ')
          AR=EIRENE_AREAA (RHO0,JM1,ARCA,YR,EP1R,ELLR)
          RHO0=SQRT(AR*PIAI)
        ENDIF

      ELSE
        WRITE (iunout,*)
     .  'WARNING: PROFE CALLED WITH LEVGEO.GT.2 '
        WRITE (iunout,*) 'NO PLASMA PARAMETERS RETURNED'
        RETURN
      ENDIF
C
C  VALUE OF PRO AT RHOSEP: PROSEP 
      DIST=RHOSEP-RHO0
      PROSEP=PRO0*EXP(-DIST/A1)
C
      DO 20 J=1,NLOCAL-1
C  1ST EXPONENTIAL
        IF (RHOZNE(J).LE.RHOSEP) THEN
          ZR=RHOZNE(J)-RHO0
          PRO(J)=PRO0*EXP(-ZR/A1)
        ELSE
C  2ND EXPONENTIAL
          ZR=RHOZNE(J)-RHOSEP
          PRO(J)=PROSEP*EXP(-ZR/E)
        ENDIF
20    CONTINUE
      PRO(NR1ST)=0.
      RETURN
      END
