C
      SUBROUTINE EIRENE_PROFS(PRO,PRO0,PRO1,SEP,PROVAC)
C
C  2-STEP PROFILE, VALUES PRO1, PRO2, 1:NR1ST, STEP AT  POSITION SEP
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CCONA
      USE EIRMOD_CGRID
      USE EIRMOD_COMPRT, ONLY: IUNOUT
 
      IMPLICIT NONE
 
      REAL(DP), INTENT(IN) :: PRO0, PRO1, SEP, PROVAC
      REAL(DP), INTENT(OUT) :: PRO(*)
      REAL(DP) :: EIRENE_AREAA, ARCA, AR, ELLR, YR, EP1R, RHOSEP
      INTEGER :: EIRENE_LEARCA, J, NLOCAL, JM1
 
      RHOSEP=SEP
      IF (LEVGEO.LE.3) THEN
        IF (RRA.GT.RAA) THEN
          NLOCAL=NR1STM
          PRO(NR1STM)=PROVAC
        ELSE
          NLOCAL=NR1ST
        ENDIF
C
C FIND X SURFACE OR RADIAL SURFACE LABELING CO-ORDINATE AT "SEP"
C
        select case (LEVGEO)
        case (1,3)
          RHOSEP=SEP
        case (2)
          JM1=EIRENE_LEARCA(SEP,RSURF,1,NLOCAL,1,'PROFS       ')
          AR=EIRENE_AREAA (SEP,JM1,ARCA,YR,EP1R,ELLR)
          RHOSEP=SQRT(AR*PIAI)
        end select
      ELSE
        WRITE (iunout,*)
     .  'WARNING: PROFS CALLED WITH LEVGEO.GT.3 '
        WRITE (iunout,*) 'CONSTANT PLASMA PARAMETERS RETURNED'
        NLOCAL=NR1ST
        DO 25 J=1,NLOCAL-1
          PRO(J)=PRO0
25      CONTINUE
        PRO(NR1ST)=0.
        RETURN
      ENDIF
C
      DO 20 J=1,NLOCAL-1
        IF (RHOZNE(J).GT.RHOSEP) GOTO 15
        PRO(J)=PRO0
        GOTO 20
15      PRO(J)=PRO1
20    CONTINUE
      PRO(NR1ST)=0.
      RETURN
      END
