
      SUBROUTINE EIRENE_SETUP_ISPEZ
C
C  SET SOME ARRAYS TO SPEED UP COMPUTATIONS
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR

      IMPLICIT NONE

      INTEGER :: IPH, IA, IM, II, IP, IZ
      
C  1ST: SPECIES FLAGS:
      DO IPH=0,NPHOTP
      DO IA=0,NATMP
      DO IM=0,NMOLP
      DO II=0,NIONP
      DO IP=0,NPLSP
        ISPEZ(-1,IPH,IA,IM,II,IP)=-1
        ISPEZ(0,IPH,IA,IM,II,IP)=IPH
        ISPEZ(1,IPH,IA,IM,II,IP)=NPHOTI+IA
        ISPEZ(2,IPH,IA,IM,II,IP)=NPHOTI+NATMI+IM
        ISPEZ(3,IPH,IA,IM,II,IP)=NPHOTI+NATMI+NMOLI+II
        ISPEZ(4,IPH,IA,IM,II,IP)=NPHOTI+NATMI+NMOLI+NIONI+IP
      ENDDO
      ENDDO
      ENDDO
      ENDDO
      ENDDO
      DO IZ=1,NPHOTI
        ISPEZI(IZ,-1)=0
        ISPEZI(IZ,0)=IZ
        ISPEZI(IZ,1)=0
        ISPEZI(IZ,2)=0
        ISPEZI(IZ,3)=0
        ISPEZI(IZ,4)=0
      ENDDO
      DO IZ=NPHOTI+1,NPHOTI+NATMI
        ISPEZI(IZ,-1)=1
        ISPEZI(IZ,0)=0
        ISPEZI(IZ,1)=IZ-NPHOTI
        ISPEZI(IZ,2)=0
        ISPEZI(IZ,3)=0
        ISPEZI(IZ,4)=0
      ENDDO
      DO IZ=NPHOTI+NATMI+1,NPHOTI+NATMI+NMOLI
        ISPEZI(IZ,-1)=2
        ISPEZI(IZ,0)=0
        ISPEZI(IZ,1)=0
        ISPEZI(IZ,2)=IZ-NPHOTI-NATMI
        ISPEZI(IZ,3)=0
        ISPEZI(IZ,4)=0
      ENDDO
      DO IZ=NPHOTI+NATMI+NMOLI+1,NPHOTI+NATMI+NMOLI+NIONI
        ISPEZI(IZ,-1)=3
        ISPEZI(IZ,0)=0
        ISPEZI(IZ,1)=0
        ISPEZI(IZ,2)=0
        ISPEZI(IZ,3)=IZ-NPHOTI-NATMI-NMOLI
        ISPEZI(IZ,4)=0
      ENDDO
      DO IZ=NPHOTI+NATMI+NMOLI+NIONI+1,NPHOTI+NATMI+NMOLI+NIONI+NPLSI
        ISPEZI(IZ,-1)=4
        ISPEZI(IZ,0)=0
        ISPEZI(IZ,1)=0
        ISPEZI(IZ,2)=0
        ISPEZI(IZ,3)=0
        ISPEZI(IZ,4)=IZ-NPHOTI-NATMI-NMOLI-NIONI
      ENDDO
      
      RETURN
      END SUBROUTINE EIRENE_SETUP_ISPEZ
