
      SUBROUTINE EIRENE_SETUP_ATOMIC_WEIGHTS
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_COMUSR
      USE EIRMOD_CZT1
      USE EIRMOD_CCONA

      IMPLICIT NONE

      INTEGER :: JATM, JMOL, JION, JPLS
C
C
C  ATOMIC WEIGHT OF TEST IONS = RMASSI(JION)
      DO JION=1,NIONI
        RMASSI(JION)=NMASSI(JION)*PMASSA
        RSQDVI(JION)=1._DP/SQRT(RMASSI(JION))*CVELAA
        CVRSSI(JION)=RMASSI(JION)*CVELI2
        ALMASI(JION)=LOG10(RMASSI(JION))
        CNDYNI(JION)=AMUA*RMASSI(JION)
      END DO
C  ATOMIC WEIGHT OF ATOMS = RMASSA(JATM)
      DO JATM=1,NATMI
        RMASSA(JATM)=NMASSA(JATM)*PMASSA
        RSQDVA(JATM)=1._DP/SQRT(RMASSA(JATM))*CVELAA
        CVRSSA(JATM)=RMASSA(JATM)*CVELI2
        ALMASA(JATM)=LOG10(RMASSA(JATM))
        CNDYNA(JATM)=AMUA*RMASSA(JATM)
      END DO
C  ATOMIC WEIGHT OF MOLECULES = RMASSM(JMOL)
      DO JMOL=1,NMOLI
        RMASSM(JMOL)=NMASSM(JMOL)*PMASSA
        RSQDVM(JMOL)=1._DP/SQRT(RMASSM(JMOL))*CVELAA
        CVRSSM(JMOL)=RMASSM(JMOL)*CVELI2
        ALMASM(JMOL)=LOG10(RMASSM(JMOL))
        CNDYNM(JMOL)=AMUA*RMASSM(JMOL)
      END DO
C  ATOMIC WEIGHT OF BULK IONS = RMASSP(JPLS)
      DO JPLS=1,NPLSI
        RMASSP(JPLS)=NMASSP(JPLS)*PMASSA
csw check photon in bulk
        if(rmassp(jpls) > 0._DP) then
          RSQDVP(JPLS)=1._DP/SQRT(RMASSP(JPLS))*CVELAA
          CVRSSP(JPLS)=RMASSP(JPLS)*CVELI2
          ALMASP(JPLS)=LOG10(RMASSP(JPLS))
          CNDYNP(JPLS)=AMUA*RMASSP(JPLS)
        else
          rsqdvp(jpls)=0.
          cvrssp(jpls)=0.
          almasp(jpls)=0.
          cndynp(jpls)=0.
        endif
csw end check
      END DO

      RETURN
      END SUBROUTINE EIRENE_SETUP_ATOMIC_WEIGHTS
