
      SUBROUTINE EIRENE_SETUP_SURFACE_SWITCHES
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CLGIN
      USE EIRMOD_COMPRT, ONLY : IUNOUT

      IMPLICIT NONE

      INTEGER :: ISTS, NLJ, EIRENE_IDEZ, I1000, JSPZ
      EXTERNAL :: EIRENE_EXIT_OWN, EIRENE_IDEZ

      DO ISTS=1,NSTSI
        NLJ=NLIM+ISTS
        ISWICH(1,NLJ)=EIRENE_IDEZ(ILSWCH(NLJ),1,6)
        IF (ISWICH(1,NLJ).EQ.1) ISWICH(1,NLJ)=-1
        IF (ISWICH(1,NLJ).EQ.2) ISWICH(1,NLJ)=1
        ISWICH(2,NLJ)=EIRENE_IDEZ(ILSWCH(NLJ),2,6)
        IF (ISWICH(2,NLJ).EQ.1) ISWICH(2,NLJ)=-1
        IF (ISWICH(2,NLJ).EQ.2) ISWICH(2,NLJ)=1
        ISWICH(3,NLJ)=EIRENE_IDEZ(ILSWCH(NLJ),3,6)
        IF (ISWICH(3,NLJ).EQ.1) ISWICH(3,NLJ)=-1
        IF (ISWICH(3,NLJ).EQ.2) ISWICH(3,NLJ)=1
        ISWICH(4,NLJ)=EIRENE_IDEZ(ILSWCH(NLJ),4,6)
        IF (ISWICH(4,NLJ).EQ.1) ISWICH(4,NLJ)=-1
        IF (ISWICH(4,NLJ).EQ.2) ISWICH(4,NLJ)=1
        ISWICH(5,NLJ)=EIRENE_IDEZ(ILSWCH(NLJ),5,6)
        IF (ISWICH(5,NLJ).EQ.1) ISWICH(5,NLJ)=-1
        IF (ISWICH(5,NLJ).EQ.2) ISWICH(5,NLJ)=1
        ISWICH(6,NLJ)=EIRENE_IDEZ(ILSWCH(NLJ),6,6)
        IF (ISWICH(6,NLJ).EQ.1) ISWICH(6,NLJ)=-1
        IF (ISWICH(6,NLJ).EQ.2) ISWICH(6,NLJ)=1
C
        IF (ISWICH(4,NLJ).NE.0.OR.ISWICH(5,NLJ).NE.0.OR.
     .      ISWICH(6,NLJ).NE.0) THEN
          ILBLCK(NLJ)=EIRENE_IDEZ(ILCELL(NLJ),4,4)
          I1000=1000*ILBLCK(NLJ)
          ILACLL(NLJ)=ILCELL(NLJ)-I1000
        ENDIF
C
        IF (ILSWCH(NLJ).NE.0.AND.ILIIN(NLJ).GT.0) THEN
          DO JSPZ=1,NSPZ
            IF (TRANSP(JSPZ,1,NLJ).NE.0..OR.TRANSP(JSPZ,2,NLJ).NE.0.)
     .      THEN
              WRITE (iunout,*)
     .          'EXIT FROM TIMEA0: SURFACE NO. ISTS OPERATING'
              WRITE (iunout,*)
     .          'A SWITCH BUT IS SOMETIMES TRANSPARENT AND'
              WRITE (iunout,*)
     .          'SOMETIMES REFLECTING (SEMI-TRANSPARENCY OPTION)'
              WRITE (iunout,*)
     .          'POSSIBLE FIXES: SEE MANUAL, CHAPTER 2, SECTION 6'
              WRITE (iunout,*) 'ISTS= ',ISTS
              CALL EIRENE_EXIT_OWN(1)
            ENDIF
          ENDDO
        ENDIF
      END DO

      RETURN
      END SUBROUTINE EIRENE_SETUP_SURFACE_SWITCHES
