!pb  26.10.06: close file after read or write
!pb  31.10.06:  definition of RPART, RPARTC, IPART, IPARTC changed
!               RPART(NPARTT,NPRNL) --> RPART(NPRNL,NPARTT)
C
C
      SUBROUTINE EIRENE_WRSNAP
C
C  SAVE SNAPSHOT POPULATION AT END OF TIMESTEP
C
      USE EIRMOD_PRECISION
      USE EIRMOD_PARMMOD
      USE EIRMOD_CTRCEI
      USE EIRMOD_COMPRT
      USE EIRMOD_COMNNL
      USE EIRMOD_COMSOU
 
      IMPLICIT NONE
 
      INTEGER :: I, J
C
      OPEN (UNIT=15+ifoff,ACCESS='SEQUENTIAL',FORM='UNFORMATTED')
      REWIND 15+ifoff
C
      IF (TRCFLE) WRITE (iunout,*) 'WRITE 15: IPRNL,FLUX,DTIMV '
      WRITE (15+ifoff) IPRNL,FLUX(NSTRAI),DTIMV
      WRITE (15+ifoff) ((RPARTC(J,I),J=1,NPARTT),I=1,IPRNL)
      WRITE (15+ifoff)  (RPARTW(I)              ,I=0,IPRNL)
      WRITE (15+ifoff) ((IPARTC(J,I),J=1,MPARTT),I=1,IPRNL)
      CLOSE (UNIT=15+ifoff)
C
      RETURN
C
      ENTRY EIRENE_RSNAP
C
      OPEN (UNIT=15+ifoff,ACCESS='SEQUENTIAL',FORM='UNFORMATTED')
      REWIND 15+ifoff
      READ (15+ifoff) IPRNL,FLUX(NSTRAI),DTIMV
      IF (TRCFLE) WRITE (iunout,*) 'READ 15: IPRNL,FLUX,DTIMV '
      READ (15+ifoff) ((RPARTC(J,I),J=1,NPARTT),I=1,IPRNL)
      READ (15+ifoff)  (RPARTW(I)              ,I=0,IPRNL)
      READ (15+ifoff) ((IPARTC(J,I),J=1,MPARTT),I=1,IPRNL)
      CLOSE (UNIT=15+ifoff)
C
      RETURN
      END
