      SUBROUTINE EIRENE_BROAD_PEDIST_USR( XTIM )
      USE EIRMOD_PRECISION, ONLY: DP
      USE EIRMOD_PARMMOD, ONLY: NSTRA

      IMPLICIT NONE

      REAL(DP), INTENT(IN) :: XTIM(0:NSTRA) !< time allocated for stratum

      END SUBROUTINE EIRENE_BROAD_PEDIST_USR
